### ISSUE TITLE
Dynamo can't launch from Ribbon - Reflection - System.TypeLoadException thrown

### ISSUE THREAD

**Issue by kmorin** [DynamoDS/DynamoRevit#1003]
## Dynamo version

1.0.0

## Revit version

2016 R2 UR4

## Operating system

Win 10

## What did you do? 

Click the Button

## What did you expect to see?

Dynamo

## What did you see instead?
>Exception was thrown from the ExternalCommand- System.TypeLoadException: Could not load type 'Dynamo.Models.DynamoModel' from assembly 'Autodesk.Bcg, Version=1.7.3.0, Culture=neutral, PublicKeyToken=d672471c03b2c408'.
'   at Dynamo.Applications.DynamoRevit.ExecuteCommand(DynamoRevitCommandData commandData)
'   at apiManagedExecuteCommand(AString* assemblyName, AString* className, AString* vendorDescription, MFCApp* pMFCApp, DBView* pDBView, AString* message, Set<ElementId\,std::less<ElementId>\,tnallc<ElementId> >* ids, Map<AString\,AString\,std::less<AString>\,tnallc<std::pair<AString const \,AString> > >* data, AString* exceptionName, AString* exceptionMessage) 
' 1:< System.TypeLoadException: Could not load type 'Dynamo.Models.DynamoModel' from assembly 'Autodesk.Bcg, Version=1.7.3.0, Culture=neutral, PublicKeyToken=d672471c03b2c408'.
'   at Dynamo.Applications.DynamoRevit.ExecuteCommand(DynamoRevitCommandData commandData)
'   at apiManagedExecuteCommand(AString* assemblyName, AString* className, AString* vendorDescription, MFCApp* pMFCApp, DBView* pDBView, AString* message, Set<ElementId\,std::less<ElementId>\,tnallc<ElementId> >* ids, Map<AString\,AString\,std::less<AString>\,tnallc<std::pair<AString const \,AString> > >* data, AString* exceptionName, AString* exceptionMessage)

![image](https://cloud.githubusercontent.com/assets/191397/15406612/0d8eeb02-1dbc-11e6-8820-650a0c2ae207.png)

**Comment by sharadkjaiswal** [comment]
@kmorin Can you please provide us more details, regarding other Revit plugins available on your system. Did you try installing an older version of Dynamo and did it work before?

**Comment by kmorin** [comment]
Clean install of Dynamo 1.0. Never launched the 0.8 that was included with R2
No other addins loaded.

**Comment by sharadkjaiswal** [comment]
@jnealb, @monikaprabhu  can you please help us reproduce this issue.

**Comment by tatlin** [comment]
@jnealb @monikaprabhu @sharadkjaiswal @kmorin The "Autodesk.Bcg" namespace is typically used by other Autodesk addins like Collaboration for Revit, BIM360Glue, etc, not Dynamo. 

Sounds like this issue: https://forums.autodesk.com/t5/revit-api/system-typeloadexception-at-runtime/td-p/5842093

**Comment by jnealb** [comment]
On it.

**Comment by kmorin** [comment]
Yup, installing the new C4R fixed the Bcg load errors.
