### ISSUE TITLE
Direct Shape Materials not Displaying in Revit 2017

### ISSUE THREAD

**Issue by jpolding** [DynamoDS/DynamoRevit#1004]
![directshape not showing materials](https://cloud.githubusercontent.com/assets/19491424/15429722/3398e4a6-1e70-11e6-9258-a6b82738f91a.png)
![directshape v1 not showing materials](https://cloud.githubusercontent.com/assets/19491424/15429724/339c961e-1e70-11e6-8fa0-30c89692b906.png)
![directshape v9 showing materials](https://cloud.githubusercontent.com/assets/19491424/15429723/339a71ea-1e70-11e6-8439-b13118073cc6.png)

v1 Dynamo version

2017 Revit version

Win10

Make a DirectShape object based on a plane. Apply (green, or any colour) material

I expected to see a (green, or any colour)Direct Shape object

## What did you see instead?

I saw a grey/clear object. Looks like normals are being flipped.

**Comment by mjkkirschner** [comment]
can you please add the .dyn and or at least an image.

**Comment by jpolding** [comment]
I uploaded the pictures of v.9 vs v1. Same Dynamo script. I couldn't see how to upload the dyn, wouldn't let me drag and drop.

Thanks for looking at this...

**Comment by mjkkirschner** [comment]
thanks for the images - will investigate.

**Comment by jpolding** [comment]
I have another similar issue on the 'Dynamo' Forum. I was able to post a version of the dyn there. https://forum.dynamobim.com/t/direct-shape-version-1-bug/4088

**Comment by mjkkirschner** [comment]
tracked internally with: [10141](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10141)

**Comment by kronz** [comment]
Fixed!

**Comment by jpolding** [comment]
Thanks! Do I need to download a new version to apply the fix?

**Comment by kronz** [comment]
If you'd like to try the new Release Candidate, look for one of the latest "RC" builds on DynamoBuilds.com
Thanks!
