### ISSUE TITLE
Select Element carries all data

### ISSUE THREAD

**Issue by ghost** [DynamoDS/DynamoRevit#1005]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

Build 1.0.0.1180
## Revit version

2016
## Operating system

windows 10
## What did you do?

Made a workflow that when user selects room, wall and floor finishes are created.
## What did you expect to see?

If I open up workflow and select room, it creates walls and floors as expected. When I change selection though, I expect the same thing to happen to the new room.
## What did you see instead?

When I select a new room, it causes all the information from the prior run to carry over, i.e even the room moves to the new selected room. I have nothing in my workflow to warrant the move.

here is a sample in which I have already selected room 6 and wall/ floor is created. I then go to select a new room and everything is carried over, including room 6. 

![workflow example](https://cloud.githubusercontent.com/assets/12743950/15452356/dbc4bbd2-201e-11e6-9790-f32206aed04a.gif)

**Comment by kronz** [comment]
@Jezzzza can you attach the workflow (by changing the .dyn file to .jpg) or include a screenshot that can demonstate the workflow?
Thanks
Z

**Comment by sharadkjaiswal** [comment]
I think it's a normal element binding behavior, which updates all the downstream nodes when the input changes. In order to achieve the expected @Jezzzza might want to select all the rooms in one go.

**Comment by kronz** [comment]
@sharadkjaiswal but I think that @Jezzzza is indicating that the selected element (in this case, a room) is moving as well.

**Comment by Jezzzza** [comment]
@kronz is correct, it is moving the selected element as well as replacing some of the element binding. I tried renaming the extension to jpg but doesn't open in image viewer, can't export workspace either as node names aren't visible.

**Comment by sharadkjaiswal** [comment]
Can you please send us the dataset to reproduce this issue at our end?
