### ISSUE TITLE
Custom node can only place family instance(s) in isolation. Multiple use of same CN on graph results in 'last node wins'

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#1014]
## Dynamo version

1.0.0
## Revit version

Revit 2016
## Operating system

Win 10
## What did you do?

I created a Custom Node which generates a prefab building using Adaptive Components (images shown below are not the original project, but a simplified example). As the master plan includes a number of these prefab buildings, the intention was to create a custom node and place multiple instances of it on the graph, each with its specific parameters/variables input to generate each prefab type required for the master plan.
## What did you expect to see?

The required variations of the prefab buildings in their relative locations on the master plan generated by each instance of the Custom Node placed by the design team
## What did you see instead?

Only one prefab building can be generated at a time. Every time a new CN is placed on the graph and its inputs satisfied with the required data, the Adaptive Components output from the previous CN disappear and are replaced by the Adaptive Components output from the new CN - in effect, a _'last node wins'_ scenario. 

The attached images show the object IDs of the output Adaptive Components are identical for every instance of the CN placed on the graph. Hence, Revit removes the previous objects (Adaptive Components) and replaces them with the output from the new CN which indicates where the problem is emanating from. 

Although Adaptive Components were used in the example/original problem, this issue affects CNs that place any Family instance type. If this is 'as intended' behaviour it represents a significant workflow flaw.

**Output from example CN - one instance on the graph:**
![one cn generates adapative components](https://cloud.githubusercontent.com/assets/18601851/15655193/bb796452-2692-11e6-8681-1c6c9993a316.png)
Output in Revit:
![one cn generates adapative components output in revit](https://cloud.githubusercontent.com/assets/18601851/15655252/4b148722-2693-11e6-92ab-951ec165ecdf.jpg)

**Output from example CN - multiple instances on the graph:**
![multiple cn generates only one set of adapative components](https://cloud.githubusercontent.com/assets/18601851/15655417/efb8d372-2694-11e6-88e3-088d356ca11b.png)
Output in Revit:
![multiple cn generates only one set of adapative components output in revit](https://cloud.githubusercontent.com/assets/18601851/15655416/e9df4832-2694-11e6-86a6-c555c35e2675.jpg)

**Comment by kronz** [comment]
@ThomasMahon Interesting.  I wonder if this is a regression or has been there all along.  I can also reproduce this with non-family creating nodes, like wall creation.  
@Randy-Ma @ke-yu  Do you think you can take a look or reassign to someone else?  
![2016-05-30_2233](https://cloud.githubusercontent.com/assets/3456818/15661581/b28421b0-26b6-11e6-8415-b076969d5b84.png)
Tracking internally as MAGN-10165

**Comment by ThomasMahon** [comment]
@kronz I only recently discovered this problem - never attempted it before v1.0.0

**Comment by LukeyJohnson** [comment]
I discussed this with Dimitar, he said this was a transaction issue. Then, we adapted a Clockwork node, you can read about it at https://dynamonodes.com/2016/06/08/family-instance-by-point-in-transaction/

**Comment by ThomasMahon** [comment]
That's definitely on the right track, but the CN in question is not that simple: it generates a prefab house and comprises over 1500 lines of code, outputting up to 20 different AC types ranging from walls, to roofs to frames. These objects are always output from a CBN as its driven by a series of DesignScript definitions in every case. There are currently over 20 permutations, so replication isn't possible as each prefab is unique.

That said, your suggestion may still be adapted to work, however it would invariably require a significant revision to all the code and result in an overly complex data structure that would be difficult to manage. Compounded with DesignScripts problems with data structures beyond rank 3 I'm not going to hazard trying (see #6493). The other issue is usability: the design team place the CN on the graph and wire up a couple of inputs to easily generate a one of the prefab buildings. From what I can glean from your link, the workaround appears to use replication, and that would lead - I suspect - to unwieldy List.Create nodes to satisfy the inputs needed to create the various permutations.

**Comment by ThomasMahon** [comment]
@kronz @ke-yu @Randy-Ma @LukeyJohnson this appears to be fixed in the latest daily build

**Comment by kronz** [comment]
@ThomasMahon Yes, we are still validating this change, but glad to see that you are finding that it is fixed
https://github.com/DynamoDS/Dynamo/pull/7078
