### ISSUE TITLE
Installing a package forces uninstall of other packages

### ISSUE THREAD

**Issue by truevis** [DynamoDS/DynamoRevit#1020]
## Dynamo version

1.0
## Revit version

2016 R2
## Operating system

Windows 10
## What did you do?

Installing Bakery package causes mayhem to already installed packages, which cannot be found out until Revit is restarted

![image](https://cloud.githubusercontent.com/assets/3574046/15735204/b9258ca2-2864-11e6-93a3-c3773285e6f4.png)

Suggest at least a warning, and option to cancel the procedure.

**Comment by thazell** [comment]
Additionally it would be really nice if the packages that need to reinstall would do so rather than just uninstalling.

**Comment by ksobon** [comment]
This is all Dynamo related and not DynamoRevit related. Can we close this issue or move it to other repo? cc: @kronz Thanks!

**Comment by truevis** [comment]
Had it happen again, recently, with dynamo for Revit. Workaround seems to be to make the files in the Packages folder all read-only.

**Comment by ksobon** [comment]
@truevis I am saying that Package Manager is not part of DynamoRevit functionality. It doesn't matter that it happens with Revit related packages. This issue should be posted in Dynamo repo as it pertains to functionality that exists in Dynamo, not in DynamoRevit. Makes sense?

**Comment by thazell** [comment]
@ksobon I'm ok if you want to move it to Dynamo, rather than DynamoRevit if that's more appropriate

**Comment by ksobon** [comment]
This issue was already brought up here: https://github.com/DynamoDS/Dynamo/issues/5487 feel free to add anything "new" to it, and let's close this here since it's duplicating issues.
