### ISSUE TITLE
if node only returns the shortest number of indexed items

### ISSUE THREAD

**Issue by stevedewitt** [DynamoDS/DynamoRevit#1068]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.0

## Revit version

2015

## Operating system

Windows 7

## What did you do? 

create an if statement where true pulls, list A and false pulls list b

## What did you expect to see?

the full list to appear

## What did you see instead?

(example..  if my true list has 0-6 indexes and my false list has 0-4 indexes, my result will only have 0-4 indexes)(some how it is cutting off any listed item beyond 0-4)
![if_statement_issue_01](https://cloud.githubusercontent.com/assets/20214675/16471723/626e0528-3e13-11e6-88e9-817fc83c210f.PNG)

**Comment by andydandy74** [comment]
Use ScopeIf node instead

**Comment by stevedewitt** [comment]
This worked...  thank you..
