### ISSUE TITLE
filepath node issue.

### ISSUE THREAD

**Issue by KWilkinson02** [DynamoDS/DynamoRevit#1093]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.0.0
## Revit version

2015 R2 Update 13
## Operating system

windows 7
## What did you do?

created filepath node to feed a Excel read from file node. when the path is on a drive different from where the .dyn file resides it returns a file path not found error.  when the file path node is replaced by a codeblock with an identical file path (i.e. U:\Test folder\ Test file.xlsx not the UNC equivalent) it works as expected.
## What did you expect to see?

Expected file to be read
## What did you see instead?

error message saying path not found.

**Comment by sharadkjaiswal** [comment]
@KWilkinson02 Can you please provide the snapshot of the error? @riteshchandawar, @monikaprabhu  can you reproduce this scenario?

**Comment by riteshchandawar** [comment]
@sharadkjaiswal @KWilkinson02 I tested this with the slightly higher version of **Revit with Update Release 3**, instead of **2** and my OS is **Win-8.1**. **File Path** node is working for me in the above scenario.

- Ritesh

**Comment by mjkkirschner** [comment]
Does your path have spaces in it?

**Comment by ksobon** [comment]
This was a FilePath node issue and not a DynamoRevit related one. @kronz can we close this? I think it was solved in 1.3 anyways. If not, let's move this to Dynamo github.

**Comment by kronz** [comment]
@jnealb could you do me a favor and verify this is fixed in 1.3?  Close if it is?  thanks!

**Comment by jnealb** [comment]
@kronz It is fixed in 1.3, closing.

![driveisdiff](https://cloud.githubusercontent.com/assets/9357222/26410383/15e4e6de-4071-11e7-99ed-f98167826345.jpg)
