### ISSUE TITLE
Dynamo Background 3D preview is not shown! 

### ISSUE THREAD

**Issue by wafabassam** [DynamoDS/DynamoRevit#1252]
Hello, 

- Dynamo version : AutoDesk Dynamo studio 2017 - Student version 
- Revit version: 1.1.0.2093
- Operating system: Windows 8.1

- The problem: I have downloaded dynamo, and I realized that there is no background 3D preview, all what I see is the nodes but no 3D view whatsoever, as shown in the screenshot 

![1](https://cloud.githubusercontent.com/assets/21977757/18227993/039409fa-7241-11e6-9a6a-5c9074f5761d.PNG)

![3](https://cloud.githubusercontent.com/assets/21977757/18228007/7dbd298c-7241-11e6-9fd9-903ff8a571cb.PNG)

![2](https://cloud.githubusercontent.com/assets/21977757/18228008/7dc47912-7241-11e6-9d00-c1b6091086c8.PNG)

Thank you, 
Regards

**Comment by kronz** [comment]
Hi @wafabassam 
There is a a known issue that is larger than Dynamo regarding hardware configurations with integrated graphics adapter AND advanced or discrete graphics cards. These may have trouble rendering background geometry
https://github.com/DynamoDS/Dynamo/wiki/Known-Issues

https://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/AutoCAD-uses-the-wrong-graphics-card.html

Please re-open this issue if it isn't solved by the solutions offered in these links.

Thanks
Zach
