### ISSUE TITLE
Different indexing in the output

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/DynamoRevit#1253]
1.1.0.2065
Revit 2015 R2
Windows 7

I' ve applied two List.Map nodes to a list of lists (2x7) but the resulting list has a different rank in the second element and the indexing is different from the input

## What did you expect to see?

same number of elements 2x7 in the output as in the input, Empty Lists where the value could not be found

## What did you see instead?

As you can see from the Image, index 1 has only 6 items but the input had 8

![image](https://cloud.githubusercontent.com/assets/14221455/18231213/e402099e-72b2-11e6-86e3-8ab3168786f5.png)

**Comment by kronz** [comment]
Hi @paoloemilioserra 
I think you might want to use IndexOf
![2016-09-05_0833](https://cloud.githubusercontent.com/assets/3456818/18247937/93bf73d6-7343-11e6-9d76-c0792815c5b4.png)
This stuff is pretty confusing, especially when you are looking at applying a list to a collection of sublists.  But @ke-yu , do you see any bug here?  Please re-open if so

**Comment by paoloemilioserra** [comment]
@kronz thank you, I had to use this script to get the data structure I needed:

def FindIndices :var[]..[](input : var[]..[], item : var)
{
	return = [Imperative]
	{
		output = {};

		if(Count(input) != null)
		{
			for(i in 0..Count(input)-1)
			{
				a = input[i];

				if(Count(a) != null)
				{
					temp = {};

					countJ = 0;

					for(j in 0..Count(a)-1)
					{
						b = a[j];

						if(Count(b) != null)
						{
							tmp = {};

							countK = 0;

							for(k in 0..Count(b)-1)
							{
								c = b[k];

								if (c == item)
								{
									tmp[countK] = k;
									countK = countK + 1;
								}
							}

							temp[countJ] = tmp;

							countJ = countJ + 1;
						}
					}

					output[i] = temp;
				}
				else if(a == item)
				{
					outputp[i] = i;
				}
			}
		}

		return = output;
	}
};
