### ISSUE TITLE
Views list not ordered alphabetically

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#1264]
## Dynamo version

1.1 stable
## Revit version

2017
## Operating system

Win 7
## What did you do?

Used the `Views` node
## What did you expect to see?

An alphabetically sorted list of views
## What did you see instead?

Chaos.

Please return the list of views in alphabetical order.

**Comment by kronz** [comment]
@andydandy74 I'm seeing the same View order listing in 0.9.2 and latest daily builds.  Can you show what you want to return to?

**Comment by andydandy74** [comment]
@kronz I don't want to return to anything - it's not a regression. I'd like to move towards an alphabetical order. This has been bugging me for as long as I've been using Dynamo but somehow I never posted an issue.

**Comment by kronz** [comment]
@andydandy74 ah, sorry, I mis-read your "please return".  i thought you were refering to a previous state.  Looks like this dropdown probalby uses element id for sorting, which is almost never what anyone wants

**Comment by ksobon** [comment]
@andydandy74  this was fixed. Can you close?

**Comment by andydandy74** [comment]
Sure
