### ISSUE TITLE
Improvement: Cache Family Type Selection in DYN to prevent data loss

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#1288]
## Dynamo version

1.1.0

## Revit version

R2016

## Operating system

Win 10

## What did you do? 

Used the Family Type node from Revit > Selection library. Picked a user created Family that was loaded into the Revit document.

Later on:
I opened the DYN and not the original RVT it was pointing to...

## What did you expect to see?

No change to the selection, (of course, I would expect to see an error during run time since the Family is only found in the original document)

## What did you see instead?

The Family Type selection is nulled, even on manual execution without running! Simply open... and bang, indiscriminately all selections are gone. This issue affects all selection node types that the DYN references where object types in one Revit document are not present in another. It would be good if the selection can be cached in the DYN so there is no loss of data - its just a bit irritating to have to re-select (or close>reopen after opening the RVT), especially as its typical in Revit to navigate between different docs in the same session, or open the DYN first then its accompanying RVT second meaning this penalty is not - strictly speaking - the fault of the user.

**Opened DYN before opening the RVT:** Family Type selection node gets wiped
![image](https://cloud.githubusercontent.com/assets/18601851/18546222/ac431fa4-7b34-11e6-9479-c0b118a27922.png)

**Opened RVT before opening the DYN:** Works as expected
![image](https://cloud.githubusercontent.com/assets/18601851/18546257/e85c19f0-7b34-11e6-9101-15495b36c07b.png)

**Comment by kronz** [comment]
HI @ThomasMahon .  The dropdown value actually IS cached in the file.  For instance, this is what is kept in a Family Types node in one of our sample files.
DSRevitNodesUI.FamilyTypes guid="2bc4ccef-dee5-4567-b976-89536f8908ce" type="DSRevitNodesUI.FamilyTypes" nickname="Family Types" x="1786.66817051115" y="953.079173874116" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="2:3PointAC_SquareTruss:3PointAC_SquareTruss" 

And this data is not dumped from the file UNLESS you safe the file after openinging it and it doesn't find the original data.  The reason that the value is immediately cleared even when in manual mode is the same reason that you can have a fully populated dropdown list of families that ARE in the file when in manual mode.  These nodes will go into the active document and find the available values wether or not the DYN file is executing.  Otherwise, you would have to execute the whole graph just to get these dropdowns to populate.

**Comment by ThomasMahon** [comment]
Hi @kronz I see, so to simplify the question then, is there anyway to 'store' the selection and change the behaviour of the node slightly such that it turns yellow with a warning that the Family etc cant be found in the current document rather than clearing the selection entirely?

**Comment by kronz** [comment]
@ThomasMahon most things are possible, they just take time/design, but what is your desired workflow?  If you open a file that doesn't have a particular family, view, etc existing in the document that you create or load it before first run?

**Comment by ThomasMahon** [comment]
@kronz That would be a good enhancement. Ultimately, I would like to see the Revit selection nodes retain their object selection even when it cant be found in the current document. I think the behaviour would be improved if this was the case. The exception can be handled by showing a warning that the object cant be found (if the graph is executed), rather than resetting and loosing any selections as currently occurs

**Comment by andydandy74** [comment]
@kronz - Something I'd really like to see is Dynamo not overwriting selected values of UI nodes like dropdowns - even if those values are not present in the current model. Here's a use case that I frequently run into: I have a test model for almost every graph. Sometimes I need to update a graph for documentation but forget to open it with the correct model. In that case all the preselected values (e.g. Family Types) will be lost as soon as I save the graph. I would prefer the following behaviour: UI nodes store the last selected value as long as they have not been explicitly set to another value.

**Comment by kronz** [comment]
@ThomasMahon @andydandy74 while I understand that it isn't nearly as convenient as the approach you are describing, do either of you ever use nodes like FamilyType.ByFamilyNameAndTypeName to get this kind of hard-coded behavior?
![2016-09-23_0529](https://cloud.githubusercontent.com/assets/3456818/18781211/d6412790-814e-11e6-8924-f86f608a46b8.png)

**Comment by andydandy74** [comment]
Never. Too prone to human error aka typos 😉

**Comment by ThomasMahon** [comment]
@andydandy74 Agree. 
@kronz its a decent workaround but the workflow is laborious: 1. open Revit document 2. find Family/Type 3. Add string/code block node 4. Enter names being sensitive to type. Explain this workflow to most users (most of the users I support are architects) and its a hard sell. Drop-downs on the other hand are very accessible and convenient, and that's where the solution should be focused
