### ISSUE TITLE
"Dynamo uses meters for length units" on wiki appears to be incorrect

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#1311]
## Dynamo version

1.2.0.20160923T0045

## Revit version

2016

## Operating system
Win 10

## What did you do? 

Used Python node + Revit API to add new points to a floor. XYZ were created in the script from a list of coordinates (doubles). It failed.

I debugged by passing a list of equivalent Dynamo points and converted them using `ToXyz()` and noticed it was a units conversion issue (mm not converted to feet)

Once I converted from mm (the Revit docs units) to feet worked as expected.

## What did you expect to see?
This is what it says on the Dynamo Python wiki. I would like to know if this statement is correct or if there is a bug in the latest build of Dynamo:

![image](https://cloud.githubusercontent.com/assets/18601851/18810322/2c19a6aa-828b-11e6-92d9-241b97e2ab42.png)

## What did you see instead?

Conversion from mm to feet instead:
![image](https://cloud.githubusercontent.com/assets/18601851/18810333/7ed095fc-828b-11e6-805a-8300eeedfa07.png)

List[1] shows the new XYZ with unit conversion from mm to feet. List[2] shows the Dynamo points converted using `ToXyz()` I used for debugging:
![image](https://cloud.githubusercontent.com/assets/18601851/18810405/f5a619ee-828c-11e6-99ed-90bd136032c8.png)

**Comment by andydandy74** [comment]
The only thing that isn't true any more is the one about Dynamo' units being metric. Dynamo units now are the same as the display units of the Revit model you're working on. The thing about having to convert units is, sadly, still true. The page you're referring to was created for helping users migrate their Python code from v0.6.3 to v0.7.x. Unfortunately it's the still the best resource on Python coding for Revit within Dynamo - except for that thing with the units....

**Comment by ThomasMahon** [comment]
Thanks for confirming.
