### ISSUE TITLE
Can't build source

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/DynamoRevit#1312]
I am not missing any references but I am getting this error: 

![image](https://cloud.githubusercontent.com/assets/529781/18810907/1b37df8e-8270-11e6-8bb5-abac2368920f.png)

![image](https://cloud.githubusercontent.com/assets/529781/18810909/320e4a7c-8270-11e6-9b38-06b82ec0d651.png)

Any ideas if I am missing something and if yes, what would that be? 

Cheers! 

cc: @ikeough @mjkkirschner

**Comment by mjkkirschner** [comment]
These are new APIs which are added in Dynamo 1.2x, what are you trying to compile?

It looks like you are trying to build Revit 1.2 on Dynamo 1.1

**Comment by ksobon** [comment]
ahhh, in that case I will have to move up one version. :-) thanks for the tip.
