### ISSUE TITLE
PolyCurve.ByPoints

### ISSUE THREAD

**Issue by jhubers** [DynamoDS/DynamoRevit#1319]
## Dynamo version

1.1.0.2065

## Revit version

2016

## Operating system

 Windows 8.1,

## What did you do? 

Used PolyCurve.ByPoints

## What did you expect to see?

Description stating that you can close the curve with bool.

## What did you see instead?

Description stating that last point should be at same location as start point. Also the icon is misleading.

**Comment by kronz** [comment]
@ellensi Could you make this change in Master?  seems like a quick thing that shouldn't have the overhead of a planned task, no?

**Comment by ellensi** [comment]
Tracked internally as [MAGN-10710](https://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-10710), as a UX decision needs to be made.

![image](https://cloud.githubusercontent.com/assets/6386550/18898762/4b74ab20-8566-11e6-9682-4448853d6f9c.png)

**Comment by aparajit-pratap** [comment]
Fixed
