### ISSUE TITLE
Intersection / Difference fails with error "BAD_CONTAINMENT"

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/DynamoRevit#1325]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1.0.2094
## Revit version

2016
## Operating system

Windows 7 
## What did you do?

Import an STL file, create a Project mass, read in both as solids and intersect/difference/difference all.
## What did you expect to see?

the new intersection / difference solid
## What did you see instead?

> Warning:Geometry.Intersect failed.
> Unable to create intersection boolean : BAD_CONTAINMENT -- inconsistent containment of intersection curve

What exactly does that mean? Is it a Bug?

**Comment by kronz** [comment]
@redinkinc i'm guessing that your STL import into Revit isn't really a solid . . . how did you import it?  can you do other operations with it, like use it in a Mass Floors operation?  Does it have a volume?  Upload an image of your graph?

**Comment by redinkinc** [comment]
Hey, I did a workaround for this. It has still some strange behavior, but I managed to handle it. So I close this issue. Just reopen it if you have further questions. Fabian

**Comment by Hao-666** [comment]
Hi @redinkinc, same problem, how did you solve it? Thanks.
