### ISSUE TITLE
Some nodes became too wide

### ISSUE THREAD

**Issue by jhubers** [DynamoDS/DynamoRevit#1336]
## Dynamo version
1.2.0.2690
## Revit version
2016
## Operating system
Windows 8.1,
## What did you do? 
Opened existing files and new workspace.
## What did you expect to see?
Nothing special.
## What did you see instead?
Some very wide nodes. E.g. DirectShape.ByGeometry has inputs that are too wide.

**Comment by josols** [comment]
No pics here, but I guess it is caused by the new list level system introduced with the 1.2 release. This affects the width of the nodes. Have a look at the blog over at dynamobim.org.

**Comment by kronz** [comment]
As designed for list@level functionality

**Comment by jhubers** [comment]
Maybe a good idea then to only enlarge the node if one uses the list@level option? Nice feature by the way.
