### ISSUE TITLE
IronPythonEvaluator Error 2

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/DynamoRevit#1337]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1.0.2094
## Revit version

Revit 2015
## Operating system

Windows 7
## What did you do?

The customer tried to run a Python Script that is working on my laptop but not on his. He cleaned install Dynamo on the machine a couple of times, upgraded to 1.2.0 but the problem persists
## What did you expect to see?

The execution of the Python Script completed correctly
## What did you see instead?

Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. 
Traceback (most recent call last):
  File "<string>", line 65, in <module>
IOError: [Errno 2] Could not find a part of the path 'C:\Program Files\Dynamo\Dynamo Core\1.1\UI\Fonts'.

**Comment by ksobon** [comment]
@paoloemilioserra is this still an issue? Dynamo 1.3.

**Comment by paoloemilioserra** [comment]
Unfortunately I cannot say

**Comment by ksobon** [comment]
@kronz can we close this?
