### ISSUE TITLE
Can't start Dynamo [business impact]

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/DynamoRevit#1338]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.1.0.2094

## Revit version

Revit 2017

## Operating system

Windows 7

## What did you do? 

Clicked on Dynamo Icon  on the Ribbon bar

## What did you expect to see?

Start a new Dynamo Session, 

## What did you see instead?

(Fill in here)
![image](https://cloud.githubusercontent.com/assets/14221455/19143363/a7f7cdb2-8ba3-11e6-95f7-605e3f0a8a38.png)

**Comment by paoloemilioserra** [comment]
The issue is connected to an exception of mscorlib.dll when attempts to call GetTempFilePath(), an exception is raised when the TEMP folder contains more than 65535 files.
A preliminary test to inform the user that a cleanup of the temp folder is necessary might be in order.

**Comment by jnealb** [comment]
Thank you @paoloemilioserra
