### ISSUE TITLE
Editing the Key Schedule node from archi-lab package

### ISSUE THREAD

**Issue by myasemin** [DynamoDS/DynamoRevit#1346]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

0.9
## Revit version

2016
## Operating system

Windows 8.1
## Extra input to **addFields** to the KeySchedule node

Using the Key Schedule node from archi-lab package, **the aim is to create multiple schedules** so that a sorted list can feed into each schedule (so that using Dynamo tools the data input is filtered). The idea to solve this problem would be if there is an input to **add fields** to the node since Key Schedules need unique parameters for each schedule that's created. 

**ORIGINAL SCRIPT from first Python node in KeySchedule from archi-lab**
![original_keyschedule_python1_scripttransaction](https://cloud.githubusercontent.com/assets/22797330/19388390/4373bde0-9217-11e6-8027-49347da0d017.PNG)

**EDITED SCRIPT of above extract attempting to input addFields**
![edit_keyschedule_python1_scripttransaction](https://cloud.githubusercontent.com/assets/22797330/19388395/473a02c2-9217-11e6-8fac-3bab7c230d32.PNG)

**Comment by myasemin** [comment]
Ok so Key Schedule has two python scripts inside so if I edit them both to add an input of "fields" I am starting with something like this >>>

I have found some codes for Revit API to add fields to a schedule, but they start with _if_ but there is no return for the results so when do I insert something like this

I edited both of the python script nodes so that the inputs match but the second node only refers to the KeyNames data entry so I didn't change anything for the other inputs there??

**Python script node 1:**
#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

from System.Collections.Generic import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#trying here i have added another input to input the fields
keySchedule = UnwrapElement(IN[0])
fields = IN[1]
data = IN[2]
inputParams = IN[3]

# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

test = []
count = []
cellParams = [[] for i in range(len(data))]
if any(isinstance(item, list) for item in data):
	# trying here to add fields to the schedule
	public void AddFieldToSchedule(List
            
            
             
              schedules)
{
    IList
	schedulableFields = null; foreach (ViewSchedule vs in schedules){ 
	Get all schedulable fields from view schedule definition. 
	schedulableFields = vs.Definition.GetSchedulableFields(); 
	foreach (SchedulableField sf in schedulableFields){ bool fieldAlreadyAdded = false; 
	//Get all schedule field ids IList
	ids = vs.Definition.GetFieldOrder(); foreach (ScheduleFieldId id in ids){ 
	if (vs.Definition.GetField(id).GetSchedulableField() == sf) { fieldAlreadyAdded = true; break; } } 
	if (fieldAlreadyAdded == false) { vs.Definition.AddField(sf); } } } }
	for i in data:
		count.append(len(i))
	colCount = max(count)
	colAvailable = len(keySchedule.Definition.GetSchedulableFields())
	if colCount > colAvailable:
		message = "Please add/remove parameters to/from schedule so that they match longest data set."
	else:
		tableData = keySchedule.GetTableData()
		sectionData = tableData.GetSectionData(SectionType.Body)
		if sectionData.NumberOfRows - 2 <= len(data):
			# schedule by default will have 2 rows (A, B, C and Header Names)
			rowsToAdd = (len(data) - sectionData.NumberOfRows) + 2
			for i in range(0, rowsToAdd, 1):
				sectionData.InsertRow(0)
		else:
			# schedule when updating might already have too many rows 
			rowsToDelete = sectionData.NumberOfRows - 2 - len(data)
			for i in reversed(range(sectionData.NumberOfRows - rowsToDelete, sectionData.NumberOfRows, 1)):
				sectionData.RemoveRow(i)

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = keySchedule

**Python script node 2:** 
#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
import sys
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

from System.Collections.Generic import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)
import re

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

keySchedule = UnwrapElement(IN[0])
fields = IN[1]
data = IN[2]
inputParams = IN[3]
upper = IN[4]

# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

tableData = keySchedule.GetTableData()
sectionData = tableData.GetSectionData(SectionType.Body)

keyNames = []
for i in range(1,sectionData.NumberOfRows - 1,1):
	keyNames.append(str(int(i)))

allKeys = FilteredElementCollector(doc).WhereElementIsNotElementType()
params = [[] for i in range(len(keyNames))]
test = []
for key in allKeys:
	try:
		if key.get_Parameter(BuiltInParameter.REF_TABLE_ELEM_NAME).AsString() in keyNames and key.OwnerViewId == keySchedule.Id:
			indexValue = keyNames.index(key.get_Parameter(BuiltInParameter.REF_TABLE_ELEM_NAME).AsString())
			for i in range(0, len(inputParams),1):
				params[indexValue].extend(key.GetParameters(str(inputParams[i])))
	except:
		pass

for i, j in zip(params, data):
	for param, value in zip(i,j):
		if isinstance(value, str):
			valueDecoded = value.decode('string_escape')
		else:
			if value == None:
				valueDecoded = " "
			else:
				valueDecoded = str(value).decode('string_escape')
		if upper:
			valueDecoded = valueDecoded.upper()
			param.Set(valueDecoded)
		else:
			param.Set(valueDecoded)


# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = keySchedule

**Comment by ksobon** [comment]
@myasemin can you please close this issue?
