### ISSUE TITLE
Dynamo Crashes on connecting first two nodes

### ISSUE THREAD

**Issue by Oszey** [DynamoDS/DynamoRevit#1350]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

0.9.1.4062
## Revit version

Revit 2017
## Operating system

Windows 10 Pro
## What did you do?

1 - Enter first node (Number)
2 - enter second node (Point ByCoordinates)
3 - Begin to connect output to inputs.
4 - Crash
## What did you expect to see?

Just what was being shown in the tutorial for beginners
## What did you see instead?

   at Dynamo.UI.Controls.PreviewControl.<>c__DisplayClassc.<RefreshExpandedDisplay>b__b(AsyncTask m)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Oszey** [comment]
I'm new to Dynamo. I was attempting to begin the basics by using the tutorials provided but could not get past the first two nodes. The above mentioned issue keeps happening (Dynamo Crashes). Can some one help me?

**Comment by sharadkjaiswal** [comment]
@oszey this issue is fixed in latest build. Please upgrade to Dynamo 1.2 from www.Dynamobim.com

**Comment by Oszey** [comment]
Thanks sharad. Its working fine. I initially did the updated, but wasn't using it. I was given an option to choose a version when starting Dynamo in Revit and I though It would have been a problem using the latest version with Revit so I chose the 0.9 version. How do I get rid of the old version with out affecting Revit?

**Comment by ke-yu** [comment]
@Oszey you can uninstall the older version.
