### ISSUE TITLE
Intermittent failure of ToProtoType() method in Python node

### ISSUE THREAD

**Issue by darrenhewett** [DynamoDS/DynamoRevit#1357]
Dynamo version: 1.2.0
Revit version: 2016
Operating system: Windows 7

## Steps to reproduce

Run the ToProtoType() method on a number of Revit GeometryObjects to convert into Dynamo's geometry system as documented here: [https://github.com/DynamoDS/Dynamo/wiki/Python-0.6.3-to-0.7.x-Migration#geometryobjects]

The code I am using is as follows:
```python
import clr
import sys
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.AddReference("RevitServices")
import RevitServices

walls  = UnwrapElement(IN[0])

# Function to get first solid GeometryObject in an element
def get_solid(element):
	geos = []
	for geo in element.get_Geometry(Options()):
		geos.append(geo)
	return geos[0]

results = []
err = []
for wall in walls:
	# Get geometry (converting to Dynamo type is the step which seems to fail)
	try:
		geometry = get_solid(wall).ToProtoType()
	except:
		e = sys.exc_info()[1]
		err.append(['Failed to get solid', wall, e])
		continue

if err:
	OUT = err
else:
	OUT = geometry
```

I have also attached the Dynamo script and Revit project file I am using. Note that the script works pretty reliably on an array of 10 walls but will fail intermittently on array sizes of 100 and above. I have also tried this on different computers and for some reason a faster machine will handle even 200 most of the time so even larger array sizes may be needed to reproduce this error.

## What did you expect to see?

No errors and the last geometry seen in the array should be displayed in Dynamo.

## What did you see instead?

When large arrays of walls are used an exception is raised (although not always the same one):
>Unable to create polygon : BAD_DELETE_BB -- deleting bulletin board - not in list

[ToProtoTypeDemo.zip](https://github.com/DynamoDS/DynamoRevit/files/541303/ToProtoTypeDemo.zip)

**Comment by mjkkirschner** [comment]
Do not let the dynamo geometry objects go out of scope without disposing them. Call dispose before you go to the next iteration of the loop or store a list of them.

**Comment by darrenhewett** [comment]
Thanks @mjkkirschner, I'm not used to manually disposing objects in Python but after adding `geometry.Dispose()` to my code above it now executes correctly.
