### ISSUE TITLE
DirectShape.ByGeometry files with "function" in Dynamo 1.2

### ISSUE THREAD

**Issue by jluebker** [DynamoDS/DynamoRevit#1359]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## What did you do? 

tried "baking" a solid into Revit using Directshape.ByGeometry and received "function" as an output. I then tested with a cuboid. Same result.

![image](https://cloud.githubusercontent.com/assets/4041748/19583521/555a8644-96f2-11e6-807c-0a4e4bbc5820.png)

**Comment by mjkkirschner** [comment]
looks like you have the default values turned off, try right clicking on all ports and checking if they are all enabled.

**Comment by andydandy74** [comment]
Actually, there's no default value for category. You must assign a category.

**Comment by jluebker** [comment]
oh true, sorry
