### ISSUE TITLE
Errors with Python script to copy and rename grids from linked file

### ISSUE THREAD

**Issue by salvodragotta** [DynamoDS/DynamoRevit#1360]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

Dynamo Core 1.2.0.2831
Dynamo Revit 1.2.0.2654
## Revit version

Revit 2016
## Operating system

Windows 10
## What did you do?

Python script to copy and rename grids from linked file.

Refer to the following post in the Dynamo Forum

https://forum.dynamobim.com/t/copy-grids-from-linked-model/6913/4
## What did you expect to see?

grids created and renamed.
## What did you see instead?

AttributeError: 'type' object has no attribute 'Create'
AttributeError: can't assign to read-only property Name of ype 'Grid'

Someone else has tested it in the RevitPythonShell and it works.

**Comment by mjkkirschner** [comment]
you've imported both the revitapi and our wrappers which include a grid type:https://github.com/DynamoDS/DynamoRevit/blob/7270187e8688fbd8ec538b4617810dccdb9a695f/src/Libraries/RevitNodes/Elements/Grid.cs#L16

you need to be specific about what type you are referring to. You are probably referring to ours which does not have a Create method. Use the full module name.

**Comment by ksobon** [comment]
Looks like @dimven solved this in the Forum. Can we close? cc: @kronz
