### ISSUE TITLE
RTF References for Dynamo Package

### ISSUE THREAD

**Issue by eertugrul** [DynamoDS/DynamoRevit#1380]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo 1.1 or Dynamo 1.2

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version
Revit 2015

(Which version of Revit are you using?)

## Operating system
Windows 7
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
developing DynamoSAP plugin, updating the dlls for dynamo package testing project
download dynamo 1.1, i was able to re-reference most of the dlls, bur couldn't locate the some of the references for RTF 

(Fill in here)

## What did you expect to see?
@ikeough 
references to test dynamo packages are missing from DynamoBim download. 
https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Package-Testing-With-the-Revit-Test-Framework-(RTF)

RevitTestFrameworkTypes.dll
RevitTestServices.dll
SytemTestService.dll

the dlls should be located 
$(DYNAMO_API)\$(REVIT_VERSION)\RevitTestServices.dll

## What did you see instead?
the references listed above are missing...

(Fill in here)

**Comment by mjkkirschner** [comment]
I believe these test dlls are not distributed with the installer and instead are in this repo.

**Comment by mjkkirschner** [comment]
should clarify, when you build dynamo, and then build DynamoRevit, the test services dlls will be copied to the Revitversion folder inside the Dynamo bin directory. ie. Dynamo/bin/AnyCPU/debug/Revit2017/

**Comment by mjkkirschner** [comment]
reopen this if I have misunderstood.
