### ISSUE TITLE
Code Block inactive

### ISSUE THREAD

**Issue by jmbyker** [DynamoDS/DynamoRevit#1385]
After updating Revit 2017, code blocks are grey'ed out, and i can't write anything.
In Revit 2016 they work well.

## Dynamo version

1.2

## Revit version

2017

## Operating system

Windows 10

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by ksobon** [comment]
@jmbyker can you give us some more information about this issue? Was there an error produced by the code block? can you post your log files? We will need more than just that to re-create the issue and solve it. 

cc: @kronz if we don't hear back in few days let's close this. Thanks!

**Comment by kronz** [comment]
@jmbyker This sounds like a conflict we were experiencing with 2 versions of Avalon Edit, a text editor that is also used in other areas of Revit.  Should be resolved in 1.3
