### ISSUE TITLE
Background preview problem

### ISSUE THREAD

**Issue by Mateusz1234** [DynamoDS/DynamoRevit#1390]
Hello,
After many attepmts of getting my dynamo work properly I still can't see anything in background preview screen.
I set up my graphic card to high performance for revit.exe and dynamosandbox.exe programs and it didn't help.
I downloaded and installed all the recent graphic card drivers and double checked my directX - no results.
I upgraded Dynamo from 0.9 to 1.2 - no results. Still blank screen. 

Please help
M

Revit 2017
Dynamo 1.2
Windows 7 Pro
Lenovo e420s laptop
[DxDiag.txt](https://github.com/DynamoDS/DynamoRevit/files/579710/DxDiag.txt)

**Comment by mjkkirschner** [comment]
It does not seem that your intel hd integrated card supports the necessary directx and your machine does not have a discrete gpu- it might still be possible to force software rendering mode for revit and this may enable software rendering for dynamo.

**Comment by Mateusz1234** [comment]
I believe that on top of intel hd integrated graphics this laptop has also AMD Radeon HD6630M.

**Comment by kronz** [comment]
@Mateusz1234 if that is the case, might need to turn off one or the other card.
https://github.com/DynamoDS/Dynamo/wiki/Known-Issues
https://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/AutoCAD-uses-the-wrong-graphics-card.html

**Comment by Mateusz1234** [comment]
Thank you kronz. By turning off one or the other card do you mean doing that in bios?
I already found these posts and tried recommended actions included but it didn't bring any effect. 
Tho it is most likely a graphic software problem.
Dual graphic cards computers are not something unusual, are they? Is it so complicated to make a fix of this known issue? Sadface

**Comment by kronz** [comment]
@Mateusz1234 I'm afraid that the dual card issue isn't an easy one to fix, and also one that is not limited to Dynamo.  For instance, the  link includes resource for how to fix the same issue in Autocad.
