### ISSUE TITLE
Warning: Internal error, please report: Dereferencing a non-pointer. (3f47aacd)

### ISSUE THREAD

**Issue by haley-bueno** [DynamoDS/DynamoRevit#1395]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.0.1.1503 (1.2.0.0) ?

## Revit version

Revit 2015 - 20150704_0715(x64)
Update Release 9

## Operating system

Windows 7 Enterprise

## What did you do? 

I created a routine to import from Excel into Revit

## What did you expect to see?

Not that error as I have done this previously and everything worked fine. However, this time I had to test other ways to get the info, and i lost track of the various combinations I made.

## What did you see instead?

The Warning and the routine could not be processed.

[IE0311734_HVAC%2520Zoning_Pressure%2520Profile_&_Sprinkler%2520Density.xlsx](https://github.com/DynamoDS/Dynamo/files/594478/IE0311734_HVAC.2520Zoning_Pressure.2520Profile_._Sprinkler.2520Density.xlsx)

![ie0311734_revit to excel](https://cloud.githubusercontent.com/assets/19666291/20346144/73e004a8-abf2-11e6-8f78-d29d22209ecd.png)

![ie0311734_excel to revit](https://cloud.githubusercontent.com/assets/19666291/20346209/cef11eea-abf2-11e6-845d-ca1bbbf7d103.png)

**Comment by ksobon** [comment]
What's the issue? Can you point out one place in that graph that is not working for you?

**Comment by haley-bueno** [comment]
Hi Konrad. Thank you for getting back to me.
The issue is that I had routines that had worked for the past year to export from Revit to Excel and back, which were recently used to recreated new routines having them as basis for the new ones. However, I no longer have them working, and the error mentioned appears when I run the routine to import data back into Revit.

I have tried a variety of connections to push the info back, and I lost track of what should work.

The issue happens when the info needs to be transferred back to the elements, as you can see in the image above. Before, I used to connect the Elements from the "Element.SetParameterByName" node directly into the Elements from "All Elements of Category" node, This now returns into a warning stating that it is read only. Therefore, i tried the version that is on the image but I got the error I published,

Strangely enough, I have just ran another routine again from Revit to Excel (which was working on Friday) and it gave me a different error and it did not produce the Excel file. Please, see image attached. The error stated: "Warning: Excel.WriteToFile operation failed. Exception from HRESULT: 0x800A03EC"

![ie0311988_revit to excel a](https://cloud.githubusercontent.com/assets/19666291/20479086/c016295c-afd4-11e6-9a78-2af83a771c0f.png)

So, it is getting very frustrating to do this, supposed, simple routine. 
If I could attach the files I could send them to you so that you could take a closer look at them.

I thank you beforehand for your help and attention.

Kind regards, Haley

**Comment by mjkkirschner** [comment]
@kronz readonly issue again.

**Comment by haley-bueno** [comment]
Hi MJK,

Thanks for your reply.
One thing that leaves me confused is that part of the routine is working back again as I had initially done. So, the read only issue and warning is not displaying anymore. I am clueless!
Thank you anyway.

**Comment by ksobon** [comment]
@mjkkirschner do you know what the "read only issue" refers to? I can think of `Element.SetParameterValueByName` having trouble getting the right parameter if there are multiple with the same name and throwing this exception when it makes a wrong choice. Is that what you are referring to?

**Comment by mjkkirschner** [comment]
@ksobon yep - this should be fixed now.

**Comment by ksobon** [comment]
@kronz can we close this?
