### ISSUE TITLE
Code Block Conditional Statement returns wrong value

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/DynamoRevit#1399]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.0.2690

## Revit version

2017.1

## Operating system

Windows 7

## What did you do? 
I'm using a conditional statement in a code block, when the input "a" is greater than 3 it should return a list of the inner elements, otherwise a list containing only the second item. Here is the formula.
output = Count(a) > 3 ? a[1..Count(a) - 2] : {a[1]};

## What did you expect to see?
let's a = {0, 1, 2, 3} -> output = {1, 2}
let's a = {0, 1, 2} -> output = {1}

## What did you see instead?

The above formula always return the false member. If I remove the curly brackets from the false member if works properly but I need a list of 1 item and not just the item

**Comment by andydandy74** [comment]
It's a feature. :-D Really.
Try this:
```
result[0] = a[1..Count(a) - 2];
result[1] = {a[1]};
result[Count(a) > 3 ? 0 : 1];
```
This has been discusssed here:
https://github.com/DynamoDS/Dynamo/issues/6491
And here:
https://github.com/DynamoDS/Dynamo/issues/6258
And here:
https://github.com/DynamoDS/Dynamo/pull/4464
And here:
https://github.com/DynamoDS/Dynamo/issues/3106

**Comment by paoloemilioserra** [comment]
Thanks!

**Comment by andydandy74** [comment]
You're not alone with that sentiment.
