### ISSUE TITLE
python node and code block not editable

### ISSUE THREAD

**Issue by Makhamat** [DynamoDS/DynamoRevit#1402]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version 1.2

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version 2017.1

(Which version of Revit are you using?)

## Operating system Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
Tried to place a codeblock/python node and edit it
(Fill in here)

## What did you expect to see?
to get a node edited
(Fill in here)

## What did you see instead?
grey codeblock window. which is not editable / black python script editing window unable to edit
(Fill in here)
![image](https://cloud.githubusercontent.com/assets/23701684/20564989/541d5872-b198-11e6-8779-21ab2863b232.png)

![image](https://cloud.githubusercontent.com/assets/23701684/20565006/664897aa-b198-11e6-848d-795a48f1589e.png)

**Comment by ksobon** [comment]
this looks like a bad Dynamo install. Did you try re-installing, and making sure that Dynamo 1.3 is the only installed version of Dynamo. It doesn't play nice with other versions.

**Comment by Makhamat** [comment]
I had Dynamo 0.9 installed, i removed it and now it works. Thanks for your reply

**Comment by ksobon** [comment]
@kronz can we close this issue?
