### ISSUE TITLE
Dynamo - Numbering Section Views

### ISSUE THREAD

**Issue by JacobWestergaard** [DynamoDS/DynamoRevit#1462]
## Dynamo version

1.2

## Revit version

2016 UR6 R2

## Operating system

Windows 7

## What did you do? 

Numbering Section Views with dynamo the elevations are considered as section views. So the first section number starts at 11. I have attached the dynamo script. Any idea?

https://we.tl/jhpQX9W5XU - link to script
Picture attached as well to illustrate.

## What did you expect to see?

That the elevations wouldn't be included

## What did you see instead?

That they were included

![image001](https://cloud.githubusercontent.com/assets/25180592/22030682/492d5372-dcd6-11e6-8298-291ed2ad2aec.png)

**Comment by ksobon** [comment]
This question belongs on the Dynamo Forum. @kronz can we close this?

**Comment by kronz** [comment]
@JacobWestergaard , yes, I believe that @ksobon is indicating that this is the "correct" behavior in relation to the underlying Revit structure, Elevations being a kind of Sectional view.
