### ISSUE TITLE
Room.Area node reports area in Project Length units.

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/DynamoRevit#1466]
## Dynamo version

1.2.1

## Revit version

2017

## Operating system

Windows 10

## What did you do? 

Room.Area 

## What did you expect to see?

Area in area units specified for the project.

## What did you see instead?

Area reported in project length units. 

Example: 

![image](https://cloud.githubusercontent.com/assets/529781/22051562/25114b2e-dd12-11e6-99aa-16ed91dfd826.png)

cc: @mjkkirschner @moethu

**Comment by moethu** [comment]
thanks @ksobon will check the conversion

**Comment by moethu** [comment]
https://github.com/DynamoDS/DynamoRevit/pull/1474
