### ISSUE TITLE
DesignScript file containing class definition fail to load in Dynamo for Revit

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/DynamoRevit#1472]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1.3083

## Revit version

2017

## Operating system

W7

## What did you do? 

I wrote a DS file containing a class with constructors, properties and methods. When tested in Dynamo SandBox everything works fine but the trying to load in Dynamo for Revit returns a failure

## What did you expect to see?

A new shelf in the library with the constructors actions and query nodes 

## What did you see instead?

Failed to load 
[Marker.zip](https://github.com/DynamoDS/DynamoRevit/files/722202/Marker.zip)

**Comment by mjkkirschner** [comment]
Class syntax I believe is not supported from ds any longer

**Comment by paoloemilioserra** [comment]
weird because it is working fine in Sandbox

**Comment by mjkkirschner** [comment]
see : https://github.com/DynamoDS/Dynamo/issues/7485

**Comment by paoloemilioserra** [comment]
ok then I will close the issue, but just for you to know the class is still recognized (at least the constructors), the failure happens only when parameters are declared
