### ISSUE TITLE
Material.AppearanceParameters

### ISSUE THREAD

**Issue by PeterJirat** [DynamoDS/DynamoRevit#1501]
Using this node in Revit model shows no result, otherwise ThermalParameters or StructuralParameters work fine.

## Dynamo version

1.2.1.3083

## Revit version

Revit 2017.2

## Operating system

Windows 10

## What did you do? 

Looking for material properties

## What did you expect to see?

properties

## What did you see instead?

Type Name :
Category :
Category :
Design Option : -1
Family Name :

![image](https://cloud.githubusercontent.com/assets/25455047/22462892/8d380984-e7af-11e6-9777-351d00a1a39a.png)

**Comment by ksobon** [comment]
What is this supposed to be returning in your opinion?

**Comment by AndyDu1985** [comment]
It is by design.
