### ISSUE TITLE
OUt of the box nodes for Project base point and survey point switched

### ISSUE THREAD

**Issue by Daniel-Gijsbers** [DynamoDS/DynamoRevit#1531]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.2.1.3083
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version
17.2
(Which version of Revit are you using?)

## Operating system
Winodws 10 64
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
I used the out of the box nodes for the project base point and survey point and I think someone switched them around. Look at the attached image

## What did you expect to see?
the other way around

## What did you see instead?
![pbpandsp](https://cloud.githubusercontent.com/assets/11941422/22820869/e83254ea-ef78-11e6-8e76-1f873f89bb2b.jpg)

**Comment by eibre** [comment]
I think this is expected behavior. Unless you have moved the PBP unclipped, it should be at point 0,0,0 measured in the internal coordinate system.

**Comment by Daniel-Gijsbers** [comment]
thanks for looking into it. It's now behaving as expected.
