### ISSUE TITLE
Material Nodes bug

### ISSUE THREAD

**Issue by mfleming04** [DynamoDS/DynamoRevit#1581]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1
as well as 1.2.1.3083

## Revit version

2016

## Operating system

Windows 7

## What did you do? 

I used nodes Element Types--> All Element's of Type and tried to get the Material.Color as well as the rest of the Material nodes.  But it causes an error relating to an array.  See screen captures.

## What did you expect to see?

Material.Nodes to populate.

## What did you see instead?

Translating to Material.Name, then back to Material.ByName then to Material.Color works but the above should work as well.

![material](https://cloud.githubusercontent.com/assets/22360133/23347760/11c7470e-fc6a-11e6-86e1-eee95f399746.png)

Refer to Forum post for additional info.
https://forum.dynamobim.com/t/is-this-a-bug-material-ootb-nodes/9900/3

**Comment by dimven** [comment]
Looks like the element wrapper is missing a definition for Revit Material instances.

**Comment by ksobon** [comment]
@dimven was right. The wrapper was missing for the Material class. Adding it fixes the issue: 

![image](https://user-images.githubusercontent.com/529781/27011836-c94e74ae-4e92-11e7-86dc-7ce50704bc79.png)

**Comment by ksobon** [comment]
@kronz this was fixed and merged here: https://github.com/DynamoDS/DynamoRevit/pull/1888
