### ISSUE TITLE
Keynote Tag Category Issue

### ISSUE THREAD

**Issue by calvertnr** [DynamoDS/DynamoRevit#1588]
## Dynamo version

1.2.1

## Revit version

2017.2

## Operating system

Windows 10

## What did you do? 

Place "Categories" node, change to "Keynote Tags" Category, feed into "All Elements of Category" node, run the script.

## What did you expect to see?

A list of all of the keynote tags in the model

## What did you see instead?

An error warning. When I switched to Dynamo version 0.9.2 this worked perfectly.

![image](https://cloud.githubusercontent.com/assets/26099702/23438724/bb922924-fdd8-11e6-9efb-29e228efb807.png)

**Comment by ksobon** [comment]
This works fine in 1.3: 

![image](https://cloud.githubusercontent.com/assets/529781/26659887/49ccefa6-4642-11e7-8b44-d6a289e78294.png)

cc: @kronz can we close this issue?

**Comment by calvertnr** [comment]
The issue returned in 1.3.1

![keynote tag category error](https://user-images.githubusercontent.com/26099702/30557461-f2afd3ae-9c73-11e7-994f-8fa31df423b2.PNG)

**Comment by wellsy101** [comment]
Same problem Revit 2019.2, dynamo 2.02
![image](https://user-images.githubusercontent.com/48451346/54145116-34185780-4425-11e9-9cd9-165e71b29222.png)
