### ISSUE TITLE
Sheet.ByNameNumberTitleBlockAndView

### ISSUE THREAD

**Issue by Teun1** [DynamoDS/DynamoRevit#1614]
After using this node for the first time in a project, the second time this node is used, it will interact with the already made Sheets (made with this node), instead of making new Sheets. 

I have seen it placing new Views on existing Sheets instead of making new Sheets.
I have also seen it deleting existing Sheets when you want to make less Sheets then the first time.

New Unique Sheet Names / Numbers don't help. 
Reopening Dynamo or even Revit doesn't help. 

I really don't know what is going on and think it is a bug. 

Right now I use a series of nodes that will work more stable, with the same input data.
 - Tool.CreateEmptySheet
 - Tool.PlaceViewsOnSheets

Dynamo1.2 & Revit 16 Update7 for R2

**Comment by Teun1** [comment]
Another problem with this node is that it doesn't except a view higher than the Titleblock.
I can place a view outside of the Titleblock but it seems that the height is a problem.

Right now I change the Height of the Tiltleblock before placing, and after placing Views change it back again.

When the reason is to tell people that the View is to high please use something else and continue the code. I can rotate the view on Sheet afterwards (0,1,2). But I will appreciate the note.

**Comment by ksobon** [comment]
@Teun1 This is expected behavior and exactly as it was designed. It's called element binding. There is a wish outstanding with the development team for disabling binding that you can find here: https://github.com/DynamoDS/DynamoRevit/issues/1673 @kronz can we close this issue? It's pretty much a duplicate request to disable binding.

**Comment by kronz** [comment]
Yep, for now, as designed
