### ISSUE TITLE
Line Style get parameter not returning the name

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/DynamoRevit#1619]
## Dynamo version

1.2.1.3083

## Revit version

2017.2

## Operating system

Windows 10

## What did you do? 

Trying to use the Line Style name to group

## What did you expect to see?

The Line Style name (Wide Lines)

## What did you see instead?

GraphicsStyle with the ID

![image](https://cloud.githubusercontent.com/assets/4299930/23786572/0f6877c8-056e-11e7-9194-a288a4d38e22.png)

**Comment by andydandy74** [comment]
This should work with Clockwork's Element.Name+ node

**Comment by DanielHurtubise** [comment]
Using your node it returns Detail Lines
![image](https://cloud.githubusercontent.com/assets/4299930/23796929/c113c944-059d-11e7-9e17-78b73866cf2c.png)

**Comment by DanielHurtubise** [comment]
My bad i'm dumb as a brick :)
Thanks
![image](https://cloud.githubusercontent.com/assets/4299930/23797015/199711c0-059e-11e7-892b-53ae8b3c55bc.png)

**Comment by ksobon** [comment]
Is this really a DynamoRevit issue? I mean it returns a Line Style object, which itself has a name property. Did you try calling Element.Name on it? That should return the string name of the style. The Line Style parameter itself holds an element not its name.

**Comment by ksobon** [comment]
@cc: @kronz I don't see an issue here. Can we close?

**Comment by kronz** [comment]
Thanks all for the feedback, but like @ksobon says, I don't think there is a bug here.
