### ISSUE TITLE
Revit hangs after disconnecting input port from Dynamo node

### ISSUE THREAD

**Issue by lerklimenko** [DynamoDS/DynamoRevit#1627]
## Dynamo version

1.2.1.3083

## Revit version

17.0.1117.0
20170118_1100(x64)
2017.2 

## Operating system

Windows 10

## What did you do? 

I've opened graph downloaded from the Dynamo [Primer](http://dynamoprimer.com/en/04_The-Building-Blocks-of-Programs/4-3_logic.html) and tried to disconnect input port from any node.

## What did you expect to see?

Port is disconnected, Dynamo and Revit continue working.

## What did you see instead?

Dynamo and Revit become not responding, so I needed to stop process via Task manager.
Issue is reproducible every time. I've also attached to process with Visual Studio and saw that the main thread got stuck in _RevitAPI.dll!Autodesk.Revit.DB.TessellatedShapeBuilderResult.GetGeometricalObjects()_

Please see attached giff
![dynamorevit_bug](https://cloud.githubusercontent.com/assets/22635288/24039123/a39f16ba-0b0c-11e7-9d44-d83f94734d9e.gif)

**Comment by dimven** [comment]
Looks like the Revit background preview is creating more faces than Revit can handle. Have you tried turning off the background preview ?

**Comment by lerklimenko** [comment]
@dimven You are right, with disabled preview it works fine. Thanks!

**Comment by jnealb** [comment]
@lerklimenko @dimven We are aware of this issue and working to resolve it. Thanks for the feedback.
