### ISSUE TITLE
Standard nodes not loading

### ISSUE THREAD

**Issue by ChubbyQuark** [DynamoDS/DynamoRevit#1628]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

1.2.1.3083

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

2017

(Which version of Revit are you using?)

Windows 7

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Open Dynamo From Revit

## What did you expect to see?

Standard nodes

## What did you see instead?

Nothing

Nodes appear when opening in sandbox mode.

Thanks.

**Comment by ksobon** [comment]
Dynamo Sandbox will not load any of the DynamoRevit nodes. You need to launch Dynamo from within Revit to get that package loaded. 

cc: @kronz I believe there is nothing that we can do here. DynamoRevit is closely coupled with Revit, and things like DocumentManager need Revit to be able to work. Can you confirm and close?

**Comment by ChubbyQuark** [comment]
Hi Konrad,
I think this is an issue with my particular install of Revit. I understand that the nodes will only load when Dynamo is launched from within Revit. The issue is noes are loading but not displayed graphically in the tree. In fact this is true of all nodes, not just the added packages.

I've contacted Autodesk regarding this but haven't got an answer. I've even tried a full re-install of Revit and various iterations of Dynamo but the issue persists.

I'll pursue with Autodesk and update if I find a resolution.

Thanks.

**Comment by ksobon** [comment]
@ChubbyQuark ah, I see. So this must be an issue with the installation. You will need to tell the guys here, exactly what version of Revit (include full build number), what version of Dynamo (also include full build number) and perhaps your system setup. Is it on Windows? If yes, what version? What Graphics Card are you running it on? If you can give them all these details, then maybe they can try and re-create that issue. cc: @jnealb 

Ps. Try posting the result from the console. It should say if there were any errors while you were loading up Dynamo. That would help these guys too.
