### ISSUE TITLE
Crash while using "delete all elements of category" Bakery Node 

### ISSUE THREAD

**Issue by EmmettCru** [DynamoDS/DynamoRevit#1630]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1

## Revit version

2015 0715_ur 14

## Operating system

Windows 7

## What did you do? 
Ran delete all elements of category node.

## What did you expect to see?
delete all of the plmb fixtures in my sample file.

## What did you see instead?

It deleted them, then bugged out.

**Comment by ksobon** [comment]
This is a forum question guys. Please move this conversation to the forum. cc: @kronz
