### ISSUE TITLE
Wrong Surface from Solid - Plane Intersection

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/DynamoRevit#1638]
## Dynamo version

1.2.1.3083

## Revit version

2017.2

## Operating system

W7

## What did you do? 

1. Extract Solids form Revit Structural Framing
2. retrieve surface from intersecting solids with plane
3. Retrieve  perimeter curves from surface

## What did you expect to see?

Convex rounded corners like in the Revit Family (the Blue arrows below)

## What did you see instead?

(Fill in here)
![image](https://cloud.githubusercontent.com/assets/14221455/24586373/aa6acbc0-179f-11e7-9f0a-905090c1d9cf.png)

**Comment by smangarole** [comment]
@paoloemilioserra Can you try this with Dynamo 1.3? Please let us know what do you find.
Thanks.

**Comment by mjkkirschner** [comment]
I would guess this has to do with detail level of geometry extraction - I think we default to medium.

**Comment by paoloemilioserra** [comment]
The customer has just confirmed that issue persists on 1.3.0.875 and was resolved in 1.3.1 with a simple model.
The profile in the beams is always the same at all level of details.
