### ISSUE TITLE
[Wishlist] Opening Excel in a background process

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/DynamoRevit#1639]
It would be very useful for teamwork that we have the ability to open Excel in the background when running operation with Read from Excel.
Most users are not closing it after the operation unfortunately.

**Comment by ksobon** [comment]
@kronz this is Dynamo related and not DynamoRevit. can we move over and/or close?

**Comment by smangarole** [comment]
@kronz - How would you like to handle feature requests? Do you think we should create a ticket and put it in the backlog?

**Comment by kronz** [comment]
This should be a DynamoDS/Dynamo improvement.  @smangarole let's not put it into the internal backlog until such time as we are ready to work on it.  
I made a new "improvement" in Dynamo
https://github.com/DynamoDS/Dynamo/issues/7921
