### ISSUE TITLE
Select Model Element - Framing Tag: Crashes Revit

### ISSUE THREAD

**Issue by thazell** [DynamoDS/DynamoRevit#1651]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version

(Which version of Revit are you using?)

## Operating system

Windows 10

## What did you do? 

Selected a Framing tag with the "Select Model Element Node" 

## What did you expect to see?

I was expecting for the Select Model Element to work the same as it always works

## What did you see instead?

Revit Crashed with a recovery file option.

Video Attached
http://autode.sk/2pDiues

**Comment by ksobon** [comment]
@thazell is this still an issue in 1.3? 

![image](https://cloud.githubusercontent.com/assets/529781/26021578/d53e71ba-375e-11e7-8513-120d2cd93907.png)

**Comment by thazell** [comment]
Interesting:  I tried the structural sample project and it works in that project.  However, when I do it with a project based on our template it doesn't work.
![image](https://cloud.githubusercontent.com/assets/14113080/26031100/2ec17bca-3835-11e7-8dcf-05c9c4e18382.png)
![image](https://cloud.githubusercontent.com/assets/14113080/26031137/581f2872-3836-11e7-8585-dd6525fc3ac2.png)
I wonder if it is due to the invisible text in our tags.  We have multiple options in the tag that users can turn off and I'm curious if the tags that have "visible off" are causing issues.  I've seen other cases where "visible off" still exists in the modeled environment it's just invisible.
Just to make sure I was comparing apples to apples, I did copy our families into the sample project and the same thing happened.

**Comment by thazell** [comment]
It does appear to be related to the background draw that @mjkkirschner  mentioned above.

**Comment by smangarole** [comment]
@thazell Can you please clarify what happens when the revit background preview is turned off?

**Comment by thazell** [comment]
@smangarole Everything works if the previews are turned off.

**Comment by smangarole** [comment]
@thazell Thanks for the prompt reply. We are tracking this issue.

**Comment by adityakaushik123** [comment]
I am getting the same error and turning off revit background preview trick is not working. Any help is appreciated
