### ISSUE TITLE
Improvement: Select Face Node outputs to a list instead of a single element

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#1656]
## Dynamo version

1.3.0

## Revit version

2017

## Operating system

Win 10

## What did you do? 

Selected a face using the Select Face node

## What did you expect to see?

A single selected face

## What did you see instead?

A single face in a list. As far as I'm aware, there are no situations where a single face yields more than one object to justify the default output to a list, but I thought I would report it in case it is an oversight. 

![image](https://cloud.githubusercontent.com/assets/18601851/25353992/1365897c-2929-11e7-94f6-95f9bdd7eca3.png)

**Comment by andydandy74** [comment]
This has been discussed here: https://github.com/DynamoDS/Dynamo/issues/3422

**Comment by ThomasMahon** [comment]
Thanks for the heads up. I had an inkling that the reason for this behaviour was for the reasons mentioned. I'll put this one to rest!
