### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by drduarte** [DynamoDS/DynamoRevit#1660]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 1.3.0.875

## Revit version

Revit 2017.1.1

## Operating system

Windows 7

## What did you do? 

Run a script that was working two days ago

## What did you expect to see?

Excel spreadsheet with exported data

## What did you see instead?

Attached warning
![untitled-1](https://cloud.githubusercontent.com/assets/15021345/25412867/ce0e8c40-29da-11e7-920f-e93d7dc1ce60.jpg)

**Comment by drduarte** [comment]
Looks like a list of more than 500,000 items caused the error.  Working around this.

**Comment by ksobon** [comment]
This is not a DynamoRevit issue. @kronz can we close here/re-open on Dynamo side?

**Comment by kronz** [comment]
@drduarte Thanks for the feedback.  Can you file this in the Dynamo repo issues, and include a sample script?
