### ISSUE TITLE
Curve offset direction is inconsistent

### ISSUE THREAD

**Issue by AndrewHeumann** [DynamoDS/DynamoRevit#1661]
The offset direction of curves (lines in particular) is not consistent with the curve's normal. Instead offsets appear to respond to their orientation relative to the world coordinate system - this is confusing and unpredictable.

This is related to this request [6585](https://github.com/DynamoDS/Dynamo/issues/6585) - 
but I would propose that rather than (or in addition to) a manually specified offset side, the default behavior of the function should be consistent relative to the curve direction.

**Comment by ksobon** [comment]
This is not DynamoRevit related issue. @kronz can we please close this / re-open on Dynamo side?

**Comment by aparajit-pratap** [comment]
Thanks guys, this is already being tracked.

**Comment by jnealb** [comment]
@aparajit-pratap What is the JIRA task?

**Comment by aparajit-pratap** [comment]
@jnealb https://jira.autodesk.com/browse/DYN-826

**Comment by jnealb** [comment]
@aparajit-pratap Thanks!

**Comment by kronz** [comment]
Moved to Dynamo repo issues:
https://github.com/DynamoDS/Dynamo/issues/7876
