### ISSUE TITLE
Document.ActiveView does not support sheets

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#1662]
## Dynamo version
1.3.0.875

## Revit version
2017.1

## Operating system
Win 10

## What did you do? 
Ran a graph with ```Document.ActiveView``` on a model that had a sheet as an active view

## What did you expect to see?
Dynamo returning the active view

## What did you see instead?
```Warning:Document.get_ActiveView failed. Unable to cast object of type 'Revit.Elements.Views.Sheet' to type 'Revit.Elements.Views.View'.```
Related to #1622.

**Comment by ksobon** [comment]
@andydandy74 this will be fixed with the #1672 PR. The `Sheet` class was inheriting from `Element` instead of `View`. It screwed up the casting a little bit. 

@jnealb let me know if this works. Cheers!

**Comment by ThomasMahon** [comment]
I've also encountered the same problem here:
https://github.com/DynamoDS/DynamoRevit/issues/1644
@ksobon I thought that was the case, thanks for confirming

**Comment by smangarole** [comment]
@mjkkirschner Can you please update the status of this PR? I see you have commented on the PR.

**Comment by andydandy74** [comment]
Working as expected in 2.0
