### ISSUE TITLE
Room.Area reports internal units, not display units

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#1668]
## Dynamo version

1.3 stable

## Revit version

2017.2

## Operating system

Win 10

## What did you do? 

Retrieve room areas using Room.Area

## What did you expect to see?

The room areas in display units (square meters)

## What did you see instead?

The room areas in internal units (square feet)
![roomareas](https://cloud.githubusercontent.com/assets/3014437/25680849/816b3158-3052-11e7-9b70-4078155fa422.PNG)

**Comment by eibre** [comment]
This is actually already fixed here: https://github.com/DynamoDS/DynamoRevit/commit/adf769d1f8fc648f845070f6f06eae6acd71dfd6

I wonder why they don't include such fixes in new releases?

**Comment by aparajit-pratap** [comment]
@andydandy74 @eibre The fix didn't make it in time for the 1.3 release cutoff. Since it's already fixed and will be available in the upcoming builds, I'm closing this for now.

**Comment by jnealb** [comment]
@aparajit-pratap @kronz @Racel Is there a JIRA task for this?

**Comment by kronz** [comment]
@jnealb does it need a JIRA task?  Already fixed an in builds?

**Comment by jnealb** [comment]
@kronz Always

**Comment by jnealb** [comment]
This is tracked with DYN-844

**Comment by aparajit-pratap** [comment]
@jnealb this is already fixed in master builds and unfortunately we can't do anything to fix it in 1.3 at this stage.

**Comment by jnealb** [comment]
@aparajit-pratap Thanks, understood.

**Comment by aparajit-pratap** [comment]
@jnealb @riteshchandawar now that we have one more window for release 1.3.1, can we cross-merge these fixes into RC1.3.1 branch?

**Comment by riteshchandawar** [comment]
@aparajit-pratap Only changes related to Player should go in nothing else because we are not going to publish this installer on DynamoBuilds site, so to remain in sync with 1.3.0 we should not have any functionality changes. Does that make sense?
