### ISSUE TITLE
Fillet/Chamfer not working

### ISSUE THREAD

**Issue by BetzaPerez** [DynamoDS/DynamoRevit#1670]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(v 3.0)

## Revit version 

(2017)

## Operating system Windows 7

( Windows 7)

## What did you do? 

Try to apply Fillet and Chamfer to the edges of a Solid By Loft using Topology Edges. 

## What did you expect to see?

(the solid with fillet/chamfer on the edges, and a list in the  Topology Edges)

## What did you see instead?

(There was not change on the edges neither list in the  Topology Edges)

![image](https://cloud.githubusercontent.com/assets/28555745/25837622/10af7396-34d2-11e7-9073-1e10e75d5b38.png)

**Comment by ksobon** [comment]
This is not DynamoRevit related issue. @kronz can we please close this / re-open on Dynamo side?

**Comment by kronz** [comment]
@BetzaPerez  thanks for the report, can you report this on the Dynamo issues, as well as an example file?  This issue doesn't reproduce for me in the simple case, so I'm wondering if it is particular to something specific in the script
