### ISSUE TITLE
Category.ByName creates incomparable objects

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#1680]
## Dynamo version

1.3 stable

## Revit version

2017.1

## Operating system

Win 7

## What did you do? 

Compare one list of categories with another list of categories using ```List.ContainsItem```

## What did you expect to see?

```List.ContainsItem``` returning ```True``` for matches

## What did you see instead?

```List.ContainsItem``` is not able to match categories created by the ```Category.ByName``` node
![listcontainscategories](https://cloud.githubusercontent.com/assets/3014437/26238361/ff2df242-3c78-11e7-98e5-a43dacb1b766.png)
Comparing categories using the ```Equals``` node fails in the same fashion.
I know that I can use category IDs for comparison as a workaround but this should work the same way it does with other Revit elements.

**Comment by ksobon** [comment]
That's not the behavior that I am seeing: 

![image](https://cloud.githubusercontent.com/assets/529781/26280194/bce21e8e-3d97-11e7-84bc-c23e8a26f20a.png)

Also, this should not have been happening because it was already reported before and fixed: 

https://github.com/DynamoDS/DynamoRevit/issues/1451

@mjkkirschner could there be another reason for this?

**Comment by andydandy74** [comment]
German locale perhaps?

**Comment by ksobon** [comment]
@andydandy74 german local should not play a role. Categories are compared by their `Id` - integer value.

**Comment by andydandy74** [comment]
@ksobon any other obvious differences between your setup and mine?

**Comment by eibre** [comment]
@andydandy74 @ksobon 
Looks like the fix is in the latest release yet:
![image](https://cloud.githubusercontent.com/assets/5968613/26426880/c628ec0c-40da-11e7-8475-b4f4c3c90019.png)

**Comment by ksobon** [comment]
That's the difference for sure. I am usually on the latest source build. @eibre thanks for reporting.

**Comment by smangarole** [comment]
@kronz and @mjkkirschner Ping.
Why is there a delta between the master and 1.3 release? Is the 1.3 release as designed?

**Comment by kronz** [comment]
The delta is the strangest part here.  Fix looks like it was merged back in January, so not sure why it isn't in 1.3 https://github.com/DynamoDS/DynamoRevit/pull/1455
@sharadkjaiswal any ideas?  I'm guessing it went into 2.0 stream and not 1.3?

**Comment by andydandy74** [comment]
Working as expected in 2.0
