### ISSUE TITLE
Google Sheets not reporting correctly

### ISSUE THREAD

**Issue by SparkYunker** [DynamoDS/DynamoRevit#1684]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.0.875

## Revit version

2018

## Operating system

Windows 10 Pro Version 1703 Build 15063.296

## What did you do? 

Use raindrops and google sheets to get list and multiply numbers together, add same numbers

## What did you expect to see?

Product, Sum

## What did you see instead?

Null at multiplication. Adding 36+48, got 3648.
![productnull](https://cloud.githubusercontent.com/assets/28810294/26255410/1fcf4dce-3c7f-11e7-8a54-8daa99aebb72.png)

**Comment by mjkkirschner** [comment]
The data is being pulled a string, you need to convert it to a number.

**Comment by SparkYunker** [comment]
Thank you sir. That worked. Added String.ToNumber between List.GetItemAtIndex and Multiply.
