### ISSUE TITLE
Revit Elements' Background Preview kills my Video Driver and Terminates Revit

### ISSUE THREAD

**Issue by dimven** [DynamoDS/DynamoRevit#1697]
*****Also see https://github.com/DynamoDS/Dynamo/issues/7703 for more discussion on this topic *******

## Dynamo version

1.21 / 1.3

## Revit version

Revit 2016 / 2017 / 2018

## Operating system
System1:
Windows 7
nVidia Quadro K3100M
Driver Version: 348.07

System2:
Windows 10
AMD Radeon 7850
Driver Version: Radeon Software Version 17.1.1

## What did you do? 

Selected all elements in the active view (floor plan)

## What did you expect to see?

A list of elements

## What did you see instead?

I saw a series of screen flashes, followed by the following errors and Revit quitting without saving:

![revit_2017-05-30_13-55-48](https://cloud.githubusercontent.com/assets/7148394/26570651/43cc3926-4544-11e7-86d0-76efe4fcc53c.png)

![revit_2017-05-30_13-55-34](https://cloud.githubusercontent.com/assets/7148394/26570654/47494d5a-4544-11e7-8794-95cf33b89b94.png)

This is most likely happening because of the new detail curve and Revit Text elements' background preview.

Element objects should NOT have a background preview unless I specifically choose to extract their geometry... It would be great if we had the option to disable this "feature" :) .

The only way to bypass this error is to open the graph in manual mode and disable the preview of the node fetching the elements.

**Comment by ksobon** [comment]
Yeah this new TextNote and DetailCurve background previous are crashing people's machines left and right.
@mjkkirschner @jnealb

**Comment by jnealb** [comment]
@dimven Just to be clear: can you please confirm this happens with 1.3 as well?

**Comment by dimven** [comment]
I'll try and test this on 1.3 this weekend. I'm pretty sure it's some kind of a weird driver/hardware combination tho because I've only had this happening on my work machine. I originally suspected the issue will also happen in 1.3 because I don't remember seeing any chances to the background preview between 1.21 and 1.3

**Comment by jnealb** [comment]
Yes, but there may be issues with our upgrade process. Please let us know.

**Comment by dimven** [comment]
@jnealb Sorry my reply took so long. Getting IT to cooperate can be a challenge. I couldn't test the office PC in 1.3 but I did test my home PC. The results are even more catastrophic with an AMD system - the screen flashes a few times then turns grey and the video driver fails to launch again. The only solution seems to be a hard reset of the system.

There's definitely a critical number of elements before this occurs, tho the crash can happen with just a few nodes as seen below:

![revit_2017-06-20_23-03-15](https://user-images.githubusercontent.com/7148394/27340615-84197af0-560d-11e7-9618-90342d0a8eea.png)

You can get a copy of the above graph from [here](https://github.com/dimven/SpringNodes/blob/master/Issues/1697%20video%20driver.dyn)

**Comment by rbosborne** [comment]
A system wide disable preview would be nice.  Or an option to set default preview behavior for all nodes to "Off" (making the user explicitly choose when they do want to see a preview).

Also- allow disable/enable preview for grouped nodes (select the group and disable all within the group) - and disable/enable preview for multiple selections (window select an area of your graph and disable/enable preview for all selected nodes).

**Comment by Racel** [comment]
@jnealb @mjkkirschner - Closed https://github.com/DynamoDS/Dynamo/issues/7703 to consolidate the discussion under one topic. 

We should consider @mjkkirschner's proposal as a potential fix:
Turn off preview rendering of TextNotes and DetailCurve, - instead add element.geometry or textNote.Curves as a function to create these curves when desired.

@kronz I suggest we try to get a fix in for 2.0 as it is causing a crash. Filed a task for this: https://jira.autodesk.com/browse/DYN-906 and added to Dynamo 2.0 epic
