### ISSUE TITLE
Area Types need to be included in ScheduleView.CreateSchedule 

### ISSUE THREAD

**Issue by frothey** [DynamoDS/DynamoRevit#1704]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
 
1.3.0.875
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version
2018

## Operating system
Windows 10

## What did you do? 

I am getting an error message when I try and create a Regular Schedule using the Areas Category. 

## What did you expect to see?

Area Types should be included in the ScheduleView.CreateSchedule for this node to function with Areas. When creating an Area Schedule in Revit you need to define type of area to schedule the building components.

It seems Areas Schedules cannot be generated using the ScheduleView.CreateSchedule node.

## What did you see instead?

ScheduleView.CreateSchedule operation failed. 
The Areas category was specified but an area scheme ID was not provided.
Parameter name: categoryId 

<img width="650" alt="image" src="https://cloud.githubusercontent.com/assets/16231672/26748678/b6bcadc2-47b4-11e7-9d35-7dd1fbd2badc.png">

**Comment by jnealb** [comment]
@ksobon Ping. FYI: @smangarole, @mjkkirschner

**Comment by ksobon** [comment]
Yeah, I am aware. I directed the user here from Dynamo Forum. Will try and have a look if/when time permits. I am not sure what the right strategy for this is. Maybe a new `Schedule Type` called Area and then we would allow user to provide an `AreaType` input instead of `Category`. Would that work?

**Comment by ksobon** [comment]
![image](https://cloud.githubusercontent.com/assets/529781/26813867/3e6fd4a0-4a4f-11e7-99f7-375010bf123c.png)

This should do the trick!

**Comment by TeunG** [comment]
Hey,

Interesting subject,

@ksobon I'm curious: Where can I find the CreateAreaSchedule node?

Thank you in advance.

**Comment by ksobon** [comment]
@TeunG it was submitted to Autodesk for approval. @kronz any idea when these PRs will be reviewed?

**Comment by MReza294** [comment]
Hi @ksobon, I'm totally new here and currently need to create more than 100 unique area schedules for marketing plans.. Is there an ETA when CreateAreaSchedule node will be available? any chance I can use it anytime soon? 
Thanks in Advance
Reza

**Comment by ksobon** [comment]
@kronz can we close this as well as it was just merged? Thanks!

**Comment by kronz** [comment]
FYI @AndyDu1985
