### ISSUE TITLE
Session Log Missing Information

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/DynamoRevit#1715]
## Dynamo version

1.3.0.875

## Revit version

2017.2

## Operating system

W7

## What did you do? 

I monitored the Log file in a Dynamo session, loading DYN files from the hard drive both in automatic and manual mode. 

## What did you expect to see?

 "Original file " with the name of the graph for each file. A way to calculate the exact duration of the execution (not just the file opened in the Dynamo Application).

## What did you see instead?

The same file called "corridor.dyn" has been opened in multiple occasions but the log trace was different from the one called "readCSV.dyn"

![image](https://user-images.githubusercontent.com/14221455/27251858-8795eda4-5350-11e7-88a7-fe2d267fdcf1.png)

**Comment by ksobon** [comment]
@kronz this is not DynamoRevit specific. It should be posted on Dynamo page. Can we move/close this?

**Comment by kronz** [comment]
https://github.com/DynamoDS/Dynamo/issues/7985
