### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by ggnistor** [DynamoDS/DynamoRevit#1722]
## Dynamo version
1.3

## Revit version
2017

## Operating system
Windows10

## What did you do? 
First time with dynamo. I downloaded the installation file and run it. I have access to the sandbox as stand alone but Dynamo does not show on Revit Add-In tab

## What did you expect to see?

Dynamo as one more add-inn in Revit

**Comment by mjkkirschner** [comment]
Dynamo should be in the manage tab not addins.

**Comment by ggnistor** [comment]
Thanks!
