### ISSUE TITLE
Sequence with letters

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/DynamoRevit#1725]
1.3.0.875

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version

2017.2

## Operating system

Windows 10 x64

## What did you do? 

Created a sequence using A as a startup point

## What did you expect to see?

When exceeding Z i was expecting to see AA

## What did you see instead?

lowercase a

And if you go above lowwer case z... the sequence end. Seems better to me to just double up the letters and keep going

Cheers guys and keep up the awesome work

**Comment by andydandy74** [comment]
see https://github.com/DynamoDS/Dynamo/issues/5277

**Comment by ksobon** [comment]
@kronz can we close this here? It's duplicate and was not supposed to be posted here since its a Dynamo issue. Cheers!
