### ISSUE TITLE
Problems with mandrill package 

### ISSUE THREAD

**Issue by Phlipflops** [DynamoDS/DynamoRevit#1728]
## Dynamo version

Dynamo 1.3

## Revit version

Revit 2017.2

## Operating system

Windows 10

## What did you do? 

I tried to visualize some data with the Mandrill package. Ist working til i want to print pdf or html. The Moment i click the "Launch/Print" - Button Dynamo shuts down, shows some error message which is just saying that there is a mistake during the process and Dynamo has to shut down. Any ideas?  Thanks

**Comment by ksobon** [comment]
@Phlipflops can you post Mandrill related issues here: https://github.com/BadMonkeysTeam/Mandrill/issues Also, please attach a sample file, image of your definition or at least what the error says. That's the only way for me to be able to start helping you. Cheers! 

cc: @kronz can you close this? It doesn't belong in this repo.
