### ISSUE TITLE
problem with SetParameterByName 

### ISSUE THREAD

**Issue by LopezDan** [DynamoDS/DynamoRevit#1736]
![image](https://user-images.githubusercontent.com/29954756/27921449-230d37de-6278-11e7-897b-ae46c44dad07.png)

Hello i'm trying to put calculated data into the field in the abacus but i have a problem i'm new in Dynamo thanks for your help
Daniel lopez

**Comment by LopezDan** [comment]
![image](https://user-images.githubusercontent.com/29954756/27921600-89f87b3e-6278-11e7-927b-1d4739304a77.png)

**Comment by ksobon** [comment]
Please post "how to" questions to this forum: https://forum.dynamobim.com/ 

@kronz can we close this issue?

**Comment by LopezDan** [comment]
ok

**Comment by LopezDan** [comment]
scusi me but i have been trying for a long but there no way to post anything there

**Comment by ksobon** [comment]
you need to create an account. You won't be able to post an image at first since you are a new user, but you can post a link to Box or Google Drive. That limitation will be removed with time. It's there to prevent spam.

**Comment by LopezDan** [comment]
ok thanks
