### ISSUE TITLE
ToRevitType() doesn't convert Dynamo Solids derived from Revit Elements to Revit API Solids

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#1760]
## Dynamo version

1.3.1

## Revit version

Revit 2017

## Operating system

Win 10

## What did you do? 

Converted a solid extracted from Revit elements (Rooms) using OOTB `Elements.Element.Solids` to a Revit API type using `ToRevitType()`

## What did you expect to see?

A Solid from the Revit API `Solid` class

## What did you see instead?

It gets converted to a mesh which causes problems for any API methods which require a Solid as an input. I am attempting to use Solid Element intersection but as the solid is a mesh, the method call fails. 

Maybe this is a limitation since any solid is deemed to be 'foreign' and meshing is therefore the only option? If not, its critical this method is updated to output Revit types more consistently:

![image](https://user-images.githubusercontent.com/18601851/29249411-29aa62a2-8027-11e7-80cf-ae21339caeb3.png)

![image](https://user-images.githubusercontent.com/18601851/29249407-0ff1312e-8027-11e7-9b46-03b84fefd065.png)

![image](https://user-images.githubusercontent.com/18601851/29249269-3b96f8ca-8024-11e7-997f-bbb909ab012a.png)

The result when `ClosedShell` property is used on the Room element. This is what I would expect `ToRevitType()` to output:
![image](https://user-images.githubusercontent.com/18601851/29249292-a3950c5a-8024-11e7-8d5e-81d8c3fde0bc.png)

**Comment by ThomasMahon** [comment]
I see this topic is also reported here: [#4061](https://github.com/DynamoDS/Dynamo/issues/4061) and here [#4496](https://github.com/DynamoDS/Dynamo/issues/4496). Are there any updates?

**Comment by dimven** [comment]
We had a discussion about this back in 2015:

https://forum.dynamobim.com/t/directshape-question/2427

At that time the API simply did not provide us with enough tools to make the conversion feasible. But now with the introduction of the BrepBuilder in Revit 2017, this seems a lot more realistic. We can now re-create the dynamo solid face by face with the different methods introduced in Revit 2017.

The biggest challenge however, lies in the fact that the BrepBuilder still has a lot of restrictions that do not apply to Dynamo based geometry entities. For example, all faces in the solid/shell have to have uniform normals, you can not have more than two references for each co-edge, you can not have any periodic faces, and so on. So if there ever is a method that recreates dynamo solids into revit solids, it will have to involve workarounds for each of those limitations.

Work on this was actually already started here:

https://github.com/DynamoDS/DynamoRevit/blob/7270187e8688fbd8ec538b4617810dccdb9a695f/src/Libraries/RevitNodes/GeometryConversion/DynamoToRevitBRep.cs

but there's been little progress made since then.

**Comment by ThomasMahon** [comment]
It does make sense. I wonder though if the `EntityTags` class in Autodesk.DesignScript.Geometry.Core could be used to mark geometry derived from Revit elements. There would be two advantages (the second being the most advantageous):

1. These solids would conform to all of the BrepBuilder requirements and be easy to reconstruct

2. If the geometry is tagged with say, a property which stores a reference to a Revit Element ID, the behaviour of `ToRevitType()` could be adapted to access the Revit element first (if the tag property contains a value) and then call the Revit API get_Geometry() method which would yield Revit API solids, rather than outputting a useless mesh. 

@aparajit-pratap @mjkkirschner it would be good to get your thoughts on this - it would have huge benefits.

**Comment by sixtysecondrevit** [comment]
Damn, just ran into this problem when I wanted to implement Autodesk.Revit.DB ElementIntersectsSolidFilter

**Comment by ThomasMahon** [comment]
Ha, no way!! ...that was where I also ran into the problem! I've found a workaround it and I will exposing that exact method in bimorph nodes next update. And It avoids the complication of DirectShape cc @dimven. There are methods in the API (from 2017 and 2016 to a certain extent) that are extremely powerful for geometry conversion. Still doing tests, but anything coming out of Revit.Elements.Element.Solid is converting to a solid so far

**Comment by dimven** [comment]
I'm not following :)

Everything that comes out of "Revit.Elements.Element.Solid" was the solid representation of a revit element to begin with. Why would you bother sending that to Dynamo and then converting it back to a revit solid?

**Comment by ThomasMahon** [comment]
@dimven one wouldn't! But its not that simple - the problem arises as per the OP regarding a custom node; any solid from Dynamo, whether derived from a family or built from Dynamo's Geometry library, is convert to a Revit API `Mesh` when `ToRevitType()` is called on the object. This means any method in the Revit API which requires a Revit API `Solid` as an input cant be used in situations where the input solid is derived from `ProtoGeometry (because `ToRevitType()` converts it to a mesh). 

In respect to your question then, there are situations where the user will be inputting geometry from Revit.Elements.Element.Solid, like for example if I create a custom node called `Element.SolidIntersection` (which I have created, OP made reference to it!) which takes a solid and Revit element as inputs. The solid input will be a Proto-Solid. Say the user wants to check for intersections been a room and some element (where the Space parameter or 'point in space' approach fail or are not appropriate), they would need to extract the solid from the room using Revit.Elements.Element.Solid and therein lies the problem: the resulting Revit object after calling `ToRevitType()` will be a Revit API `Mesh` which causes the Element.ElementIntersectsSolidFilter method to fail, causing a hindrance to any situation where this problem arises. 

I've found a method which reliably converts all ProtoGeometry solids to Revit API Solids, and using solids derived from Revit.Elements.Element.Solid is perfect for testing as the geometry is easy to get, can vary in complity and clean. Hence, `Element.SolidIntersection` can now reliably be used with Proto Solids.

Some other comments: why doesn't the node doesn't simply take two elements as inputs, and extract the solids directly in the API context? Firstly its more versatile to input Proto Solids as the user can create their solid however they like (they could create Proto Cylinders for each door in their project to represent door-swings for example, and use this node to check for clashes with other elements). Secondly, I've already created a Element.IntersectsElement node (due to be released with BmiorphNodes v2.1), but the method I'm using to perform the intersection test doesn't support every Revit element type, such as rooms, which is why the workflow described in my first example is very real, and why both methods (nodes) are needed.

![image](https://user-images.githubusercontent.com/18601851/30511917-3aae0206-9b0d-11e7-96bb-ea2f92aaa184.png)

**Comment by sixtysecondrevit** [comment]
@dimven, in my case as building a custom "bounding box" on a curtain panel by offsetting the boundary each direction. From there I am converting to a solid in Dynamo. In my intersection node, I will be feeding in the Dynamo solid, then running this method on a collector of a certain category. http://www.revitapidocs.com/2018/19276b94-fa39-64bb-bfb8-c16967c83485.htm

Using "ToRevitType" is resulting in a mesh and doesn't allow me to use that method. :(

**Comment by sixtysecondrevit** [comment]
@ThomasMahon, I did see the solid builder in the examples here. http://www.revitapidocs.com/2018/7a3b5ac1-c66d-9f81-a11d-9bcd4e026295.htm Have you successfully implemented this in your code?

**Comment by ThomasMahon** [comment]
I'm using a different approach altogether since my start geometry is a mesh (as opposed to the Revit Element). I basically reconstruct the entire mesh, 'glue' it all together then build it as a solid. It only supports flat faces - as far as I'm aware the approach I'm taking isn't documented anywhere online and came about through my own endeavours, but doing a google search now I've found this which is along the lines of what I've done. I'll possibly write up what I've done in a blog post and put it on the Dynamo forum for wider consumption in due course.

**Comment by ThomasMahon** [comment]
This is solved.

**Comment by sixtysecondrevit** [comment]
Solved how? You revised the "ToRevitType" class?

**Comment by ThomasMahon** [comment]
No, there was no need to.

**Comment by sixtysecondrevit** [comment]
Lol, so using "ToRevitType" on a solid and getting a mesh is expected.

**Comment by mjkkirschner** [comment]
if I recall correctly, the tessellated shape builder is able to essentially do the same thing as the process you've described - you can pass tessellated faces to the builder but describe the output as a solid and get a tessellated solid from the mesh geometry. I even think this is what we do using the DirectShape nodes when Brep conversion fails.

**Comment by sixtysecondrevit** [comment]
Yeah, that's what Thomas discussed as well. I need to look at it some more. For my purposes I am just creating a direct shape with the dynamo solid for now.

**Comment by dronov-dmitry** [comment]
dynamo 2.13 (R23) dosnt work unfortunally
![изображение](https://user-images.githubusercontent.com/9892891/230795103-a4e0bcf8-a184-4792-866c-b0b60e69ce7c.png)
