### ISSUE TITLE
RoomTag.CenterOnRoomLocation indicates the output is Room, but it is actualy RoomTag.

### ISSUE THREAD

**Issue by spageRDG** [DynamoDS/DynamoRevit#1770]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.1

## Revit version
2018
## Operating system

Windows 10x64

## What did you do? 

I tried to use the Roomtag.CenterOnRoomLocation node and the node worked, however the output indicated in "room" but it actually gives your room tags.

## What did you expect to see?

Rooms as the output

## What did you see instead?

RoomTag as the output.
![capture](https://user-images.githubusercontent.com/31448525/29832558-3a55d012-8cae-11e7-845c-8ea86ad0eb3f.png)

**Comment by sixtysecondrevit** [comment]
Hello, this is my custom node in Rhythm. I have revised the output name and will push an update soon. 
![image](https://user-images.githubusercontent.com/15744724/30599842-fce94c7c-9d1a-11e7-9f0b-3d5dd2a1027e.png)

@kronz can we close this?

**Comment by kronz** [comment]
Awesome, thanks @sixtysecondrevit
