### ISSUE TITLE
Element.Geometry not working with Mass Voids

### ISSUE THREAD

**Issue by teocomi** [DynamoDS/DynamoRevit#1786]
## Operating system Win 7

Getting geometry or faces of a Mass element that has voids throughout doesn't work properly. Only some faces have the hole of the void.

![image](https://user-images.githubusercontent.com/2679513/30319628-4ad97ba0-97a8-11e7-9bd6-26fa0a9c443f.png)

![image](https://user-images.githubusercontent.com/2679513/30319673-5e5f9768-97a8-11e7-91a6-f0fa81b8e0d7.png)

**Comment by jnealb** [comment]
@aparajit-pratap Ping.

**Comment by aparajit-pratap** [comment]
@jnealb looks like a bug, can you log? Thanks!

**Comment by jnealb** [comment]
@aparajit-pratap This is filed with QNTM-1959.
