### ISSUE TITLE
[Feature Request] Notes output for Player

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/DynamoRevit#1808]
Could we have the ability to add in a static notes output to Player? You can fudge this by putting in a faux string, or a faux watch node, but it's still not quite ideal.

This would allow for users to input micro-help files into their players scripts that would help out hugely with legibility.

![dyn_improvement](https://user-images.githubusercontent.com/12857357/30991754-44ce393c-a49e-11e7-9d3d-281e535251c0.jpg)

**Comment by phliberato** [comment]
@mjkkirschner Do you know where is dynamo player source code? I intend to implement something similar on Advance Steel.

**Comment by ksobon** [comment]
@phliberato Dynamo Player is not an open source project. Also, as far as I know the team working on it is different team that the one working on Dynamo itself. 

cc: @kronz is that right? Is it advised to post comments and issues regarding Dynamo Player here? Would it be better to put these elsewhere?

**Comment by kronz** [comment]
@ksobon you are correct!  Player is implemented by another group at Autodesk, which is understandably a distinction without a difference for a lot of people.  I'll definitely pass along the request, and also tag @BogdanZavu if there are prefered places to record this desire.  Generally for Revit features, that place is here:  https://forums.autodesk.com/t5/revit-ideas/idb-p/302/tab/most-recent
