### ISSUE TITLE
Dynamo Dictionary going to blank page from Dynamo

### ISSUE THREAD

**Issue by chamfered** [DynamoDS/DynamoRevit#1813]
## Dynamo version

(1.3.1.1736)

## Revit version

(Revit 2017, Build 17.0.501.0)

## Operating system

(Windows 7)

## What did you do? 

(Clicked on Dynamo Dictionary in the help menu)

## What did you expect to see?

(Dynamo Dictionary)

## What did you see instead?

(Blank Page)

**Comment by QilongTang** [comment]
Should be a temp state while we are maintaining Dynamo Dictionary Page http://dictionary.dynamobim.com/#/. Thanks for reporting. Closing
