### ISSUE TITLE
(DividedSurface.ByFaceAndUVDivisions) Node Not working on a Second Run

### ISSUE THREAD

**Issue by Cescobido** [DynamoDS/DynamoRevit#1837]
Hi I am having issues with this node above(DividedSurface.ByFaceAndUVDivisions) when selecting multiple faces. 

I have multiple massing stacked on top of each other:
![image](https://user-images.githubusercontent.com/31930252/32236708-55eb7c48-be39-11e7-8478-cd4a11f6e57c.png)

I would select three or four faces at a time to create my divided surface, _(works fine)_.
![image](https://user-images.githubusercontent.com/31930252/32236655-2e83fc0c-be39-11e7-8235-ae206c66dbbc.png)
**Image 1**

When I start the script again and select another set of faces for division is when the node fails. What I have found is when running it a second time on the same model it does not create a unique element ID. It takes the previous set of element IDs and does not create the divided surface with the selected model surface.
![image](https://user-images.githubusercontent.com/31930252/32236432-7cc3422a-be38-11e7-8cb0-2c6fa707572a.png)
**Image 2**

As you can see on Image 1 and Image 2, they are two set of three different model surfaces, but has the same element ID from the node(DividedSurface.ByFaceAndUVDivisions). I have expected to create a new divided surface with a unique IDs. But in this case the new set of surfaces are not divided and the node fails to create a new element

 I would like to have the option to back to the model and divide the surface when needed. Would there be a fix for this.?

I did have a work around which involves delete all divided surfaces and running the graph again. Which is counterproductive when adaptive panels has already been placed onto the divided surface.

Using:
Revit 2017.2
Dynamo Core: 1.3.1.1736

**Comment by jnealb** [comment]
@Cescobido Can you please try this again with Dynamo for Revit 2.0, as released on Dynamobuilds.com? We think it may have been fixed. @alfarok fyi.

**Comment by Cescobido** [comment]
Hi, Neal thanks for responding. I apologies for not getting back to you sooner. I did manage to download the latest build Dynamo for Revit 2.0. The node is working for this build.

Thanks again
Chris
