### ISSUE TITLE
Using statement with ProtoGeometry - proper implementation query

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#1889]
## Dynamo version

1.3.2

## Revit version

2016-18.2

## Operating system

Win 10

## Question? 

Created a BoundingBox from ProtoGeometry library from a Revit API Outline. 

My question is simple: I know that ProtoGeometry elements have to be disposed if not returned, to prevent Revit from going into an inconsistent state. So is the following bad code, since the points are not assigned to variables, but still created on memory, and therefore cant be disposed in anyway:

`return DynamoBoundingBox.ByCorners( Outline.MinimumPoint.ToPoint(),  Outline.MaximumPoint.ToPoint());`

Instead, should the following be implemented?
```
                using (Autodesk.DesignScript.Geometry.Point minPt = Outline.MinimumPoint.ToPoint())
                {
                    using (Autodesk.DesignScript.Geometry.Point maxPt = Outline.MaximumPoint.ToPoint())
                    {
                        return DynamoBoundingBox.ByCorners(minPt, maxPt);
                    }
                }
```

**Comment by mjkkirschner** [comment]
I believe you are *safer* with points than other geometry - to be completely safe - I would call dispose on anything that implements dispose.

I would not use nested using statements - they get unwieldy for me personally.

I keep a list of IDisposables and just dispose them all before the method returns or in a finally block so that dispose happens even if some other exception jumps out of the method.

**Comment by ThomasMahon** [comment]
I see, so you call Dispose() instead of using statement. And you wrap your function in a try catch finally statement. 

Thanks, that's useful advice.

**Comment by ColinDayOrg** [comment]
Quick couple of comments;
1) If you are just dealing with one geometry item that needs to be disposed then the using block is (somewhat) safer, as the dispose happens automatically, but when dealing with multiple items that need to be disposed I find the nested using to be confusing as well
2) I believe that points need to be disposed of, even though they are very primitive forms of geometry. They do not create a lot of geometry, but some is more than none, and the some will be leaked without the disposal.
