### ISSUE TITLE
IndexGroup.ByIndices

### ISSUE THREAD

**Issue by rannils** [DynamoDS/DynamoRevit#1897]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2.2480

## Revit version

2018.2

## Operating system

Windows 7

## What did you do? 

Use IndexGrop.ByIndices(a,b,c) which should store three indices

## What did you expect to see?

Three indices A B C

## What did you see instead?

Four indices A B C D, where D was the same random number for all of the groups

**Comment by aparajit-pratap** [comment]
@jnealb could you verify this?

**Comment by jnealb** [comment]
@rannils Thanks for reporting this. @aparajit-pratap this is tracked as QNTM-3094.
