### ISSUE TITLE
LinePatternElement missing instances and throws an exception

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#1915]
## Dynamo version

1.3.2

## Revit version

2018.2

## Operating system

Win 10

## What did you do? 

Attempted to retrieve a LinePatternElement by name using an Revit built-in pattern (Solid), and I get this exception:

![image](https://user-images.githubusercontent.com/18601851/34796307-05edf63e-f64d-11e7-9988-66bdfb221b9d.png)

Also, the selection method doesn't list the Solid pattern nor a number of others:

![image](https://user-images.githubusercontent.com/18601851/34796475-84cf9714-f64d-11e7-9a56-4abaa85e67a7.png)

**Comment by ThomasMahon** [comment]
On further investigation this looks like a problem with the Revit API, not Dynamo:

![image](https://user-images.githubusercontent.com/18601851/34797364-13ad5c76-f650-11e7-873b-ad276d6e6c4a.png)

**Comment by ThomasMahon** [comment]
Answered my question - the LinePatternElement class only returns line patterns with dashes and dots, not built-in solid lines, which isn't classed as a LinePatternElement:

![image](https://user-images.githubusercontent.com/18601851/34797700-2c12bd50-f651-11e7-92f8-6e6fbaf824c8.png)

**Comment by ksobon** [comment]
@kronz can we close this? There is no action here.

**Comment by kronz** [comment]
Closing, nothing to fix here
