### ISSUE TITLE
03_sunlighthoursAnalisis.dyn

### ISSUE THREAD

**Issue by xvmichal** [DynamoDS/DynamoRevit#1929]
Dynamo 1.3.2.2480

Revit 2018 student version

Windows 10 Pro 

I used sample file '03_sunlighthoursAnalisis.dyn'

Run completed with warnings:

'minute must be in 0.59'

**Comment by jnealb** [comment]
@xvmichal Can you please attach that dyn file here? Thanks.

**Comment by xvmichal** [comment]
Thanks for your support, but i haven't this file anymore.
I'm sorry for the trouble
