### ISSUE TITLE
Filter elements by workset name" node crashed Dynamo

### ISSUE THREAD

**Issue by rottyfish** [DynamoDS/DynamoRevit#1931]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2.2480

## Revit version

2017

## Operating system

Windows 7 Pro

## What did you do? 

Run "Filter elements by workset name" node and Dynamo crashed

## What did you expect to see?

(Fill in here)

## What did you see instead?

Got a prompt to restart

**Comment by ksobon** [comment]
@rottyfish what package is that node from? Can you add images?

**Comment by ksobon** [comment]
@kronz I think that this is a node from a 3rd party package, not OOTB. Also this was dormant and request for more information has gone unanswered for over 2 months now. Can we close this? User can always re-open if they want to raise this issue again.

**Comment by kronz** [comment]
Agreed, appears to be from an outside package
