### ISSUE TITLE
Curved framing that follows complex surface is now broken in 1.3.2

### ISSUE THREAD

**Issue by edwinguerra** [DynamoDS/DynamoRevit#1939]
[1.31 Framing Complex Surfaces.dyn.zip](https://github.com/DynamoDS/DynamoRevit/files/1726059/1.31.Framing.Complex.Surfaces.dyn.zip)

## Dynamo version

1.3.2

## Revit version
2018

## Operating system
Windows 7-64bit

## What did you do? 

Followed procedure described (also in video and sample files http://bit.ly/2gMt3cT ) at my blog:
http://summitaec.com/framing-a-complex-roof-structure-using-dynamo/

## What did you expect to see?

I have a blog post describing the process for framing complex structures. It is very simple, select surface, select lines. Extrude lines, find intersection, use intersection curves to create structural framing. I tested it previously on 2017 with 1.3.1 and it all worked. The definition uses no external packages. I expected the framing to be generated when using 2018, 1.3.2

## What did you see instead?

Intersection curves are created, but at the final node, StructuralFraming.BeamByCurve , I am consistently getting a "knot" error and comments are piling on my blog referencing the same error:

Warning: StructuralFraming.BeamByCurve operation failed. 
The multiplicities of other interior knots must be at most degree - 2.
Parameter name: knots

occuring on the StructuralFraming.BeamByCurve node

This is very frustrating, so I would greatly appreciate any help. You can see in the video that it worked at one point in time.

In further testing, it appears to be specifically related to 1.3.2. I have been able to run same file successfully with other surfaces in 2016 using Dynamo 0.9. For 2018, I am unable to uninstall 1.3.2 which prevents me from verifying that it works in Revit 2018 with 1.3.1 or earlier versions of Dynamo.

**Comment by jnealb** [comment]
@edwinguerra Thanks for reporting this apparent regression. @mjkkirschner @kronz Any thoughts?

**Comment by kronz** [comment]
Yep, this is fixed in 2.0, .  (It deals with some of the more proprietary geometry stuff in ASM.  For those "on the inside", https://jira.autodesk.com/browse/DYN-904, https://git.autodesk.com/Dynamo/LibG/pull/554 )
The summary is that the Revit geometry kernel in 2017 and before used a differnt way to deal with knots that the 2018 version.  I believe the workaround is re-building the curves as new nurbs curves in Dynamo at the point before sending to Revit Structural framing.
