### ISSUE TITLE
ToProtoType() Conversion not as expected

### ISSUE THREAD

**Issue by MarkThorley** [DynamoDS/DynamoRevit#1940]
## Dynamo version
1.3.2

## Revit version
2018

## Operating system
Windows 10

## What did you do? 
I am attempting to convert a line/curve from Dynamo to a Revit Curve.

## What did you expect to see?
Using dynCurve.ToProtoType() I was expecting this to inherit the Autodesk.Revit.DB.Curve class. 

## What did you see instead?
Regardless of whether the dynamo geometry is a line or a curve they both get converted to Autodesk.Revit.DB.Line and then there seems no way of casting to the  Autodesk.Revit.DB.Curve class.

**Comment by MarkThorley** [comment]
ToRevitType() I meant

**Comment by mjkkirschner** [comment]
can you share some sample code here, how are you trying to use the resulting geometry where you cannot?

**Comment by mjkkirschner** [comment]
maybe a more clarifying question, why do you need to cast to the curve type?

**Comment by MarkThorley** [comment]
hey Mike,
In the curve class there is a method called EndPointReference which doesnt exist in the Line class, hence why I need it as a curve.

                Autodesk.Revit.DB.Curve revitCurve = curve.ToRevitType();
                Autodesk.Revit.DB.Curve newCurve = revitCurve as Autodesk.Revit.DB.Curve;
                Reference endRef = newCurve.GetEndPointReference(1);

Even trying to be explicit and cast it stays as a Autodesk.Revit.DB.Line

**Comment by MarkThorley** [comment]
this is weird because the method in the RevitNodes.dll for the conversion says it returns a curve

public static Autodesk.Revit.DB.Curve ToRevitType(this Autodesk.DesignScript.Geometry.Curve crv, [bool performHostUnitConversion = True])
    Member of Revit.GeometryConversion.ProtoToRevitCurve

**Comment by mjkkirschner** [comment]
A line is a curve in Revit.DB - line is an inherited class, so it's odd that `EndPointReference` does not exist on a derived class.

the revit api docs say that method exists on line:
http://www.revitapidocs.com/2017.1/5619a3fd-38e1-fb56-7286-2e5f33a3b2b8.htm

not to say that your original point that this conversion method is maybe returning a line type incorrectly.

**Comment by MarkThorley** [comment]
On a curve but not on the line?
http://www.revitapidocs.com/2017.1/154b23e2-9f1f-813b-df56-e7c1bb347711.htm

**Comment by MarkThorley** [comment]
ye even as a line it runs a null

            var revitCurve = curve.ToRevitType();
            Autodesk.Revit.DB.Line revitLine = revitCurve as Autodesk.Revit.DB.Line;
            Reference endRef = revitLine.GetEndPointReference(1);

**Comment by mjkkirschner** [comment]
is it possible to upload this code and the curve you are running this on? 
What happens if you do not perform this cast.

**Comment by MarkThorley** [comment]
I think I have found the issue.

"I would argue about the question-ability of the GetEndPointReference method. Agreed, it could probably be better documented to state more clearly that the references can only be obtained from curves that actually exist in a Revit model, but otherwise the method works well, I believe. It is also documented that it may return null, so I would advise that needs to be tested by programmers who invoke it."

https://forums.autodesk.com/t5/revit-api-forum/null-reference-error-when-adding-dimension/m-p/6388655#M16774

**Comment by mjkkirschner** [comment]
just note, that I don't think you need to perform that cast either way, you're going to be calling the method that exists on the inherited class not the base class method.

https://stackoverflow.com/questions/8329470/convert-derived-class-to-base-class

**Comment by mjkkirschner** [comment]
so seems you may want to manually use a  transaction and ensure the line is actually in the model.

**Comment by MarkThorley** [comment]
Ye I'm trying to avoid placing loads of model curves in the model. I assumed taking the .FullCurve of the CurtainGridLine would give me an actual curve in the model.

http://www.revitapidocs.com/2018/6bc234da-f624-9ac2-a306-6e62cfc77945.htm

However it also seems to return null. 
@ksobon how did you get around this when creating dims for curtain walls which is what I'm doing?

As you stated though @mjkkirschner the original issue of the ToRevitType() still stands even though we have moved away from that topic.

**Comment by ksobon** [comment]
```
def ReferenceFromCurtainGridLine(gridLine):
	opt = Options()
	opt.ComputeReferences = True
	opt.IncludeNonVisibleObjects = True
	geoElement = gridLine.get_Geometry(opt)
	for i in geoElement:
		if (type(i) == Autodesk.Revit.DB.Line):
			return i.Reference
			break
```
