### ISSUE TITLE
Excel Not Responding

### ISSUE THREAD

**Issue by mengelmn** [DynamoDS/DynamoRevit#1950]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.3.2

## Revit version
2018.2

## Operating system
Windows 10

## What did you do? 
Write a Value to A File Using out of the Box Write to Excel node from within Revit.
(Fill in here)

## What did you expect to see?
Values in Excel

## What did you see instead?
Excel becomes unresponsive.

Other Notes
1)  Dynamo Sandbox and Dynamo Studio Both Can write to excel using the same graph.
2) Last Week the issue existed and was resolved by removing and reinstalling Dynamo and Dynamo Cores
3)  Issue Returned Yesterday - fix was to reinstall excel (and full office from scratch) - This then worked last night and this morning.  After restarting Revit the problem has returned.

**Comment by mengelmn** [comment]
After forcing Excel Closed - Dynamo and Revit become Responsive with the following error noted in the write to excel node.

Warning: Excel.WriteToFile operation failed. 
The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)

![image](https://user-images.githubusercontent.com/20505196/37124102-88358980-222c-11e8-87fa-8ca8bc4ce75a.png)

**Comment by mengelmn** [comment]
After much digging I have a solution - though still baffeled at the cause.  
It is related to the GPU vs Integrated Graphics.  

Excel will not run on the GPU has to be run on the integrated Graphics Card.  Which in the settings it is set to only use the Integrated 

When running Dynamo Studio or Sandbox and writing to Excel, Excel does not use the GPU,  Dynamo Shows as pulling the GPU but Excel Does Not.   When Running Revit, and Dynamo for Revit, Excel attempts to pull the GPU which cause the unresponsiveness.  To remedy this one needs to go into the options of excel and disable hardware acceleration (even though it is already set in the system not to utilize it)  

This source led me to the solution after much trial and error of solutions.  

(Of course how in the past few days it worked some days at some times and not others is still baffeling)

**Comment by jnealb** [comment]
This is great; nicely done :)

**Comment by Jaiyakumar** [comment]
@mengelmn  Thanks for your effort.
But Even after checking the disable hardware graphic option. I am still getting this warning message in Dynamo.

Is it that - Am I doing something wrong in this?
It would be great - if you can advice on this.

![1](https://user-images.githubusercontent.com/37184105/41466044-63256e5c-7098-11e8-827a-f16abda10190.jpg)

**Comment by apurv-kashyap** [comment]
Hi. I tried the solution suggested by you. Strangely enough it helped to disable hardware acceleration in excel.
