### ISSUE TITLE
DYN files open in custom node workspace

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#1952]
## Dynamo version

2.0.0.4297

## Revit version

2017.2

## Operating system

Windows 10

## What did you do? 

Open a DYN file

## What did you expect to see?

Its workspace

## What did you see instead?

DYN file is opened as custom node (works okay in Sandbox)
![grafik](https://user-images.githubusercontent.com/3014437/37194277-be0e7b42-236d-11e8-99f5-444029944263.png)
I tried this with a number of files from here:
https://github.com/andydandy74/ClockworkForDynamo/tree/master/package_samples/1.x/dynamo
This is **not** happening in Revit 2018 BTW.

**Comment by QilongTang** [comment]
@jnealb @smangarole

**Comment by jnealb** [comment]
@andydandy74 @QilongTang @alfarok @mjkkirschner Not able to repro this with latest internal build:

![image](https://user-images.githubusercontent.com/9357222/37214328-af221660-2382-11e8-8644-00847ed6340c.png)

**Comment by andydandy74** [comment]
@jnealb Just rechecked on my work machine - same issue in Revit 2017.2.3 (as opposed to 2017.2 at home). Seems to be limited to Revit 2017 running in **German**. Works just fine in English UI.

**Comment by andydandy74** [comment]
While I was at it, I checked in French as well, same issue:
![grafik](https://user-images.githubusercontent.com/3014437/37216436-0a2966b6-23bb-11e8-98ba-51f15217ae1e.png)
So most likely a localization issue? I would guess that this happens in all non-English versions.

**Comment by jnealb** [comment]
will look

**Comment by mjkkirschner** [comment]
I can't seem to reproduce it yet, but I have only tried setting Revit to DEU -not my entire system.
![screen shot 2018-03-09 at 1 22 15 pm](https://user-images.githubusercontent.com/508936/37223116-82ed0300-239d-11e8-8236-28929637ce1f.png)

@andydandy74 I am also on 2017.2, and core 2.0..04297

**Comment by mjkkirschner** [comment]
@jnealb even after setting revit to DEU I am still getting Dynamo menu items in english, what am I missing there?

**Comment by mjkkirschner** [comment]
@andydandy74 I can reproduce it when Dynamo goes into localized mode...
:(

**Comment by mjkkirschner** [comment]
<img width="835" alt="screen shot 2018-03-09 at 1 39 04 pm" src="https://user-images.githubusercontent.com/508936/37223663-40853652-239f-11e8-87ff-3292926e6c9e.png">

@jnealb @kronz

**Comment by jnealb** [comment]
@andydandy74 @mjkkirschner This is tracked with QNTM-3652.

**Comment by mjkkirschner** [comment]
@andydandy74 this should be resolved in the daily builds sometime next week.
https://github.com/DynamoDS/Dynamo/pull/8642

**Comment by andydandy74** [comment]
Looking good. Thanks!
