### ISSUE TITLE
Alpha-numeric detail numbering... but invert the x-axis!

### ISSUE THREAD

**Issue by AWRash** [DynamoDS/DynamoRevit#2012]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo 1.3.2.2480

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit 2018

(Which version of Revit are you using?)

## Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Auto-naming views on sheet in alpha-numeric order 

## What did you expect to see?

The script I've cobbled together from various videos works, but the catch for this particular task requires inverting the x-axis so theoretical detail view "1A" will be on the lower right-hand side near title block, instead of at the binding side. I'll be upfront, I've got very little Dynamo skills and even less Python... but basic premises of each understood. I think the fix lies in inverting the x-axis in the Viewport Properties node python script. 
![capture](https://user-images.githubusercontent.com/38443953/38839854-a2ee7690-41aa-11e8-9068-23dfca346f25.JPG)
![2](https://user-images.githubusercontent.com/38443953/38839857-a8640fae-41aa-11e8-943e-281c78f4eef8.JPG)

Is there some python language which can invert the 0 position (so to speak) to have the desired outcome below?
Many thanks from a green newb. 

(![capture](https://user-images.githubusercontent.com/38443953/38839406-6e25f61a-41a8-11e8-83fe-d7305f6e31b5.JPG)))

**Comment by AWRash** [comment]
let me know if it would help anyone to have the .dyn file to facilitate a solution

**Comment by andydandy74** [comment]
You should take this question to the forum:
https://forum.dynamobim.com/
The GitHub site is for recording bugs and feature requests only.

**Comment by AWRash** [comment]
Sorry for for misunderstanding where to post this - I'll close the issue
