### ISSUE TITLE
Dynamo Core could not be found though it is installed.

### ISSUE THREAD

**Issue by alkhayyatw** [DynamoDS/DynamoRevit#2024]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(2.0.0)

## Revit version

(Revit 2019 and 2018)

## Operating system

(Windows 10)

## What did you do? 

(I opened Revit as usual and a warning popped up saying "Dynamo Add-In is not able to find an installation of Dynamo Core version 1.3 or higher..." and it asked me to download the latest version of DynamoCore.msi from http://dynamobim.org
![1](https://user-images.githubusercontent.com/38832058/39405276-0cdaaccc-4bab-11e8-88c7-a7cd8749a2d1.PNG)
)

## What did you expect to see?

(I expected not to see the previous warning because I have Dynamo Core 2.0.0 and 1.3 versions, although, I installed the version 2.0.0 again which means that I clicked on OK
![1](https://user-images.githubusercontent.com/38832058/39405263-eb1a4566-4baa-11e8-9294-3e233f65579f.PNG)
)

## What did you see instead?

(Dynamo and Dynamo player are no more shown in Revit while the application is installed successfully on my computer (the latest version indeed)
![2](https://user-images.githubusercontent.com/38832058/39405281-24c3a23a-4bab-11e8-97b1-207eb4e9b3b0.PNG)
)

**Comment by aminghali** [comment]
I have the same problem

**Comment by jnealb** [comment]
@aminghali @alkhayyatw One suggestion: first un-install all versions of Dynamo, using the Microsoft Fixit utility if necessary (for uninstall). Then uninstall R2019 and re-install it.

**Comment by aminghali** [comment]
@jnealb worked perfectly, thanks.
