### ISSUE TITLE
Copy/pasting/deleting nodes does not work anymore in Revit 2019

### ISSUE THREAD

**Issue by mathib** [DynamoDS/DynamoRevit#2025]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Tested in v.1.3.3 and 2.0.0

## Revit version

Tested on Revit 2019.0.1.1

## Operating system

Wind 10

## What did you do? 

Use ctrl+v/ctr+c/delete to copy/paste/delete one or more nodes

## What did you expect to see?

Just a quick way to copy/paste/delete nodes, just as it worked for Dynamo v1.3.3 and v2.0.0 in Revit 2018.3 and prior

## What did you see instead?

Nothing. Normal text input in a code block does work

**Comment by mjkkirschner** [comment]
this is a known issue with revit 2019, and should be fixed in the next point release there.
