### ISSUE TITLE
Failure to start Dynamo

### ISSUE THREAD

**Issue by JLMarCa** [DynamoDS/DynamoRevit#2026]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.0.0.0.4655

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version
2017.2.3

(Which version of Revit are you using?)

## Operating system
Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

I installed Dynamo and some packages

## What did you expect to see?

The main Dynamo screen with the  usable nodes 

## What did you see instead?

![image](https://user-images.githubusercontent.com/38880590/39483166-d16d7368-4d71-11e8-9c99-b9771a33241b.png)

**Comment by ramramps** [comment]
Can you go to the `green` icon on the top and get the notifications? 
Also, do you have McAfee installed on your machine?

**Comment by JLMarCa** [comment]
Hi

I have 5 notifications

I copy and paste the information of each of them

My antivirus program is the Norton version 22.14.0.54

Regarding Dynamo ... I have already tried to uninstall and reinstall
several times and I have always obtained the same error at the start of the
application

thank you so much for your attention

Best regards

*José-Luis Martínez Cava*
Arquitecto Técnico e Ingeniero de Edificación | BIM Expert
| jlmcblau@gmail.com







1. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser
inestable. Si se detectan problemas, desinstale los complementos o paquetes
y póngase en contacto con el proveedor.

Al cargar el montaje LibraryViewExtension, Version=2.0.0.4654,
Culture=neutral, PublicKeyToken=null, Dynamo ha detectado que la
dependencia CefSharp, Version=57.0.0.0, Culture=neutral,
PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión
incompatible. Es probable que otro complemento de Revit haya cargado este
montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo.
Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión
incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core,
Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

2. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser
inestable. Si se detectan problemas, desinstale los complementos o paquetes
y póngase en contacto con el proveedor.

Al cargar el montaje LibraryViewExtension, Version=2.0.0.4654,
Culture=neutral, PublicKeyToken=null, Dynamo ha detectado que la
dependencia CefSharp.Core, Version=57.0.0.0, Culture=neutral,
PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión
incompatible. Es probable que otro complemento de Revit haya cargado este
montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo.
Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión
incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core,
Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

3. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser
inestable. Si se detectan problemas, desinstale los complementos o paquetes
y póngase en contacto con el proveedor.

Al cargar el montaje CefSharp, Version=57.0.0.0, Culture=neutral,
PublicKeyToken=40c4b6fc221f4138, Dynamo ha detectado que la dependencia
CefSharp, Version=57.0.0.0, Culture=neutral,
PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión
incompatible. Es probable que otro complemento de Revit haya cargado este
montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo.
Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión
incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core,
Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

4. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser
inestable. Si se detectan problemas, desinstale los complementos o paquetes
y póngase en contacto con el proveedor.

Al cargar el montaje CefSharp.Wpf, Version=57.0.0.0, Culture=neutral,
PublicKeyToken=40c4b6fc221f4138, Dynamo ha detectado que la dependencia
CefSharp, Version=57.0.0.0, Culture=neutral,
PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión
incompatible. Es probable que otro complemento de Revit haya cargado este
montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo.
Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión
incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core,
Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

5. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser
inestable. Si se detectan problemas, desinstale los complementos o paquetes
y póngase en contacto con el proveedor.

Al cargar el montaje CefSharp.Wpf, Version=57.0.0.0, Culture=neutral,
PublicKeyToken=40c4b6fc221f4138, Dynamo ha detectado que la dependencia
CefSharp.Core, Version=57.0.0.0, Culture=neutral,
PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión
incompatible. Es probable que otro complemento de Revit haya cargado este
montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo.
Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión
incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core,
Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms





2018-05-01 19:27 GMT+02:00 ramramps <notifications@github.com>:

**Comment by JLMarCa** [comment]
Hi

I have 5 notifications

I copy and paste the information of each of them

My antivirus program is the Norton version 22.14.0.54

Regarding Dynamo ... I have already tried to uninstall and reinstall several times and I have always obtained the same error at the start of the application

thank you so much for your attention

Best regards

JlMarCa

![image](https://user-images.githubusercontent.com/38880590/39517911-9e004a60-4e01-11e8-99d2-7f1848ca227e.png)

1. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser inestable. Si se detectan problemas, desinstale los complementos o paquetes y póngase en contacto con el proveedor.

Al cargar el montaje LibraryViewExtension, Version=2.0.0.4654, Culture=neutral, PublicKeyToken=null, Dynamo ha detectado que la dependencia CefSharp, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión incompatible. Es probable que otro complemento de Revit haya cargado este montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo. Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core, Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

2. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser inestable. Si se detectan problemas, desinstale los complementos o paquetes y póngase en contacto con el proveedor.

Al cargar el montaje LibraryViewExtension, Version=2.0.0.4654, Culture=neutral, PublicKeyToken=null, Dynamo ha detectado que la dependencia CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión incompatible. Es probable que otro complemento de Revit haya cargado este montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo. Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core, Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

3. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser inestable. Si se detectan problemas, desinstale los complementos o paquetes y póngase en contacto con el proveedor.

Al cargar el montaje CefSharp, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138, Dynamo ha detectado que la dependencia CefSharp, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión incompatible. Es probable que otro complemento de Revit haya cargado este montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo. Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core, Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

4. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser inestable. Si se detectan problemas, desinstale los complementos o paquetes y póngase en contacto con el proveedor.

Al cargar el montaje CefSharp.Wpf, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138, Dynamo ha detectado que la dependencia CefSharp, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión incompatible. Es probable que otro complemento de Revit haya cargado este montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo. Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core, Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

5. System.IO.FileLoadException

Dynamo ha detectado un conflicto con una dependencia y podría ser inestable. Si se detectan problemas, desinstale los complementos o paquetes y póngase en contacto con el proveedor.

Al cargar el montaje CefSharp.Wpf, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138, Dynamo ha detectado que la dependencia CefSharp.Core, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138 ya se había cargado con una versión incompatible. Es probable que otro complemento de Revit haya cargado este montaje. Pruebe a desinstalar otros complementos e iniciar Dynamo de nuevo. Dynamo podría ser inestable en este estado.
Es probable que uno de los montajes siguientes haya cargado la versión incompatible:
RevitPlugin, BusinessLogic, BusinessLogic, BusinessLogic, CefSharp.Core, Revit2017, Revit2017, CefSharp.WinForms, CefSharp.WinForms

**Comment by mjkkirschner** [comment]
same as :https://github.com/DynamoDS/DynamoRevit/issues/2019

**Comment by JLMarCa** [comment]
Thank you very much for your quick response Michael
I have deactivated plugin NBS and Dynamo works!!!
Great!
Best regards

**Comment by smangarole** [comment]
Thanks for the update @JLMarCa. Closing this for now.
