### ISSUE TITLE
Trouble with Excel.ReadFromFile node

### ISSUE THREAD

**Issue by pdickman12** [DynamoDS/DynamoRevit#2037]
Excel opens but stops responding with Excel.ReadFromFile node.

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## 1.3.3.4651

(Which version of Revit are you using?)18.3.0.81

## What did you do? 
![dynamoerrorexcel](https://user-images.githubusercontent.com/39013810/39667280-7c879eb6-5080-11e8-89df-409d33cca259.PNG)

(Tried to pull data from an excel file)

## What did you expect to see?

(Data from excel file)

## What did you see instead?

Excel hangs. When Excel is closed, Dynamo returns this warning.

Warning: Excel.ReadFromFile operation failed. 
Value cannot be null.
Parameter name: pNativeData

**Comment by pdickman12** [comment]
Dell pushed through an updated video card driver. I updated the driver and now the node is working!

**Comment by jnealb** [comment]
Thanks for the update.
