### ISSUE TITLE
archilab/rhythm node issue

### ISSUE THREAD

**Issue by gundelund** [DynamoDS/DynamoRevit#2039]
## Dynamo version

2.0.0

## Revit version

2017

## Operating system

Windows 7

## What did you do? 

Some nodes have issues with Dynamo 2.0.0 (see image below). It looks fine at first, but when I save the file and open it up again there is an issue. Every time the .dyn-file is opened, there is one more output from the nodes. The nodes are from archilab(2018.2.2) and Rhythm (2018.4.20). There was no problem before upgrading to Dynamo 2.0.0.

## What did you expect to see?

Only one output

## What did you see instead?

![multiple_output](https://user-images.githubusercontent.com/39090212/39758558-7b5c7da2-52d0-11e8-821e-c09dc2c83b96.JPG)

**Comment by ksobon** [comment]
@gundelund thanks for reporting this. I will take care of the archi-lab.net node issue here: https://github.com/ksobon/archilab/issues/14

**Comment by ksobon** [comment]
@gundelund just to give you some context. this happens when package was not updated to 2.0 (which might be the case with rhythm), and if there are conflicting versions of Newtonsoft.json loaded into revit, so in theory it could be a conflict with other 3rd party package.

**Comment by sixtysecondrevit** [comment]
Rhythm is not compatible with Dynamo 2.0 fully quite yet. The UI nodes are the main ones that break at this time. (Also, I removed space types from the package today).

**Comment by ksobon** [comment]
@gundelund this was just fixed with archi-lab version 2019.2.0 Please download that from Package Manager. In the future any issues regarding archi-lab please post to https://github.com/ksobon/archilab/issues 

@kronz can we close this issue?

**Comment by sixtysecondrevit** [comment]
Fixed in latest version of rhythm too. 😎
