### ISSUE TITLE
Minor bugs - F5, characters in code blocks, delete

### ISSUE THREAD

**Issue by ntikb** [DynamoDS/DynamoRevit#2044]
## Dynamo version
Dynamo Core: 2.0.0.4654
Dynamo Revit: 2.0.0.4655

## Revit version

Revit 2019 (19.0.0.405)
Build 20180216_1515(x64)

## Operating system

Windows 10

## What did you do? 
1) Press F5 to run script
2) Delete node by del key on keyboard.
3) Delete characters in code block by del key on keyboard.
4) Add character " or ; in code block.
5) Ctrl+c / ctrl+v to copy/paste node or nodes.
6) Try running script having a (red) code block containing an error.

## What did you expect to see?
1) Script being run.
2) Node being deleted.
3) Content being deleted from code block.
4) Character added as usual.
5) Nodes being copied.
6) Script being run, but failing the code block containing an error.

## What did you see instead?
1) Nothing happens, script is not being run
2) Node is not deleted, instead the delete tool in Revit is activated.
3) Content is not being deleted, instead the delete tool in Revit is activated.
4) Character added, but with the sound of Windows Background.wav. (This also seems to be true for all the number keys plus ,.-'<
5) Nothing happens
6) Script is not being run. Upon removing the node with the error, the script can be run again.

**Comment by QilongTang** [comment]
This is a known Revit issue, please see discussion in https://github.com/DynamoDS/Dynamo/issues/8785 and https://github.com/DynamoDS/DynamoRevit/issues/2025.
