### ISSUE TITLE
Problem with Parameter.IsReadOnly

### ISSUE THREAD

**Issue by dbaldacchino** [DynamoDS/DynamoRevit#2052]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## What did you do? 

This node is not accepting lists. If I pass a list, I get this error which it asks to be reported:

![image](https://user-images.githubusercontent.com/4656191/40086296-66f1d856-5863-11e8-9568-ec7f1b1e431e.png)

It works fine with a single element.

![image](https://user-images.githubusercontent.com/4656191/40086476-189d3122-5864-11e8-8a27-38d3ab7b7022.png)

I tried using list.map to see if I could get it to work on a list but was unable to (same error showed up).

## What did you expect to see?

I expected this node to work on lists.

## What did you see instead?

See error above.

**Comment by dbaldacchino** [comment]
Ok, it WORKS with lists, but fails if there are nulls in the list. In my use case I made a selection of all objects by workset, so naturally there were built-in items that belonged to Workset1 (ID 0) which returned a null when I tried to check which parameters in the list were read-only. Cleaning out the nulls restored functionality.

**Comment by aparajit-pratap** [comment]
It looks like the node throws a null reference exception for null parameters that isn't checked. It should ideally have a null check: @jnealb @QilongTang

**Comment by jnealb** [comment]
Thanks @dbaldacchino - we have forwarded your report to the appropriate dev team.
