### ISSUE TITLE
No search results for string

### ISSUE THREAD

**Issue by NWoodsman** [DynamoDS/DynamoRevit#2056]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.0.4655

## Revit version

2017.2

## Operating system

Windows 10

## What did you do? 

Search for the node "All Elements of Type" using any combination of those words, eg "all elements", "elements of type", "type", "elements of", etc.

## What did you expect to see?

Expected to see the node in the search results.

## What did you see instead?

Cannot find node.

**Comment by jnealb** [comment]
@NWoodsman This is fixed with the 2.0.1 daily build
