### ISSUE TITLE
Missing modification star "*" if we only change node as "IsInput"

### ISSUE THREAD

**Issue by chtimi59** [DynamoDS/DynamoRevit#2058]
## Dynamo version

2.0.1.4917

## Revit version

2.0.1.4917

## Operating system

Windows 10

## What did you do? 

Open an existing graph with Input\Basic\String in it. Right click on those node to toggle "Is Input"

## What did you expect to see?

- A little star aside of graph name, to mark the document as an modified one.
- If I close the document without saving it, I expect a prompt like "Save the documement ?"

## What did you see instead?

Nothing tell me that the document has been modified

**Comment by jnealb** [comment]
@chtimi59 Thank you for this report. This is tracked with QNTM-4350 and is part of the 2.1 release backlog.
