### ISSUE TITLE
Mandrill error - Crash Launch window

### ISSUE THREAD

**Issue by 8434alberto** [DynamoDS/DynamoRevit#2059]
## What did you do? 

Hi to everyone guys,
I really need your help please.

MANDRILL for Dynamo:
Report Window (Launch Window) node dosn't have input and I can't connect it to Create Report node (It has a D3jsLib.Report inside). Why? 

If I use Save to Html node, Dynamo Crash every time.
Error:
"(Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index"

Any solutions?

Thanks.

**Comment by jnealb** [comment]
@8434alberto We will need more information: your Dynamo graph, Revit model, any loaded Packages.

**Comment by 8434alberto** [comment]
![01 simple](https://user-images.githubusercontent.com/39626798/40550971-f49dd0a8-603b-11e8-841d-cfe4afbbdcaa.JPG)
![01b](https://user-images.githubusercontent.com/39626798/40550979-fda2e36e-603b-11e8-921d-7a080571e34e.JPG)

Revit Model 2016 with many planting elements. 
You can see the loaded packages on the screenshots attached.

It doesn't work even with a simplest graph (image01).

**Comment by jnealb** [comment]
@8434alberto We are able to reproduce your results with D4R 1.3.3, but also find that if you click the '+' control of the Create Report node (in Automatic execution mode) then the node appears to function (giving 2 charts). You can then click the '-' control to drop the second chart, so you may then have a workaround? The relevant files are attached. We have recently released Dynamo 2.0.1 which is available from our website, fyi (but of course not all Packages are migrated to 2.0).

**Comment by jnealb** [comment]
![report](https://user-images.githubusercontent.com/9357222/40564670-895abf30-6037-11e8-90cc-2786a304aaa4.jpg)
