### ISSUE TITLE
"System.IO.FileLoadException", missing left node panel, & packages won't uninstall

### ISSUE THREAD

**Issue by JasWright** [DynamoDS/DynamoRevit#2111]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.1.5065

## Revit version

Revit 2018.2

## Operating system

Windows 7

## What did you do? 

Open Dynamo 2.0.1 from Revit 2018 and the nodes folders to the left are missing. There are also 7 notifications on the task bar that says System.IO.FileLoadException. I tried uninstalling the only plug in on it and it remains "uninstall pending" permanently.

## What did you expect to see?

Dynamo 2.0.1 open with all the nodes folders to the left and for packages to uninstall. 

## What did you see instead?

Packages still remain in manage package folder with red tag "uninstall pending". And a blank left panel in the Dynamo UI

![image](https://user-images.githubusercontent.com/42219353/43858889-325e80d8-9b1d-11e8-9a0f-0bf55f3b6a95.png)

![image](https://user-images.githubusercontent.com/42219353/43858923-4cf9e93c-9b1d-11e8-9a01-cb10c6fe4436.png)

**Comment by mjkkirschner** [comment]
Hi @JasWright please click the show details buttons on the notifications to see what they refer to.

Also please upgrade your 2018 to 2018.2 if you have pnid modeler addin installed (it comes with revit by default)

**Comment by JasWright** [comment]
Hey @mjkkirschner and thanks for checking in on this! I've been getting by with the search on the right mouse click, but would still love to solve this issue. I have uninstalled add-in and same issue persists. Where do I upgrade the pnid modeler to 2018.2?

I currently have Revit 2018.2. The details of the error are attached below: 
![system io fileloadexception](https://user-images.githubusercontent.com/42219353/44743558-d51a7300-aad0-11e8-8115-6d6ded4a6346.png)

**Comment by Mootjuh** [comment]
I too have this problem, using Windows 10.

**Comment by mjkkirschner** [comment]
@JasWright and @Mootjuh I'm sorry, 2018.2 is the version with the error - please update to 2018.3 it should be fixed there (the conflict with pnid modler addin)

**Comment by QilongTang** [comment]
@JasWright Thank you for verification! Cheers.
