### ISSUE TITLE
Logic node "If" produce wrong result given empty list as input

### ISSUE THREAD

**Issue by 1moresec** [DynamoDS/DynamoRevit#2124]
## Dynamo version

Dynamo Core 2.0.1.5055
Dynamo Revit 2.0.1.5065

## Revit version

Revit 2019

## Operating system

Windows 10 Enterprise N

## What did you do? 

Fill an "If" node with an empty list as input

## What did you expect to see?

Return the other input [1]

## What did you see instead?

![image](https://user-images.githubusercontent.com/24972688/45533234-889d9a00-b829-11e8-8cad-9159c53e6809.png)

**Comment by andydandy74** [comment]
Same issue as https://github.com/DynamoDS/Dynamo/issues/6258
This is working as designed.
Use ScopeIf node instead

**Comment by 1moresec** [comment]
Thanks for the explanation.
