### ISSUE TITLE
Wish: Warning if active command in Revit prevents graph execution

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#2134]
## Dynamo version

Any

## Revit version

Any

## Operating system

Any

## What did you do? 

Ran a graph while a command in Revit was still active

## What did you expect to see?
Dynamo warning me that the graph can't be run while a command in Revit is still active
![grafik](https://user-images.githubusercontent.com/3014437/46435617-0e40a580-c757-11e8-9a6d-d4334c16e53c.png)

## What did you see instead?
No warning. Dynamo pretends to run the graph but it doesn't.
![grafik](https://user-images.githubusercontent.com/3014437/46434245-6b3a5c80-c753-11e8-9488-01567a472115.png)

Previously filed here: https://github.com/DynamoDS/Dynamo/issues/965

**Comment by AndyDu1985** [comment]
DynamoRevit uses Idle event to comunicate with Revit, when Revit is busy, it won't trigger the Idle event, so DynamoRevit won't get chance to know the status of Revit.

**Comment by ZiyunShang** [comment]
Due to Revit API limited, we may not be able to do more now.
