### ISSUE TITLE
Sheet.ByNameNumberTitleBlockAndView fails on empty View

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2149]
<a href="https://github.com/DavePlumb"><img src="https://avatars2.githubusercontent.com/u/18071127?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DavePlumb](https://github.com/DavePlumb)**
_Friday May 11, 2018 at 14:21 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/8858_

----

If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2

## Operating system

Windows 7 SP1

## What did you do? 

Use Sheet.ByNameNumberTitleBlockAndView node to create a Sheet and place a View on it.

## What did you expect to see?

View placed on Sheet

## What did you see instead?

The node works properly provided there is something visible in the View being placed.
However, if the View is completely empty, the node simply fails to place the View on the Sheet.
This is expected Revit behavior, so there's really nothing "wrong" with the node.
It's just that I'd expect the node to throw an error or a warning saying that it failed to place an empty View

**Comment by ZiyunShang** [comment]
Hi @DavePlumb , here is a new node added to create a sheet with no views - https://github.com/DynamoDS/DynamoRevit/pull/2513 . You can get it in latest DynamoRevit version.
