### ISSUE TITLE
SetParameterByName fails on Families (adaptive components) structured in a list of rank 3

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2155]
<a href="https://github.com/ThomasMahon"><img src="https://avatars3.githubusercontent.com/u/18601851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ThomasMahon](https://github.com/ThomasMahon)**
_Thursday Apr 21, 2016 at 21:34 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/6493_

----

## Dynamo version

0.9.2
## Operating system

Win 10
## What did you do?

I have an Adaptive Component cladding system organised in a 3D list/rank 3 (List of list of lists). I iterate through the list to update each components instance parameters within an imperative DesignScript block but it fails to update the parameters.
## What did you expect to see?

The instance parameters update with the information I was giving it (import from Excel). Instead, I had to extract the sublist of panels first (so 2D list/rank 2) and return it back into a 3D array once I had iterated through the list to get around the bug. 
## What did you see instead?

No change to the instance parameters. 
(Fill in here)

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/ikeough"><img src="https://avatars1.githubusercontent.com/u/1139788?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ikeough](https://github.com/ikeough)**
_Thursday Apr 21, 2016 at 21:44 GMT_

----

@ke-yu Sounds like an imperative block issue.

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/ThomasMahon"><img src="https://avatars3.githubusercontent.com/u/18601851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ThomasMahon](https://github.com/ThomasMahon)**
_Thursday Apr 21, 2016 at 22:02 GMT_

----

Just some further information to clarify the above; I did achieve SetParameterByName within DesignScript imperative block, but only by extracting the sublist to a new list, operating on that list inside a secondary for loop, then returning back into a primary list to retain my required data structure (i.e. 3D list). That was the workaround I mentioned. See image

<img width="963" alt="setparameterbyname problem" src="https://cloud.githubusercontent.com/assets/18601851/14725715/940ed096-0815-11e6-8b16-1bd77b57ddcb.PNG">

**Comment by ZiyunShang** [comment]
Hi @ThomasMahon , are you experiencing this issue in latest version now?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
