### ISSUE TITLE
Installation and access problems

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2156]
<a href="https://github.com/vykrum"><img src="https://avatars3.githubusercontent.com/u/5621624?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vykrum](https://github.com/vykrum)**
_Friday Apr 15, 2016 at 05:43 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/6434_

----

## Dynamo version

1.0.1.1050
## Operating system

Windows 10
## What did you do?

Searched for Dynamo on the windows search bar
## What did you expect to see?

Dynamo 1.0 listed in the search results
## What did you see instead?

Nothing
Dynamo isn't listed under All Apps in the Windows Start Menu

The sequence of events......
Initially was able to run Dynamo standalone, but not from Revit

So, uninstalled Dynamo 1.0 and reinstalled

Now it runs from Revit, but no standalone (sort of)

PS: Standalone Dynamo without background 3D (but with a 2D grid) can be accessed from

C:\Program Files\Dynamo\Dynamo Revit\1.0\DynamoSandbox.exe

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/kronz"><img src="https://avatars3.githubusercontent.com/u/3456818?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kronz](https://github.com/kronz)**
_Saturday Apr 16, 2016 at 01:33 GMT_

----

FYI @sharadkjaiswal

**Comment by ZiyunShang** [comment]
Hi @vykrum , are you experiencing this issue in latest version now?
BTW, since Revit 2020, Dynamo will be an internal addin, not standalone.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
