### ISSUE TITLE
Crash from Element.GetParameterValueByName

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2157]
<a href="https://github.com/DavePlumb"><img src="https://avatars2.githubusercontent.com/u/18071127?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DavePlumb](https://github.com/DavePlumb)**
_Friday Mar 25, 2016 at 13:43 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/6311_

----

## Dynamo version

0.9.1
## Operating system

Windows 7-64 SP1
## What did you do?

My graph selects all Doors in a project, then gets the nearby Rooms
Next it compares the Door Number to both Room Numbers and sets a flag if the Door matches one of the Rooms or false if it matches neither.
## What did you expect to see?

This has worked on small projects, but on a large project with
I got an error:
**Internal error: please report: 
Dereferencing a non-pointer (3f47aacd)**
(Image attached)
This was in an Element.GetParameterValueByName node

I've attached the graph and an image of the error, but the Revit project is 400 Meg, 
If you want to test the graph, you'll also want to remove the "Filter Superdoors" node.
That node uses a parameter that is unique to our doors. 
"Normal" doors will work fine bypassing that node.
![dynamoerror](https://cloud.githubusercontent.com/assets/18071127/14045134/71095028-f265-11e5-87ef-7b2149ce1ff3.PNG)

[DoorNumberQA.dyn.txt](https://github.com/DynamoDS/Dynamo/files/189557/DoorNumberQA.dyn.txt)

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/DavePlumb"><img src="https://avatars2.githubusercontent.com/u/18071127?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DavePlumb](https://github.com/DavePlumb)**
_Friday Mar 25, 2016 at 13:54 GMT_

----

Forgot to mention:
By "large project", I meant there are about 1600 Doors.
Is there perhaps a limit on List length?

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/ke-yu"><img src="https://avatars1.githubusercontent.com/u/2600379?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ke-yu](https://github.com/ke-yu)**
_Monday Mar 28, 2016 at 14:45 GMT_

----

No limit on list length. I'll do some test with your graph.

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/DavePlumb"><img src="https://avatars2.githubusercontent.com/u/18071127?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DavePlumb](https://github.com/DavePlumb)**
_Monday Mar 28, 2016 at 15:10 GMT_

----

I've been narrowing it down this morning, and I think I understand what's going on.
The error message is generated when the Element.GetParameterValueByName node is passed a nul value for the "element" input. 
So that makes sense.
Now I have to figure a way around that condition in my graph.

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/ikeough"><img src="https://avatars1.githubusercontent.com/u/1139788?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ikeough](https://github.com/ikeough)**
_Thursday Apr 21, 2016 at 20:59 GMT_

----

@DavePlumb You shouldn't have to "get around" this. We should safely handle nulls input to that node.

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/jnealb"><img src="https://avatars1.githubusercontent.com/u/9357222?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jnealb](https://github.com/jnealb)**
_Thursday Apr 21, 2016 at 21:25 GMT_

----

@ikeough @DavePlumb @ke-yu This, and another "user not friendly" issue are tracked: please see MAGN-9976, 9915.

**Comment by ZiyunShang** [comment]
Hi @DavePlumb , are you experiencing this issue in latest version now?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
