### ISSUE TITLE
Cannot use Revit API "TopographyEditScope" in Dynamo Python Script

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2159]
<a href="https://github.com/rbosborne"><img src="https://avatars2.githubusercontent.com/u/12659052?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rbosborne](https://github.com/rbosborne)**
_Monday Feb 29, 2016 at 13:59 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/6189_

----

## Dynamo version

0.9.0
## Operating system

 Windows 7
## What did you do?

I am trying to add points to a topo (not create new, but add points to an existing) in Revit using PythonScript In Dynamo.  This requires the use of TopographyEditScope.  It seems that TopographyEdit Scope does not play nice with Dynamo.  See this post on the user forum:
http://dynamobim.org/forums/topic/topo-add-points-api-guru-help-needed/
## What did you expect to see?

I expected to be able to enter the TopographyEditScope, Add points, and see new points added to the topo
## What did you see instead?

Error on PythonScript (see pics on Dynamo Forum)

**Comment by ZiyunShang** [comment]
Hi @rbosborne , do you experience this issue in latest version now?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
