### ISSUE TITLE
Element.OverrideColorInView continuos crash

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2167]
<a href="https://github.com/safawi"><img src="https://avatars3.githubusercontent.com/u/9339366?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [safawi](https://github.com/safawi)**
_Monday Sep 14, 2015 at 14:18 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/5296_

----

Hi I'm not able to complete this task because every time dynamo crashes (virtual machine error).
I'm using dynamo 0.8.2 on revit 2016 and trying to override 7850 curtain panels by colour using their area as a parameter. It should be an easy task. What's wrong?

![dynamo error](https://cloud.githubusercontent.com/assets/9339366/9851970/a19955a8-5af3-11e5-8a97-adff436d8c8c.jpg)
![capture](https://cloud.githubusercontent.com/assets/9339366/9851978/a46a573c-5af3-11e5-84d7-201162e6416c.png)

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/aparajit-pratap"><img src="https://avatars0.githubusercontent.com/u/5710686?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [aparajit-pratap](https://github.com/aparajit-pratap)**
_Wednesday Sep 16, 2015 at 02:36 GMT_

----

@Randy-Ma could you take a look at this? Thanks.

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/Randy-Ma"><img src="https://avatars0.githubusercontent.com/u/5584246?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Randy-Ma](https://github.com/Randy-Ma)**
_Wednesday Sep 16, 2015 at 09:02 GMT_

----

From the call stack, it looks like that there might be some race condition and it can not be caused by the OverrideColorInView node

**Comment by ZiyunShang** [comment]
Hi @safawi , do you experience this issue in latest version now?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
