### ISSUE TITLE
Error, but no error

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2168]
<a href="https://github.com/vykrum"><img src="https://avatars3.githubusercontent.com/u/5621624?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vykrum](https://github.com/vykrum)**
_Saturday Sep 05, 2015 at 08:15 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/5237_

----

ver:0.8.3.2464
OS: Win7

I might have reported something on these lines earlier (related to defined functions) , but it's getting to be a regular bother lately.
A definition (with no defined functions) when rerun after making a change in the associated Revit file, does not execute and shows error warnings

![20150905-1](https://cloud.githubusercontent.com/assets/5621624/9698444/3321e188-53d4-11e5-9877-5fa7085e4411.png)

The same file executes as expected on reopening.

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/monikaprabhu"><img src="https://avatars3.githubusercontent.com/u/5218721?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [monikaprabhu](https://github.com/monikaprabhu)**
_Monday Sep 07, 2015 at 03:23 GMT_

----

@vykrum - Thanks for reporting this - Can you also check the value passed to this node when its throwing this error ? is RM passed to this function returning a non- null value when its throwing this error ? Are you saying that when you modified the code shown above in the image and rerun it did not execute ?

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/vykrum"><img src="https://avatars3.githubusercontent.com/u/5621624?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vykrum](https://github.com/vykrum)**
_Monday Sep 07, 2015 at 03:44 GMT_

----

@monikaprabhu not changes to the code, changes to the associated Revit elements 
In the example above, the code is referencing Rooms in Revit
The variable _Rm_ is a set Rooms, _RmFil_ selects a few and _RmBb_ converts the selected few to Dynamo Geometry.

**Comment by ZiyunShang** [comment]
Hi @vykrum , do you experience this issue in latest version now?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
