### ISSUE TITLE
Minus symbol inside custom node watch

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2172]
<a href="https://github.com/mjkkirschner"><img src="https://avatars3.githubusercontent.com/u/508936?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjkkirschner](https://github.com/mjkkirschner)**
_Monday Jun 22, 2015 at 19:02 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/4767_

----

From a user, is this symbol intended and what does it mean?

With no output connected, the watch window shows a green “minus” symbol;
![image001](https://cloud.githubusercontent.com/assets/508936/8290231/954b95d6-18ef-11e5-960a-a11c6b115626.png)
With an output connected the watch window shows the expected output;

![image002](https://cloud.githubusercontent.com/assets/508936/8290233/97729922-18ef-11e5-8c93-3c58d0b82a94.png)

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/ikeough"><img src="https://avatars1.githubusercontent.com/u/1139788?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ikeough](https://github.com/ikeough)**
_Monday Jun 22, 2015 at 23:42 GMT_

----

It's not a minus sign. It's the button that should only show up if you've wired up a revit element. When you click on that button in Dynamo for Revit, it takes you to the element in the view. It's obviously showing up when it's not supposed to.

**Comment by ZiyunShang** [comment]
Hi @mjkkirschner , can you reproduce this issue now? I just try it and don't see the minus symbol in custom node watch.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
