### ISSUE TITLE
View creation in python, batch process needed

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2173]
<a href="https://github.com/jbenoit44"><img src="https://avatars1.githubusercontent.com/u/4572196?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jbenoit44](https://github.com/jbenoit44)**
_Thursday May 21, 2015 at 16:33 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/4544_

----

I have an issue with dynamo vhen i want to create 3D views from a python node. I remember that in 0.6.3 it was a blast. I was able to create hundreds in less than a minute. right now it take ages as it seems that dynamo regenerate Revit each time a view is created.

The node I use is available in Steamnodes package as Element.Create 3D Cropped view.

line used: b=View3D.CreateIsometric(doc, typeid)

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/ke-yu"><img src="https://avatars1.githubusercontent.com/u/2600379?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ke-yu](https://github.com/ke-yu)**
_Monday May 25, 2015 at 10:04 GMT_

----

@Randy-Ma , do you have any idea about this issue? is it because of transaction model?

**Comment by AndyDu1985** [comment]
Could you still reproduce it? If yes, could you provide the file?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
