### ISSUE TITLE
Getting Revit face reference fails for some element types

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2179]
<a href="https://github.com/andydandy74"><img src="https://avatars2.githubusercontent.com/u/3014437?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andydandy74](https://github.com/andydandy74)**
_Wednesday Feb 25, 2015 at 18:06 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/3821_

----

In order to get a Revit face reference from a selected face I have been using the following Python code:
`ref = face.Tags.LookupTag("RevitFaceReference")`
I think it was originally suggested to me by @pboyer when I was migrating my content to 0.7 last year.
I noticed today that this method actually does not work for all element types. To be more precise I tried to get a Revit face reference for a piece of geometry contained in a generic model family and the code above returned null. Now my question is: is this a limitation of the Revit API or does Dynamo treat some element types differently?

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/ikeough"><img src="https://avatars1.githubusercontent.com/u/1139788?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ikeough](https://github.com/ikeough)**
_Wednesday May 04, 2016 at 17:28 GMT_

----

@andydandy74 Is this still an issue?

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/dimven"><img src="https://avatars2.githubusercontent.com/u/7148394?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dimven](https://github.com/dimven)**
_Saturday Oct 22, 2016 at 08:17 GMT_

----

This is still an issue and it's even more pronounced now that the native "FamilyInstance.ByFace" node has been introduced. References are correctly added for system based elements ( walls, floors, ceilings, etc) but fail for faces of family instances. 

~~This is most likely  because each instance has its own geometry instance and the current method does not account for that.~~

![revit_2016-10-26_13-43-54](https://cloud.githubusercontent.com/assets/7148394/19717677/5c16bcea-9b94-11e6-9566-2462f27d8ce9.png)

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/mjkkirschner"><img src="https://avatars3.githubusercontent.com/u/508936?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjkkirschner](https://github.com/mjkkirschner)**
_Saturday Oct 22, 2016 at 15:13 GMT_

----

These tags are added in the geometry converter in the DynamoRevit repo I believe during element conversion. just more info.

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/dimven"><img src="https://avatars2.githubusercontent.com/u/7148394?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dimven](https://github.com/dimven)**
_Wednesday Oct 26, 2016 at 07:57 GMT_

----

Had another look. The problem seems to be limited to the face selection nodes (see image in previous post) because extracting all of the faces of an element correctly adds the appropriate references.

**Comment by AndyDu1985** [comment]
Could you provide an rvt sample file and dyn file? Thanks!

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
