### ISSUE TITLE
element.geometry unstable

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2184]
<a href="https://github.com/FMFuk"><img src="https://avatars1.githubusercontent.com/u/10216228?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [FMFuk](https://github.com/FMFuk)**
_Wednesday Dec 17, 2014 at 09:29 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/3435_

----

Hi all,

I place a AC components at the end point of a curve and normal to the curve,
use element.geometry or element.curve to get a list of lines/arcs which are containing
in that AC components, use curve.byjoiningCurve to form a profile shape.
The first time I press "run", curve and the profile are drawn at the right place.
But afterwards if i run again (no matter edit the program content or not), the curve is still
at its right place, BUT the profile goes to somewhere near 0,0 which is very likely 
to be the origin of the AC component family, no longer normal to the curve also, become
flat on XY plane.
Any hints to solve this ? I remember such things do not happen in 0.6 version.

Rgds
FM

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/RodRecker"><img src="https://avatars1.githubusercontent.com/u/7010618?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RodRecker](https://github.com/RodRecker)**
_Wednesday Dec 17, 2014 at 13:31 GMT_

----

@FMFuk Sorry to hear this is not working as expected. Which version of Dynamo are you using?

**Comment by ColinDayOrg** [comment]
<a href="https://github.com/FMFuk"><img src="https://avatars1.githubusercontent.com/u/10216228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FMFuk](https://github.com/FMFuk)**
_Wednesday Dec 17, 2014 at 23:37 GMT_

----

Thanks for your prompt reply
my current version is : 0.7.6.3427.

**Comment by ZiyunShang** [comment]
Hi @FMFuk , are you still experiencing this issue with the latest version of Dynamo?

**Comment by FMFuk** [comment]
Hi

This issue has gone, I’m now using Dynamo 2.02, no particular issue.

Thanks
