### ISSUE TITLE
Swept blend

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2195]
<a href="https://github.com/ivanilmatto"><img src="https://avatars2.githubusercontent.com/u/5256567?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ivanilmatto](https://github.com/ivanilmatto)**
_Sunday Mar 23, 2014 at 16:13 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/1346_

----

Hi all!
I need to create a swept blend:
- I have a curve
- I have a couple of profiles

Profiles are generic model families (I tried to place them manually, selecting them and the path curve and create form: it works as expected); I tried using both adaptive components and "standard" generic models: it works using both the methods.

The point is: is there any way to place, using dynamo, the two profiles at the right position with the right orientation?

I tried several different methods but I wasn't able to solve this issue.

is there anyone who can help me?

ciao!
Paolo

**Comment by AndyDu1985** [comment]
Could you provide a sample file?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
