### ISSUE TITLE
Custom Python Node crashing in Dynamo 2.0 - calling Revit API

### ISSUE THREAD

**Issue by jmussett2018** [DynamoDS/DynamoRevit#2216]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.1.5055 Dynamo Core

## Revit version

2018.3.1.2

## Operating system

Windows 10

## What did you do? 

Saved a script in 2.0 that was created in 1.3 (revit 2017). We are updating all our scripts essentially.

## What did you expect to see?

This script syncs and compacts by calling up the sync dialogue in the Revit API and inputs a yes or no for the variable(s). We run it with automation software at night.

## What did you see instead?

The dynamo script says it ran with success but the time stamp on the file it was supposed to be saving doesn't change. If you right click edit the custom node and right click edit python, = Crashface bandaid guy.
Also including a snip of what the code looked like in 1.3.
![compact model crash](https://user-images.githubusercontent.com/44213067/47047052-3919f900-d15c-11e8-8d32-a81d582c3fe3.gif)
![r18 dyn 1 3 python code](https://user-images.githubusercontent.com/44213067/47047094-5222aa00-d15c-11e8-84eb-447bba060a6a.JPG)

**Comment by mjkkirschner** [comment]
Please attach the stack trace from the crash dialog, and the nodes in question if possible.

**Comment by mjkkirschner** [comment]
@jmussett2018 I also think this is likely to do with an addin conflict, can you please move to the latest version of pyRevit - do you have that installed?

**Comment by mjkkirschner** [comment]
please check what version of ironpython is installed on your machine under add/remove control panel.

**Comment by jmussett2018** [comment]
2.7.31

**Comment by mjkkirschner** [comment]
not sure yet if this is related but as a debugging step can you follow these steps?
https://github.com/DynamoDS/Dynamo/wiki/Dynamo-FAQ#ironpython

you may also want to try removing pyRevit just as a debugging step.

**Comment by jmussett2018** [comment]
Ok, I temporarily moved pyrevit. That seemed to prevent a crash. This script didn't do what is is written to do, open a local copy of a file, sync it and compact it. So I guess I'm back to my hunch that python is incorrectly calling up the Revit API.
