### ISSUE TITLE
View.ExportAsImage

### ISSUE THREAD

**Issue by arquicol** [DynamoDS/DynamoRevit#2221]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
2.0.1
## Revit version

(Which version of Revit are you using?)
2019
## Operating system

(e.g. Windows 7, Windows 8.1, etc)
Windows 10
## What did you do? 

(Fill in here)
use View.ExportAsImage in ENU and ESP versions
## What did you expect to see?

(Fill in here)
An exported image 
## What did you see instead?

(Fill in here)
An error and no image
![2](https://user-images.githubusercontent.com/44247043/47120922-40add080-d236-11e8-84cd-023b0ee14a5a.JPG)
![1](https://user-images.githubusercontent.com/44247043/47120924-42779400-d236-11e8-984c-0c0a07a9f192.JPG)

**Comment by ksobon** [comment]
What's the problem here? It looks like it works on that second image.

**Comment by arquicol** [comment]
In the first image I'm using Spanish version of Revit. No image is generated

In the second image I'm using English version of Revit. Correct image is generated.

The code is the same, so there is a problem with the extraction of the image in the Spanish version of Revit

**Comment by ZiyunShang** [comment]
Hi @arquicol , are you still experiencing this issue with the latest Revit & Dynamo version?
If so, I hope you can provide files with this issue.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
