### ISSUE TITLE
Cannot place Select Phase node

### ISSUE THREAD

**Issue by sshowalterAMD** [DynamoDS/DynamoRevit#2223]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.0.1.5055
Dynamo Revit 2.0.1.5065

## Revit version

18.3.1.2
20180423_1000(x64)
2018.3.1

## Operating system

Windows 7 Professional 64-bit (6.1, Build 7601)

## What did you do? 

Attempted to place the "Select Phase" node into a script

## What did you expect to see?

The node to appear in the script workspace.

## What did you see instead?

The node did NOT appear. Any other node can be placed, but this particular node will not appear in the script. See attached log file. The bottom of the log shows several lines that appear each time I attempted to place the node. I have also tried to place this node without any custom nodes installed, but the issue still occurs.
[dynamoLog_b299cfdc-6f4d-4abe-991a-a7058ed95b12.txt](https://github.com/DynamoDS/DynamoRevit/files/2492709/dynamoLog_b299cfdc-6f4d-4abe-991a-a7058ed95b12.txt)

**Comment by mjkkirschner** [comment]
@alfarok did you write a test that verifies all dropdown nodes can be placed / loaded?

**Comment by mjkkirschner** [comment]
@ZiyunShang - this error appears to come from Revit when using a filtered element collector - do you think this node is written incorrectly or behavior may have changed in 2018?

https://forums.autodesk.com/t5/revit-api-forum/the-input-type-is-not-a-subclass-of-element/td-p/7028649

I have not had time to try to reproduce yet.

**Comment by ZiyunShang** [comment]
Hi @sshowalterAMD , I'm sorry that I'm late. Are you still experiencing this issue now? Could you provide your work files like Revit file, .dyn and .dyf files?

**Comment by sshowalterAMD** [comment]
@ZiyunShang - I am no longer experiencing the issue. It started functioning properly again awhile after my original post and I forgot to follow up on this. My apologies!
Unfortunately I can't remember exactly what fixed this. I don't think I reinstalled or did anything differently, so it may have been an update or something?
