### ISSUE TITLE
"Del" key does not delete nodes

### ISSUE THREAD

**Issue by teocomi** [DynamoDS/DynamoRevit#2237]
## Dynamo version

Core 2.0.1.5055
Revit 2.0.1.5065

## Revit version

19.0.0.405

## Operating system

Win 10

## What did you do? 

"Del" key does not delete nodes, I need to right click and click "Remove", seems to only happen in Revit 2019

**Comment by ksobon** [comment]
Did you update Revit to 2019.1? It's a known issue with the version 2019.0

**Comment by teocomi** [comment]
Thanks @ksobon , didn't find that when I searched.
Cheers
