### ISSUE TITLE
BUG - I cant Copy and paste with in Dynamo it does it in my revit window.

### ISSUE THREAD

**Issue by CallumHale** [DynamoDS/DynamoRevit#2244]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.0.1.5055
Dynamo Revit 2.0.1.5065

## Revit version

R 2019

## Operating system

Windows 10

## What did you do? 

Ctrl+C - Ctrl+V

## What did you expect to see?
Copy and paste node - didn't work
Copy and paste string text - didn't work

## What did you see instead?

It copied the previous element selected in revit and the copied and pasted for me to then place the element. Pain in the arse for repetitive coding with slight changes to the text.

**Comment by mjkkirschner** [comment]
please see:
https://github.com/DynamoDS/DynamoRevit/issues/2025
should be fixed in 2019.1
