### ISSUE TITLE
Delete button or any keyboard short cuts are not working 

### ISSUE THREAD

**Issue by DurgamPruthvi** [DynamoDS/DynamoRevit#2253]
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
2.01
## Revit version
2019
## Operating system
windows 10
## What did you do? 
I'm unable to use delete button or any key board short cuts
## What did you expect to see?
I want to use complete key board short cuts while working on dynamo

**Comment by mjkkirschner** [comment]
please see:
https://github.com/DynamoDS/DynamoRevit/issues/2244

**Comment by mjkkirschner** [comment]
https://github.com/DynamoDS/DynamoRevit/issues/2025
