### ISSUE TITLE
Hotkeys not functioning

### ISSUE THREAD

**Issue by jstoddart** [DynamoDS/DynamoRevit#2256]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.0.1.5065

## Revit version
Revit 2019

## Operating system
Windows 10.0.17134 Build 17134

## What did you do? 
Pressing hotkeys (eg. Delete, fn+Delete, Ctrl + C, Ctrl + V, etc)

## What did you expect to see?
Hot-key mapped functions (delete selected node, copy, paste, etc.)

## What did you see instead?
Nothing - hot keys are not functioning in Dynamo Revit (verified they work in Dynamo Core 2.0.1.5055). Functions can only be accomplished through context menu. Ctrl + drag does work for copying, but not Ctrl-C & Ctrl-V. Nodes can only be deleted by selecting and using pull-down menu, or right-clicking and deleting individually.

**Comment by mjkkirschner** [comment]
please see:
https://github.com/DynamoDS/DynamoRevit/issues/2253
