### ISSUE TITLE
FilterRule.ByRuleType takes number value and string parameter, when set as View Filter crashes Revit on manual filter edit.

### ISSUE THREAD

**Issue by ekkonap** [DynamoDS/DynamoRevit#2266]
## Dynamo version

1.3.2.2480

## Revit version

17.0.1158.0
20181011_1645(x64)
2017.2.4

## Operating system

Windows 10

## What did you do? 

In FilterRule.ByRuleType I put in a number value in the value port, and a string parameter type in the parameter port.

## What did you expect to see?

I expect to see an error message telling me that the value data type does not match the parameter type.

## What did you see instead?

After creating a View Filter via ParameterFilterElement.ByRules and running the script without warnings, I tried editing the created Filter manually. Upon selecting the Filter in the Filters Menu, Revit crashes, allowing me to save a recovery file and send an error report.

After changing the offending number value to a string value in my script, the problem did not repeat.

**Comment by ZiyunShang** [comment]
Hi @ekkonap , are you still experiencing this issue now? I think you can try the latest version of Revit & Dynamo.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
