### ISSUE TITLE
Dynamo and Insight in Revit

### ISSUE THREAD

**Issue by mcterry1337** [DynamoDS/DynamoRevit#2267]
I am running Dynamo 2.0.1 on Revit 2019.1 and I get this (see image below) after I run Dynamo and then try to run the latest version of Insight in Revit.

![image](https://user-images.githubusercontent.com/33162085/48808168-d4126f80-ecd4-11e8-8f52-93c69894f599.png)

The people at the Insight forums found what is causing the problem, which is rooted in Dynamo, (see link below) and I was hoping this could get fixed so then I don't to do their suggested work around.

https://forums.autodesk.com/t5/lighting-solar-analysis-forum/error-message/td-p/8088068

Thanks,
Matt

**Comment by ZiyunShang** [comment]
@mcterry1337 are you still experiencing this error on latest Dynamo version like 2.0.3 or 2.2.1?

**Comment by mcterry1337** [comment]
No, everything is fixed now.
