### ISSUE TITLE
Dynamo for Revit Crashes after browsing for the scripts in B360 Desktop Connector

### ISSUE THREAD

**Issue by archjahz** [DynamoDS/DynamoRevit#2268]
Dynamo Crashes when I access through BIM360 Desktop Connector in Explorer. 

## Dynamo version

Dynamo Core 2.0.1.5055 / Dynamo Revit 2.0.1.5065

## Revit version

Revit 2018.3

## Operating system

Windows 7

## What did you do? 

I tried to browse for my Dynamo scripts which is saved in B360. So I went from Manage>Dynamo>Browse>B360

## What did you expect to see?

Folders in Desktop Connector 

## What did you see instead?

"Dynamo Crash - Attempted to read or write protected memory. This is often an indication that other memory is corrupt" - and then some codes below. Also documented the whole thing here: [https://autode.sk/2DPrjJO](url)

![dynamo crash in b360](https://user-images.githubusercontent.com/33277039/48835262-b4ee0d80-edba-11e8-855e-623bb81b9384.JPG)

**Comment by AndyDu1985** [comment]
@archjahz Do you run Revit with Administrator authority?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
