### ISSUE TITLE
DynamoRevit 2.x Categories Dropdown Produces Inconsistent Results Between Revit versions

### ISSUE THREAD

**Issue by dimven** [DynamoDS/DynamoRevit#2281]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.x

## Revit version

Any two recent versions of Revit, e.g. 2018 and 2019

## Operating system

Windows 10

## What did you do? 
Steps to reproduce:
- start a 2.0 graph in Revit 2018
- Place a Categories node and choose Walls from the dropdown
- save the graph
- open Revit 2019
- load the graph
- the Categories node now points to something totally differeny

## What did you expect to see?

The exact same category selection between versions

## What did you see instead?

Something else

This happens because the dropdown is serialized as just and index integer in the JSON, where as built-in categories are not static between Revit versions.

I imagine one way to solve this is to store the current selection as both a string and an index.

**Comment by QilongTang** [comment]
@dimven Good suggestion! 

@AndyDu1985 @ZiyunShang @BogdanZavu @sm6srw Looking for your suggestion here, let's assume the index for all categories will always change, should we override the category dropdown to serialize the category name or element id whichever is more stable?

**Comment by dimven** [comment]
@andydandy74 just pointed out to me that this is a regression:
https://github.com/DynamoDS/Dynamo/issues/3055

**Comment by andydandy74** [comment]
Category name is not going to work across revit localizations. Use built in category name instead.

**Comment by andydandy74** [comment]
By the way - the ```Element Types``` node behaves the same way between Revit versions.

**Comment by dobriai** [comment]
@QilongTang Yes, as far as Categories go, the stable thing is the built-in ID and this is what should be serialized.
In general, for dropdowns, you want to remember built-in ids, when possible. For user-created stuff, of course, ids are no good - so there you remember strings, most likely. I am not sure how many dropdowns there are out there that fill up with user-created items, but Family Types are one such case. Materials another. Well types are also user-created.

**Comment by dobriai** [comment]
It is worse than just "inconsistent between versions". It is impossible now to even localize scripts for the same version, as lists are sorted in each language, so the index means nothing.
With the old, 1.3 XML format, things were not rosy either, but there at least the name was serialized, which could be translated for the target language.

**Comment by QilongTang** [comment]
Closing. This should be fixed in the coming DynamoCore + DynamoRevit 2.1.0 release.
