### ISSUE TITLE
Dynamo causes blanck quickbar

### ISSUE THREAD

**Issue by silverglow** [DynamoDS/DynamoRevit#2305]
## Dynamo version

Dynamo 1.0.0
## Operating system

Windows 10
## What did you do?

As soon as I have installed Dynamo, Revit 2016 R2 quickbar became blank and all the icons seems invisible. 
I have uninstalled Dynamo and since that everything is correct: quickbar returns always visible. 
I have checked my graphic card settings (NVIDIA settings),and my drivers are all updated.
I've tried 100% as DPI scale too.
I'm running Windows 10, Revit 2016 R2, NVIDIA GTX 950M.
## What did you expect to see?

Revit coloured quickbar, as it is normally using Revit 
## What did you see instead?

Installing Dynamo, Revit quickbar immediately becomes blank and all the icons seems invisible (if I pass over an icon I can see the description of the button, but I can’t see the icon!). If I switch the quickbar down, below the ribbon bar, I can see all the buttons running Dynamo, but I’d like to keep it on the top of the screen.
After I have uninstalled Dynamo and everything looks fine: quickbar returns always visible.

**Comment by ZiyunShang** [comment]
Hi @silverglow , do you still have this problem now?
BTW, since Revit 2020, Dynamo would be an internal addin, and need not be installed.

**Comment by AndyDu1985** [comment]
Please use the latest version of Dynamo For Revit. I will close this one, if it can reproduce with the latest version, I will reopen it.
