### ISSUE TITLE
StructuralFraming.Location does not work for structural columns but works for structural beams

### ISSUE THREAD

**Issue by marcellosgamb** [DynamoDS/DynamoRevit#2311]
StructuralFraming.Location does not work for structural columns but works for structural beams

**Comment by ZiyunShang** [comment]
Hi @marcellosgamb , is this fixed? Your file link is invalid now, I can't reproduce this issue now.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
