### ISSUE TITLE
saving while crashing erases file

### ISSUE THREAD

**Issue by ghost** [DynamoDS/DynamoRevit#2312]
I was working on a dyn that entered into a particularly long calc. I had already saved the file, so I wasn't worried about force-quitting. when I went to "end task," dynamo was responsive and brought up "do you want to save" - I didn't think anything of it, hit yes, and now my entire file has been overwritten by an empty one. This makes me very sad.

:'(

**Comment by ZiyunShang** [comment]
Hi @aaron @mjkkirschner , could you take a look at this issue? Is there an autosave in Dynamo now?

**Comment by QilongTang** [comment]
@ZiyunShang 
1. You @ the wrong Aaron
2. There is auto save now, if you open Dynamo with Console opened, you should see such message periodically indicating your backup has been saved
![image](https://user-images.githubusercontent.com/3942418/61884956-0ced8e80-aecb-11e9-880c-b9642ce43103.png)

**Comment by ZiyunShang** [comment]
OK, I will close this issue.
