### ISSUE TITLE
Create Project Parameter node input

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/DynamoRevit#2315]
I add this topic as an issue... @mjkkirschner suggested to move it here.
https://forum.dynamobim.com/t/create-project-parameter-from-shared-parameter/29631/4

what seems to be worse is that the option "groupName" in the CreateProjectParameter node gives the user errors. I can only confirm that this is the case in my tests...
https://forum.dynamobim.com/t/create-project-parameter-from-shared-parameter/29631

It is strange that the node CreateProjectParameter has an input for groupName, since this does not apply with how to add a project parameter.

In my package I have a node alike yours, but in mine I dont have the "groupName" option since it doesn’t make sense… either you add a shared parameter or you add a project parameter, even though it in the background uses the same method… namely adding a parameter as shared parameter.

below is my nodes...
![parameter](https://user-images.githubusercontent.com/2844374/50099866-639d3680-021f-11e9-9992-e51ce2601dae.png)

**Comment by mjkkirschner** [comment]
looking a bit closer now, I think there are two issues:
* the user has a graph which when re-opened, does the *classic deserialize incorrectly and adds more outputs which will return null* thing.
* the node confuses the idea of project parameters and shared parameters.

**Comment by DonniaT-H** [comment]
I tried to use the Parameter Groups node but it kept duplicating the out. Using a code block like I saw here worked. Anyone seen that duplication in an out before?
![duplicate out](https://user-images.githubusercontent.com/58597506/72276712-95d5bf00-35fe-11ea-8dc8-0656a2f16421.jpg)

**Comment by FalconStarFighter** [comment]
Is there any way to specify between shared and project parameters.  Using the create project parameter node, I still get shared parameters as a result.  This prevents the use of these added parameters in a key schedule.
![Project Parameter node results in shared parameter](https://user-images.githubusercontent.com/61020227/79367919-78690780-7f03-11ea-9532-fd1431eaab47.JPG)

**Comment by erfajo** [comment]
If it is a dynamo node issue, then I am sorry that I interfered. However, if the issue goes on nodes in the Orchid package, then please address these issues at https://github.com/erfajo/OrchidForDynamo/issues
