### ISSUE TITLE
Dynamo percentage of a surface and list

### ISSUE THREAD

**Issue by Lainee03** [DynamoDS/DynamoRevit#2319]
Hello Everyone.

I'm having trouble finding how i can do this.
I have a number that corresponds to the % of a large surface (it's a variable) and i have a random list of all the little surfaces that creates the large surface.
Now i want the sum value of X items in the list to be below or equal to the % of the large surface.

for exemple in my screenshot my % result is 112.75m²
If i do the sum of 55 values in my list and it's equal to 114m², how can i do a new list with only the first 54 items
Any advice ? what componant i should take
![1](https://user-images.githubusercontent.com/38813068/50403710-2d246600-07a1-11e9-9596-97a014ad437d.JPG)

**Comment by mjkkirschner** [comment]
Try asking this on the forum,
