### ISSUE TITLE
Error in creating an Excel file from family instance location

### ISSUE THREAD

**Issue by nissal11** [DynamoDS/DynamoRevit#2327]
## Operating system
Windows 10 x64

## What did you do? 

Im trying to make an excel file of spot coordinates of model elements(mainly assets).
I had reached to file one phase of generating XYZ coordinates in Watch node.

## What did you expect to see?

I want to make an excel file from watch node which shows XYZ coordinates.

## What did you see instead?

I can now one error and one warning. 
Next part of creating an excel, im putting a value in string node but it is not generating. I had typed in variables like x, X, projectPosition.EastWest, EastWest, .EastWest, Name, East, x= projectPosition.EastWest.

![doubt1](https://user-images.githubusercontent.com/46665049/51097160-fcf04600-17e7-11e9-9f39-b22f26591bb1.jpg)
![doubt2](https://user-images.githubusercontent.com/46665049/51097163-0083cd00-17e8-11e9-9298-6ddc457ea60a.jpg)

[Family instance location without excel.zip](https://github.com/DynamoDS/DynamoRevit/files/2754049/Family.instance.location.without.excel.zip)

I dont know how to proceed further. Please put your valuable suggestion. It would be thoughtful.

**Comment by ZiyunShang** [comment]
Hi @nissal11 , I think this isn't a bug report or improvement request, you could go to the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
