### ISSUE TITLE
FamilyInstance GetSolids bug

### ISSUE THREAD

**Issue by ekkonap** [DynamoDS/DynamoRevit#2331]
## Dynamo version
1.3.2.2480 - 2.0.2.6833 

## Revit version
16.0.1185.0 - 19.1.0.112

## Operating system

Windows Server 2016 Standard version 1607 build 14393.2759

## What did you do? 

Selected a Family Instance in an empty project from a 'none' template, retrieved its Solids: Revit.Element.Solids(element)

## What did you expect to see?

I expected to see the Family Geometry as it is generated in Revit: a slab with a hole in it.

## What did you see instead?

I saw the hole closed on one side with 2 Faces, one the size of the outer sketch loop, one the size of the inner sketch loop, intersecting. Cutting the larger Surface with the smaller Thickened Solid from the smaller Surface generates an error: Warning: Solid.Difference operation failed. 
Unable difference two Solids : INCONS_FACE -- inconsistent face-body relationships

With more complex shapes, the errors in the generared Solids differed as well, but upon cutting with a Solid always resulted in the same error.

Attache: dyn, rfa, png

[FamilyGeometryBug.zip](https://github.com/DynamoDS/DynamoRevit/files/2778493/FamilyGeometryBug.zip)

**Comment by ZiyunShang** [comment]
Hi @ekkonap , I think you could use the latest version of Revit & Dynamo. It works fine now.
![FamilyGeometryBug_2019-07-17_03-21-23](https://user-images.githubusercontent.com/33445445/61355363-cc788a00-a8a6-11e9-8093-ee459a863050.png)
