### ISSUE TITLE
UseHardwareAcceleration flag ignored when Dynamo launched from within Revit

### ISSUE THREAD

**Issue by dimven** [DynamoDS/DynamoRevit#2333]
## Dynamo version

2.0.x

## Revit version

Revit 2018 / 2019

## Operating system

Windows 10 1803

## What did you do? 

Launch Dynamo4Revit and try to load a large graph

## What did you expect to see?

The graph

## What did you see instead?

When I launch Dynamo 4 Revit with a large graph, it instantly crashes together with Revit.

I'm ruining this on a laptop with HD4000 integrated GFX, Not sure if this is the case, but there seems to be an outgoing bug with Intel drivers and WPF hardware acceleration. I can see in the logs that WPF hardware acceleration is used even tho I've set the `UseHardwareAcceleration` flag inside `DynamoSettings.xml` to false. Interestingly, when I open the same graph in sandbox, it seems to load and work fine.

Weirdly, if you just rename the exact same file, everything works fine once again. It's as if the rename clears some internal cache that got corrupted. I'm open to suggestions but if this is some Intel thing and there's nothing that can be done at least there's a record of it now.

**Comment by mjkkirschner** [comment]
Hi @dimven - what file are you referring to in this part of your message:
`Weirdly, if you just rename the exact same file, everything works fine once again.` ?

**Comment by dimven** [comment]
If I rename the graph that is crashing everything and try again, everything behaves.

**Comment by mjkkirschner** [comment]
That’s ... surprising - once renamed are you opening it from the same location? Do you have any other extensions running ?
Does it crash immediately? Have you tried disabling backup save?

**Comment by dimven** [comment]
Same location, crashes almost immediately after you drag the graph in or use the open dialog. Will record it next time it happens.

**Comment by dimven** [comment]
Ok, this appears to be not driver related at all. We can now replicate this consistently on multiple systems. It seems to be a problem with the web-library in 2.0. Disabling the library view extension stops the crashes.

**Comment by mjkkirschner** [comment]
@dimven thanks. Would you be able to test master branch on your systems and see if it's fixed there? I believe it will be.

**Comment by mjkkirschner** [comment]
I think you'll have to test in DynamoRevit for a real testing scenario as the packages will not all load in sandbox and the issue is caused when many packages are loaded at once.

**Comment by dimven** [comment]
"many" is a subjective term :) I'd wager I have a lot less packages installed in 2.0 than 1.3 and that always worked fine minus the CEFsharp library. I don't think I have time to build the repo but maybe there's a daily build I can try?
