### ISSUE TITLE
How to get a wall reference 'point' / 'perpendicular edge'

### ISSUE THREAD

**Issue by MarkAckerley** [DynamoDS/DynamoRevit#2334]
## Dynamo version
2.0.2

## Operating system
Windows 10

## What did you do? 
Tried to dimension at a junction of 2 walls which were not perpendicular

## What did you expect to see?
To get a reference Point at the junction (the faces were not perpendicular to the dimension so they could not be used)

## What did you see instead?
Only to get references as a face (or to lookup the face 'tag')

![image](https://user-images.githubusercontent.com/41670424/51533724-9bf5ed00-1e3b-11e9-8fe4-b1b81ae376b7.png)

In Revit I can dimension from a point like this...
![image](https://user-images.githubusercontent.com/41670424/51534054-9351e680-1e3c-11e9-8895-1bd7ce5e0791.png)

There is some related discussion here... https://github.com/DynamoDS/Dynamo/issues/1704#issuecomment-45152511
Though this topic was not deemed a Revit issue.  It would be helpful to have an explanation of the difference.

**Comment by AndyDu1985** [comment]
You can use python to implement a node to solve this issue. How to use Revit API, you can refer to https://forums.autodesk.com/t5/revit-api-forum/create-dimension-between-two-points/m-p/7842430#M29359.

**Comment by MarkAckerley** [comment]
Hi,

Thanks for your input.

Yes I can get the end point reference of a line, but what I need is the end point of a wall, as I am able to do in Revit.  

If I write a Python code to extract the end point reference from the wall location I get nulls (perhaps I am doing something wrong) but more importantly, the end point of the location line is not in the same place as the end point of the wall.

![image](https://user-images.githubusercontent.com/41670424/53631598-cdb45d80-3c0a-11e9-82d4-ffb5af22d5a7.png)

Therefore even this work around would not provide a satisfactory outcome.

Thanks again,

Mark

**Comment by AndyDu1985** [comment]
You can get the location line and get the structure layer from wall type, then do some calculation, but this maybe a little complex. 
You can post this issue to Dynamo Forum: https://forum.dynamobim.com/

**Comment by AndyDu1985** [comment]
Close this issue as it is about how to use Dynamo, not a defect or a new requirement.

**Comment by MarkAckerley** [comment]
Hi,

Thanks for the response.

Unfortunately your statements demonstrate that you do not understand the issue.  

To Close the issue due to a mistaken belief that it is about 'how to use Dynamo' does not solve the issue,  so Dynamo development does not move forward.

> You can get the location line and get the structure layer from wall type, then do some calculation, but this maybe a little complex.

This is what I demonstrated above, I also noted that it misses the point of the Issue.  

I am not after a static point, I am after the same dynamic Reference as I retrieve in Revit, the end 'point' / 'vertical edge viewed in plan' reference of the wall geometry .

Thanks,

Mark

**Comment by AndyDu1985** [comment]
![2019-07-24_1556](https://user-images.githubusercontent.com/10704909/61776058-c9444780-ae2c-11e9-956c-0d25ec0079c7.png)
![2019-07-24_1556_001](https://user-images.githubusercontent.com/10704909/61776063-cba6a180-ae2c-11e9-843b-0a54dd666afd.png)
I create a dimension like this, and use RevitLookUp to look into its data. Is this the dimension you want? Do I miss anything?

**Comment by MarkAckerley** [comment]
Hey, that's it...

If you can do that in Dynamo, that would be awesome :D

**Comment by AndyDu1985** [comment]
It is about how to find the corresponding reference to create a dimension.

**Comment by MarkAckerley** [comment]
It is about how we access that reference through Dynamo.

RevitFaceReference fails? Could you describe your method?

**Comment by MarkAckerley** [comment]
Ok, so I had a think about it and realise that what I was getting was a not a Point, but a Vertical Edge Referece viewed in Plan.

This can be easily extracted from the Element Geometry.

So I am closing this topic.

Thanks,

Mark
