### ISSUE TITLE
Dynamo 2.0.2 does not save "Category" and "all elements of category" nodes

### ISSUE THREAD

**Issue by Mjeronimobarbosa** [DynamoDS/DynamoRevit#2338]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

dynamo 2.0.2
revit 2018
Windows 10 pro

## What did you do? 

This nodes disappear from my script, does not save with save as. Tried a new file just with this nodes and it did not save again.

**Comment by ZiyunShang** [comment]
Hi @Mjeronimobarbosa , could you provide your work flow to show the case you described? Or could you try to use the latest Revit & Dynamo version instead?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
