### ISSUE TITLE
"Structural Framing Type" node changing selection to random while using Dynamo Player. 

### ISSUE THREAD

**Issue by Dutchnesss** [DynamoDS/DynamoRevit#2339]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.2

## Revit version
2019.2

## Operating system

Windows 10

## What did you do? 

Using the "Structural Framing Types" node, selecting the type I want, works great. 

## What did you expect to see?

Continued use through the Dynamo player for multiple projects

## What did you see instead?

I noticed at some point dynamo changed the values I selected as the types in the dropdown selection of the Structural Framing Types node. This didn't throw an error, just simply "chose a different type". Frankly really dangerous, glad I found it when I did. 

[Auto-Size Selected Beams by Length (Multiple Inputs).zip](https://github.com/DynamoDS/DynamoRevit/files/2797737/Auto-Size.Selected.Beams.by.Length.Multiple.Inputs.zip)

**Comment by mjkkirschner** [comment]
What is the name of your selected structural type?

This should be fixed in the next version of Dynamo:
https://github.com/DynamoDS/DynamoRevit/issues/2281
