### ISSUE TITLE
RFI: Dynamo-Revit Geometry display

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#2340]
@mjkkirschner @aparajit-pratap I have a query: what geometry engine does Dynamo use to render geometry objects in the Revit display? Is this library available to third parties? I am looking to do something similar (diagnostics display of data attached to elements) and want to know whats possible.

**Comment by aparajit-pratap** [comment]
@ThomasMahon I think we use Revit transient geometry display API's to draw transient geometry to display in the Revit background preview: `Autodesk.Revit.DB.GeometryElement.SetForTransientDisplay()`. This should be available in the Revit API. You might want to refer to this code: https://github.com/DynamoDS/DynamoRevit/blob/c0ec8251b98124c668624862b54a7f3bd740159f/src/DynamoRevit/ViewModel/RevitWatch3DViewModel.cs#L126
For more information maybe @QilongTang can put you in touch with the right folks from the Revit team.
