### ISSUE TITLE
Basic nodes (exp.: Boolean) are UNRESOLVED!

### ISSUE THREAD

**Issue by lucky117** [DynamoDS/DynamoRevit#2355]
## Dynamo version 

RevitDynamo 2.0.2.

## Revit 

Revit 2019.2

## Operating system 

Windows 10

## What did you do? 

Nothing special, one day the basic nodes are UNRESOLVED without any reason...

## What did you expect to see?

Standard nodes are normally functional, without any problem. Printscreen from college’s computer. 

![standardnodes](https://user-images.githubusercontent.com/15686929/53636401-66a1a380-3c20-11e9-9158-c9ec48ea7e5c.png)

## What did you see instead?

Same version of Revit and Dynamo, same script but different behaviour. Basis nodes like “File Path” or ”Boolean” are UNRESOLVED. I’m using RevitDynamo (not Revit sandbox). Can somebody tell me where is the problem? It seems the basis library is somehow corrupted. Can you help me?

![standardnodes_unresolved](https://user-images.githubusercontent.com/15686929/53636357-35c16e80-3c20-11e9-8303-a18189f231e8.png)

**Comment by mjkkirschner** [comment]
Hi @lucky117 I would try removing all packages and add them back one by one.

* did you recently install any new packages?
* do you see any green notifications in the dynamo menu bar?
