### ISSUE TITLE
2018 - 2019 incompatibility

### ISSUE THREAD

**Issue by alfonsomonedero** [DynamoDS/DynamoRevit#2358]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.1
## Revit version

2018.3 and 2019

## Operating system

Windows 10
## What did you do? 

Open a dyf file with out of the boxes

## What did you expect to see?

The graph should work for both 2018 and 2019 revit

## What did you see instead?

Same script opened in Revit 18 and 19 is missing basic boxes (Python, collect elements, categories…), same happens to custom nodes. In 2018 the python boxes inside nodes disappear. 

![18-19](https://user-images.githubusercontent.com/43339587/53750234-1edd7f00-3ea1-11e9-9495-a5903182b748.jpg)

**Comment by mjkkirschner** [comment]
@alfonsomonedero please try uninstalling pyRevit... I think something odd is going on when pyRevit built targeting .net 4.7.1 is loaded into revit 2018 and older.

**Comment by mjkkirschner** [comment]
also, please list other addins you have installed in 2018?

**Comment by alfonsomonedero** [comment]
@mjkkirschner I have RevitPythonShell, Pyrevit, Ideate software, RTV xporter. I definitely think it is RevitPythonShell or Pyrevit, but I really need Pyrevit so I hope there is a work around. It worked well at the beginning but lately these boxes are disappearing.

**Comment by mjkkirschner** [comment]
apparently this has been fixed with latest built of pyrevit, please reopen if you still see the issue.
