### ISSUE TITLE
Node Error After Saving, Closing, and Re-Opening a Script

### ISSUE THREAD

**Issue by coverholt** [DynamoDS/DynamoRevit#2359]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.2

## Revit version

2018 and 2019

## Operating system

Windows 10

## What did you do? 

Added different nodes, such as 'All Elements of Model Category' and 'Links'... Saved the file... re-opened the file later.

## What did you expect to see?

One output connection from the nodes.

## What did you see instead?

An added output connection for each time the file is opened.
![node error](https://user-images.githubusercontent.com/48330828/53980081-6b150300-40dd-11e9-870e-f61153b34f00.jpg)

**Comment by QilongTang** [comment]
@mjkkirschner @alfarok I remember our team has seen similar issue to happen because of NewtonSoft.Json conflict? Because this seems like a deserialization failure to me

**Comment by alfarok** [comment]
@QilongTang Yeah, I usually encounter this when a NodeModel derived node is missing a Json constructor.

**Comment by mjkkirschner** [comment]
or if something else has loaded an incompatible version of json.net - please search the forum or issues for this same issue.

**Comment by mjkkirschner** [comment]
https://forum.dynamobim.com/t/dynamo-2-0-duplicates-ports-of-custom-node-when-file-is-saved-and-reopened/20867/4

**Comment by MarcSp74** [comment]
thanks for the link, but I really don't know what to do.
Seems a lot of people had this issue posted, but a clear and simple answer how to fix I cannot find.
the only thing I can imagine and tried is reinstalling the package, but that doesn't help.
Should I uninstall en reinstall Revit and Dynamo and al of its components? Does that help? I prefer not as you hopefully can understand.

**Comment by mjkkirschner** [comment]
@MarcSp74 `something else has loaded an incompatible version of json.net` - it's likely some addin you have installed in Revit.
