### ISSUE TITLE
Cannot use ctrl+s to save .dyn file

### ISSUE THREAD

**Issue by lxmfly123** [DynamoDS/DynamoRevit#2362]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.2

## Revit version

(Which version of Revit are you using?)

Revit 2019.0

## Operating system

Windows 7

## What did you do? 

Use ctrl+s to save the editing .dyn file.

## What did you expect to see?

The .dyn file should be saved.

## What did you see instead?

The host .rvt file was saved.

**Comment by andydandy74** [comment]
Pretty sure this is related to https://github.com/DynamoDS/Dynamo/issues/8751 which would make it a Revit issue that can be solved by upgrading to 2019.0.1 or higher.

**Comment by lxmfly123** [comment]
Thanks to @andydandy74 ,
