### ISSUE TITLE
Node: Category by Name not working with MEP-Räume (Spaces)

### ISSUE THREAD

**Issue by dakeret** [DynamoDS/DynamoRevit#2364]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
V2.02

## Revit version
Revit2018.3 (German)

## Operating system
Windows 10

## What did you do? 
Using the Node CategoryByName to get the Category: MEP-Räume (Spaces)
The German Input of Spaces is MEP-Räume. The Node only works with the English Word but not with the German translation. 

## What did you expect to see?
the Categorie MEP-Räume

## What did you see instead?
Null

**Comment by ZiyunShang** [comment]
Hi @dakeret , I have resolved this bug by PR https://github.com/DynamoDS/DynamoRevit/pull/2404 yet.
