### ISSUE TITLE
Revit and Dynamo freezed because of Tag Leader Type

### ISSUE THREAD

**Issue by kachuncho** [DynamoDS/DynamoRevit#2372]
## Dynamo version

Dynamo Core 2.0.1.5055
Dynamo Revit 2.0.1.5065

## Revit version

2019

## Operating system

Windows 10

## What did you do? 

In Automatic Mode
I created a python nodes.
used
`tag.LeaderEndCondition = tag.LeaderEndCondition.Free`
for getting the position of LeaderEnd

and used
`tag.LeaderEndCondition = tag.LeaderEndCondition.Attached`
at the end to make the leaderEnd attach back to object

## What did you expect to see?

The Tag leaderEnd Condition remain Attached

## What did you see instead?

Dynamo and Revit freezed so I have to force closed them.
I need to change to Manual mode so it can run

**Comment by ZiyunShang** [comment]
Hi @kachuncho , could you provide a workflow including dynamo script to show the case you describe?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
