### ISSUE TITLE
Dynamo 2.0.2 won't expand in Revit 2018.3 or Revit 2019.2

### ISSUE THREAD

**Issue by TheBIMsider** [DynamoDS/DynamoRevit#2373]
## Dynamo version 
2.0.2 in Revit 2018.3 & 2019.2
## Operating system 
Windows 10
##What did you do? 

Just tried to open Dynamo 2.0.2 in Revit. Once I see the Dynamo window (startup page) open I try to expand it to full size and I get a crash screen. Id I just try and adjust the size of the dynamo screen at all I get the crash screen. If I don't change the size of the Dynamo window I can open a graph, but when I do there is no Library visible?

Exact same thing in 2019.2 as in 2018.3

Both versions fo Revit work fine with Dynamo 1.3.4

Extra Info:
I have Revit 2020 installed with Dynamo 2.1
I have Civil 3D 2020 installed with Dynamo 2.1
I have Advanced Steel 2020 Installed with Dynamo 2.1
I have FormIt Pro V17.1 installed with Dynamo 2.1

I have Dynamo Core and Revit 1.3.4 installed

## What did you expect to see?

See above

## What did you see instead?

See Above

## Pictures

![2019-04-24_19-37-59](https://user-images.githubusercontent.com/37883693/56704177-675b3100-66c9-11e9-9379-663d31ba3187.png)

![2019-04-24_19-37-19](https://user-images.githubusercontent.com/37883693/56704185-6de9a880-66c9-11e9-81aa-6ef15aa4608f.png)

![2019-04-24_19-35-44](https://user-images.githubusercontent.com/37883693/56704195-70e49900-66c9-11e9-9624-c5a2994399e0.png)

![2019-04-24_19-36-39](https://user-images.githubusercontent.com/37883693/56704199-75a94d00-66c9-11e9-8130-5facd625dab8.png)

**Comment by mjkkirschner** [comment]
@TheBIMsider did you install an older daily build of 2.1 which installed globally on your machine? Please uninstall it if so.

Can you share your control panel showing installed DynamoCore versions?

**Comment by mjkkirschner** [comment]
@TheBIMsider ... did you do something like copy the 2.1 dlls into the ProgramFiles/DynamoCore 2 folder?

<img width="1178" alt="Screen Shot 2019-04-24 at 10 11 42 PM" src="https://user-images.githubusercontent.com/508936/56705262-43eeb100-66de-11e9-8d4d-45b5f7a6a5af.png">


I also have 2.1 / 2020 installed.

**Comment by TheBIMsider** [comment]
Hey @mjkkirschner it was a Dynamo Core 2.1 that was installed.

When I removed that in installed the Dynamo Core 2.0.2 again all worked

I installed Advanced Steel 2020 and the Dynamo Add-in for it, and that is what installed the Dynamo 2.1 core. It seems to be the only 2020 product that does not have Dynamo 2.1 incorporated within the main program. So it looks like Advanced Steel 2020 with the Dynamo Add-in can't be installed with Dynamo 2.0.2?

**Comment by mjkkirschner** [comment]
I believe advanced steel is the cause - looking into this now. Thanks for reporting it. 👍

**Comment by QilongTang** [comment]
@TheBIMsider Can I invite you to post the workaround in our forum at https://forum.dynamobim.com/? I think what you have experienced should help others as well. Thank you for reporting.

**Comment by TheBIMsider** [comment]
> @TheBIMsider did you install an older daily build of 2.1 which installed globally on your machine? Please uninstall it if so.
> 
> Can you share your control panel showing installed DynamoCore versions?

**Comment by TheBIMsider** [comment]
I have posted this in the Dynamo Forum

https://forum.dynamobim.com/t/dynamo-2-0-2-wont-expand-in-revit-2018-3-or-revit-2019-2/35196/2
