### ISSUE TITLE
category mapping when changing language

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/DynamoRevit#2374]
## Dynamo version
2.02

## Revit version
2019

## Operating system

win10

changing from german revit to english revit
loading a definition file
the listed categories  (node categories) are not mapped to the respective english category
for example:
german "Körper" should map to "mass" but is mapped to "lines - Hidden Lines"

**Comment by ZiyunShang** [comment]
Hi @epeter- , this issue has been fixed. You can refer to DynamoDS/Dynamo#9367 DynamoDS/Dynamo#9386 #2324
