### ISSUE TITLE
Parameter.CreateSharedParameter Invalid Type Parameter Errors Issues

### ISSUE THREAD

**Issue by mfleming04** [DynamoDS/DynamoRevit#2376]
## Dynamo version
2.0.2.6833

## Revit version
Revit 2018.3

## Operating system
Windows 7

## What did you do? 
Feed in a list of data from excel to create new shared parameters.  This works fine for "Text", "Length".  Tried anything that has DataType with an Underscore like "Mass_Density" does not get added.

## What did you expect to see?
All parameters created

## What did you see instead?
Invalided Parameter Type

- If you use "TEXT" vs "Text" it will fail.  Node should ignore case.   When trying to rebuild our SP, I'm using existing SP File inside excel and defaults are uppercase.

- So far I'm not able to use type "Mass_Density" or "MASS_DENSITY", also "MASS_PER_UNIT_AREA" and a few others.  I'm guessing the underscore in the DataType name is causing issues?

**Comment by mfleming04** [comment]
Using the "Select Parameter Type" Node, worked making "MASS_DENSITY" = **MassDensity**
Still would be good to **ignore case** and follow the API option using the **default underscore**.

**Comment by AndyDu1985** [comment]
@mfleming04 Could you provide a dyn file to show the case you describe?

**Comment by AndyDu1985** [comment]
Will reopen if more information provided.
