### ISSUE TITLE
Dynamo 2.0.2 Crashes every time I try to to map it to existing Packages

### ISSUE THREAD

**Issue by TheBIMsider** [DynamoDS/DynamoRevit#2378]
## Dynamo version

2.0.2 - Core & Revit

1.3.4 is also installed (Core & Revit)
## Revit version

2018.3 & 2019.2

Revit 2020 is also installed

## Operating system

Windows 10

## What did you do? 

Every time I try to map an existing location for my Dynamo packages the program crashes without allowing the mapping to work.

I can get this far, but as soon as I hit "Accept" it will crash.

![2019-04-27_18-57-03](https://user-images.githubusercontent.com/37883693/56856778-06c53180-691f-11e9-9411-408ef42a0583.png)

If I create a new folder (same name same location) and download all the packages again then it works fine.

The "E" drive is a local drive on my laptop, which is an SSD drive with lots of storage space.

This has only been an issue since the Update to the Package Manager a few weeks back.

Note: The this process works as expected with Dynamo 1.3.4, even after the update to the package manager.

## What did you expect to see?

That the mapping would work and all my existing packages would be available

## What did you see instead?

Nothing program will crash

**Comment by mjkkirschner** [comment]
Please try 2.0.3 daily - there’s a hot fix for this issue.

**Comment by TheBIMsider** [comment]
Hello @mjkkirschner 

That seems to have done the trick.
