### ISSUE TITLE
TextNote.ByLocation appears to exceed the threshold of .NET GC probably due to unnecessary geometry window display, which consequently invalidates Revit Element output (reference object is not valid)

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#2383]
## Dynamo version
1.3.4+

## Revit version

2018-2020

## Operating system

Win 10

## What did you do? 

Created lots of text notes (1600) using OOTB TextNote.ByLocation

## What did you expect to see?

1600 text notes

## What did you see instead?

Nothing displayed in Revit and when querying the elements, say using OOTB Element.Name node, I get a "reference object is not valid" exception. Also, if I try and double-click the ID from the node watch window, it does noting:
![image](https://user-images.githubusercontent.com/18601851/57198516-9b591080-6f6b-11e9-8faf-9115b91cae3d.png)

If I limit the amount of elements, to say 100, it works as expected and the elements are created/visible in Revit:
![image](https://user-images.githubusercontent.com/18601851/57198471-0bb36200-6f6b-11e9-8992-0525fa8e3b0c.png)

If the geometry display is the cause (its going to be generating 100s of 1000s of protogeometry elements I assume), it cant be switched off, so can this feature be optional or removed completely?

**Comment by mjkkirschner** [comment]
Do you notice an improvement if you disable all previews?

We actually did remove this:
https://github.com/DynamoDS/DynamoRevit/pull/1827
and
https://github.com/DynamoDS/DynamoRevit/pull/1866

so if you still see this behavior in 2020 something else is likely going on.

**Comment by ThomasMahon** [comment]
Hi @mjkkirschner yep, switching off the preview fixes it. And my mistake with Revit 2020, basically this problem only affects Dynamo 1.3. Dynamo 2.0 works without issue, so I suppose thats where this feature was mothballed.

![image](https://user-images.githubusercontent.com/18601851/57200629-2f37d600-6f86-11e9-8fc4-d47ff1bca74d.png)
