### ISSUE TITLE
Element.Solids Unable to compute edge from curve

### ISSUE THREAD

**Issue by wassimj** [DynamoDS/DynamoRevit#2385]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.1.0

## Revit version
2010

## Operating system
Windows 10 (64bit)

## What did you do? 
Starting from the included Revit "Sample Architecture Project", I launched Dynamo from "Manage" and created the following graph:

Categories (and specified Rooms) ---> All Elements of Category ---> Element.Solids

## What did you expect to see?

3D Solids of the rooms (which sometimes they do appear)

## What did you see instead?

On a later run, this stopped working and instead, Element.Solids reported a warning:
"Warning: Element.get_Solids operation failed. Unable to compute edge from curve: NO_CUR_BB -- no current bulletin board exists"

<img width="1266" alt="DynamoRevitBug" src="https://user-images.githubusercontent.com/6302909/57213850-f3315f00-6fdf-11e9-9989-bbd0085cc165.PNG">

**Comment by ZiyunShang** [comment]
The DynamoRevit 2.1.0 was built with Revit 2020 API.Because of the changes in RevitAPI & RevitAPIUI, I don't think it supports the Revit 2010 version very well.
