### ISSUE TITLE
Wall.ByCurveAndLevels - No Top Constraint applied

### ISSUE THREAD

**Issue by torkuen** [DynamoDS/DynamoRevit#2388]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.2.6833

## Revit version

2019.2

## Operating system

Windows7

## What did you do? 

used Wall.ByCurveAndLevels

## What did you expect to see?

A wall with Bottom and Top attached to the levels provided

## What did you see instead?

Top is unconnected

![DynamoCreateWallByCurveAndLevels](https://user-images.githubusercontent.com/7558042/57696387-ef8d8000-7650-11e9-987f-714e88eca6a8.PNG)

**Comment by ZiyunShang** [comment]
That node Wall.ByCurveAndLevels can't attach top constraint due to Revit API. I think you can do as picture below:
![Wall-SetTopConstraint](https://user-images.githubusercontent.com/33445445/60255995-50bc9a80-9903-11e9-9951-b3ad8af819d7.png)
