### ISSUE TITLE
Simultaneous View Creation  

### ISSUE THREAD

**Issue by CunninghamL** [DynamoDS/DynamoRevit#2389]
## Dynamo version

Official Release 2.0.2 initially, I then tried daily build 2.0.3.8656 before I was sure of my issue.
(Reverting back to the official release did not work, the installer would not allow me to "downgrade")

## Revit version

Revit 2018

## Operating system

Windows 10

## What did you do? 

I attempted to create two plan views at the same time for parallel sections of my graph. 

## What did you expect to see?

I expected to see two newly created plan views.

## What did you see instead?

The view creation nodes had an empty output and did not turn yellow to indicate an error. 
![image](https://user-images.githubusercontent.com/49533190/58044936-ee979b00-7af5-11e9-8808-829887e8190c.png)
and 
![image](https://user-images.githubusercontent.com/49533190/58044980-0a9b3c80-7af6-11e9-9476-0469719d3d62.png)
^I am am still unsure why the level creation node had a similar issue but I have tested this issue on a fresh graph with the same results. 
![image](https://user-images.githubusercontent.com/49533190/58045109-606fe480-7af6-11e9-871c-98f6e13ced8c.png)
^Finished run 
![image](https://user-images.githubusercontent.com/49533190/58045243-b93f7d00-7af6-11e9-87a1-85837c1c960d.png)
^No views were created 

You may want to refer to my two posts on the Dynamo Forum for more context found here: [I’m having issues with transactions](https://forum.dynamobim.com/t/im-having-issues-with-transactions/36132)
and here: [Simultaneous View Creation Bug ](https://forum.dynamobim.com/t/simultaneous-view-creation-bug/36216)

**Comment by ZiyunShang** [comment]
Hi @CunninghamL , I couldn't reproduce this issue on my side. But I found there is a solution on forum https://forum.dynamobim.com/t/simultaneous-view-creation-bug/36216 :
![image](https://user-images.githubusercontent.com/33445445/60309813-64f3ac80-9982-11e9-99fe-6c21bcedb4c5.png)
I don't think this is a node issue, @QilongTang @mjkkirschner , Could you take a look at this?

**Comment by CunninghamL** [comment]
When you attempted to reproduce this graph were your run settings set to automatic?

This issue arises on manually ran graphs, on automatic graphs the view creation nodes will never have to run at the same time because they will simply execute in the order that you insert them. 

To develop and debug graphs of this size automatic runs are unfortunately not possible. 
![image](https://user-images.githubusercontent.com/49533190/60372520-afd8e880-99b1-11e9-9c1e-f55c3dcfd6c1.png)

I am aware of that workaround/solution because I posted it, thanks for looking into it though. :)

**Comment by mjkkirschner** [comment]
I don't think what you posted before is a "workaround" - that is a valid approach to order execution - Dynamo is a data flow programming language - it does not have control statements unless you use them in designscript imperative block.

You can also use function composition with custom nodes.

**Comment by CunninghamL** [comment]
That's fair, I guess there is no way to force the program to do two things at the same time when it wasn't intended to function that way. We just have to be aware to sequence certain nodes to avoid these hard to track errors.
