### ISSUE TITLE
Dynamo nodes not appearing

### ISSUE THREAD

**Issue by MrAlex8** [DynamoDS/DynamoRevit#2390]
## Dynamo version

![image](https://user-images.githubusercontent.com/45394203/58088483-ad1cf380-7bba-11e9-9fe9-2250a2484bfd.png)

## Operating system

Windows 10

## What did you do? 

Open a previous dynamo file

## What did you expect to see?

The dynamo graph

## What did you see instead?

Wires only

![image](https://user-images.githubusercontent.com/45394203/58088580-e8b7bd80-7bba-11e9-8b0c-e8aaf3c4cfd7.png)

**Comment by mjkkirschner** [comment]
what version of Revit is this? 
do you see any green notifications in the dynamo menu - Does a restart of Revit fix this?

**Comment by mjkkirschner** [comment]
Also are you using PyRevit or other addins, a first step is to disable them and see if the issue disappears - then identifying which is causing the conflict.

**Comment by MrAlex8** [comment]
Yes I had an out of date archilab package clashing with Speckle. All sorted now, thanks
