### ISSUE TITLE
Is Dynamo 2.1 still open source?

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#2392]
Hi Dynamo team. A qucik question: is Dynamo 2.1 still open source and will it continue to be open source now it is integrated into Revit? 

Can other versions of Dynamo be installed in Revit 2020?

**Comment by dimven** [comment]
I'm not sure why you'd think Dynamo4Revit is not open source any more. The current master branch seems to be targeting something beyond 2.2, there's RC (release candidate) branches starting from 2.2 and going all the way back to 0.8.

What's definitely changed tho, is that each version from 2.1 onward targets only the current latest version of Revit (and not two versions back), which is definitely a shame, because it further fragments the platform and alienates people with long-running projects.

**Comment by kronz** [comment]
Hi @ThomasMahon @dimven 
yep, Dynamo 2.1 is still open source and will continue to be. I think people are starting to conflate open source code and how it's being distributed.  We aren't building seperate installers for DynamoRevit anymore, and the distribution of supported versions of Dynamo in Revit are coming straight through the Revit release and point release process. You can read all about the reasons for this on these posts, but the essence is to insure high quality moving forward, stop creating confusion with multiple installs per machine, and stop creating disruption by having one version of Revit change the installed behavior of other versions of Revit.
https://dynamobim.org/dynamo-core-2-1-release/
http://help.autodesk.com/view/RVT/2020/ENU/?guid=GUID-A45F5AF9-6FCF-4F0C-90FA-309A964833B2

The code is open source, the ability of people to build and distribute versions and branches that they want to is still there. Revit is distributing a Dynamo "as a feature" of Revit, and like other features it, it provides the new functionality with the new versions of Revit. For example, the new Path of Travel tools in Revit 2020 have not been "back ported" to Revit 2019, and I don't think anyone expects them to be. Would that be cool?  Yes, for sure, but it comes at a cost (maintenance, testing, etc that could be used for other things), and would also further fragment the the platform ("are you on the version of Revit 2019 that has Path of Travel? No? Oh, then you can't use the version of 2019 that I have.") 

This is a change, to be sure. We did a lot of work in the past to have every version of Dynamo working on 3 releases of Revit at once. We are chosing a path of dependability, consistency, and reliability at the expense of ubiquity. But the code itself is still open, and we've got no plans to stop.
-Z

**Comment by ThomasMahon** [comment]
Thanks, thats good to know. So I take it if I want to customise v2.1 and install it in Revit 2020 there are no issues?
