### ISSUE TITLE
ElementFilter.ByCategory Dereferencing a non-pointer

### ISSUE THREAD

**Issue by shnlmn** [DynamoDS/DynamoRevit#2403]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.3

## Revit version

2019

## Operating system

Windows 10

## What did you do? 

Connecting 'Categories' and 'Select Model Elements' to filter out Grids.
![2019-06-28 10_44_46-Dynamo](https://user-images.githubusercontent.com/11766000/60361010-f28ac880-9991-11e9-8833-a61e1e62cc2d.png)

## What did you expect to see?

Elements from 'Select Model Elements' filtered to only show Grids Elements. 
This script has worked for several days before this.

## What did you see instead?

Error:
![2019-06-28 10_47_26-Dynamo](https://user-images.githubusercontent.com/11766000/60361071-24039400-9992-11e9-99d9-bbf2f6a01f56.png)

**Comment by ZiyunShang** [comment]
Hi @shnlmn , this node ElementFilter.ByCategory is a custom node in Rhythm package. I think we couldn't do something about this.
