### ISSUE TITLE
Automatically fill the Floor Finish, Wall Finish and Ceiling Finish in the Rooms schedule

### ISSUE THREAD

**Issue by amratiya2002** [DynamoDS/DynamoRevit#2405]
## Dynamo version 

Version 2.0.3.0

## Revit version

Revit 2019

## Operating system

Windows 10

## What did you do? 

The main idea is to automatically fill the Floor Finish, Wall Finish and Ceiling Finish in the room schedule from modeled Floors, Walls and ceilings (Name or Finish of the element).

**Comment by ZiyunShang** [comment]
Hi @amratiya2002 , is there any problem when you do your work? I think you can go to Dynamo Forum (https://forum.dynamobim.com ) for help if your question is about how to use DynamoRevit.
