### ISSUE TITLE
Rhynamo and clockwork crashes with Dynamo 2.1

### ISSUE THREAD

**Issue by bimxl** [DynamoDS/DynamoRevit#2409]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.1.0.7500

## Revit version

2019

## Operating system

Windows 7

## What did you do? 

open a definitions/script prepared in dynamo 2.0 and containing custom nodes from packages (clockwork and Rhynamo). I was trying to import Rhino mesh to Revit and build floor in Revit. 

## What did you expect to see?

no crash and see mesh and floors in Revit

## What did you see instead?

Constantly crash and I cannot even see the library on Dynamo

![2019-07-12_10-32-48](https://user-images.githubusercontent.com/52829616/61137002-985e2d00-a492-11e9-97b9-bff5ca2d08db.jpg)
![2019-07-12_10-33-17](https://user-images.githubusercontent.com/52829616/61137003-985e2d00-a492-11e9-9fcb-7710769409cc.jpg)

**Comment by mjkkirschner** [comment]
@QilongTang didn't you see this recently under some odd circumstances?

**Comment by mjkkirschner** [comment]
@bimxl do you have Dynamo advanced Steel also installed? If so please remove it and update to the latest version.

**Comment by bimxl** [comment]
no, advanced steel is not installed. I tried to remove the dynamo folder in C drive under roaming etc. After restarting, the issue remains there. 

On the notifications, it repeats the following msg: 
notification:System.IO.FileLoadException:
 Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider.: 
 While loading assembly LibraryViewExtension, Version=2.1.0.7500, Culture=neutral, PublicKeyToken=null, Dynamo detected that the dependency CefSharp.Wpf, Version=65.0.1.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138 was already loaded with an incompatiable version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
UIFramework, CefSharp.Core, ModelBrowser, RevitModelingHost, PnIDModeler, SiteLinkerUI, CefSharp.Wpf

**Comment by QilongTang** [comment]
@mjkkirschner I suspect PnIDModeler?

**Comment by mjkkirschner** [comment]
ah, I missed it -  @bimxl how are you running 2.1 in Dynamo 2019.... anyone of those other addins will have loaded CEFSharp with another version - causing issues like this.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
