### ISSUE TITLE
Nodes are missing in a script that was working before

### ISSUE THREAD

**Issue by tonyzekry** [DynamoDS/DynamoRevit#2410]
## 2.0.3

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## 2017

(Which version of Revit are you using?)

## Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Missing nodes in the script

## What did you expect to see?

Full usual script

## What did you see instead?

When i open some scripts that i have previously created and they were working good, suddenly a few days ago i started opening my script using dynamo and i find that there are some missing nodes in the script and i have to add these nodes again to the script! As i said these scripts were correct previously but currently i don't know what happened.
![1](https://user-images.githubusercontent.com/34275263/61373301-1ca11d80-a8a2-11e9-96b4-1fda0fc2c9df.jpg)

**Comment by mjkkirschner** [comment]
Please check the dynamo console - from the looks of it, these are UI nodes which are missing.
A few things to try:
* Please uninstall any new addins or packages. 
* Any green notifications in the Dynamo Menu, what do they say?
* Update to latest pyRevit if you are using it.

**Comment by tonyzekry** [comment]
Dear Michael,
First of all, thank you so much for the reply.
Second, i uninstalled all packages then dynamo then installed again and same problem.

![d1](https://user-images.githubusercontent.com/34275263/61849105-e6265c80-aeb8-11e9-9381-5bb2f7618f56.jpg)
![d2](https://user-images.githubusercontent.com/34275263/61849109-e9214d00-aeb8-11e9-9602-5ab4dcede12d.jpg)

I have read in other posts about the pyrevit. Actually i am not using it but do you think updating it would be useful?

**Comment by mjkkirschner** [comment]
These conflicts about the Revit API can usually be ignored - 
I would look for other conflicts in the details - relating to UI - maybe Xceed dll?
it might be a conflict with another addin. You can also try removing all addins and adding them back to find the conflict if the details panel does not help.

if you have pyRevit installed then update it.

**Comment by ZiyunShang** [comment]
Hi @tonyzekry , are you still experiencing this issue now?

**Comment by tonyzekry** [comment]
Hi,
Yes problem solved. I deleted all the packages and installed again.
