### ISSUE TITLE
Cannot insert a node in the UI

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/DynamoRevit#2411]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 2.0.3 on Revit 2019
Dynamo 2.1 on Revit 2020

## Revit version

2019 & 2020

## Operating system

Windows 10 Build1809

## What did you do? 

Insert the Categories node

## What did you expect to see?

To see the node in the UI

## What did you see instead?

Nothing
It's the same behavior on both Revit version

**Comment by DanielHurtubise** [comment]
Works fine after removing all the packages, im gonna track down the bad guy and get back to you :)

**Comment by ZiyunShang** [comment]
@DanielHurtubise  Is this problem resolved?
