### ISSUE TITLE
Missing Nodes in a script that previously worked

### ISSUE THREAD

**Issue by rodbernard** [DynamoDS/DynamoRevit#2414]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.0.3

## Revit version

2018.3

## Operating system

Windows 10

## What did you do? 

Upgraded Dynamo 1.3 to 2.0.3
Opened existing graphs
Several nodes were missing, (File Path, File from Path, etc) so I added them back into the graph, saved and exited. When I open the graphs again, the same nodes are missing again. I can add new nodes elsewhere on the graph, and they are persistent, but the missing nodes always vanish.
Colleagues can open the graphs and they run correctly, (using same Revit and Dynamo versions).
I can open the graphs with Revit 2019, and they run correctly.

I reinstalled Dynamo 2.0.3 - same issue.

## What did you expect to see?

I expect all nodes to be saved.

## What did you see instead?

Missing nodes.

**Comment by mjkkirschner** [comment]
If you are using pyrevit try updating it to the latest version

**Comment by ZiyunShang** [comment]
Hi @rodbernard , are you still experiencing this issue now?

**Comment by rodbernard** [comment]
Problem fixed. I had to reload Revit anf Dynamo. I never found the problem, but I believe it was related to a Revit addon ie PyRevit.


Regards
Rod Bernard


________________________________
