### ISSUE TITLE
Library search extremely slow

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/DynamoRevit#2415]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.3

## Revit version

Revit 2018
18.0.0.420
20170223_1515(x64)

## Operating system

Windows 10

## What did you do? 

Search in the library

## What did you expect to see?

Quick filtering of nodes

## What did you see instead?

Search freezes, sometimes for minutes. Is intermittent. These are the packages I have installed. Rest of Dynamo works, i.e. i can pan in the graph, copy/paste etc. But I can't search the library for several minutes.

![1_2](https://user-images.githubusercontent.com/10913639/62176865-49ffc800-b386-11e9-9538-285bd81d89e9.PNG)
![2_2](https://user-images.githubusercontent.com/10913639/62176866-4a985e80-b386-11e9-935e-64cf7eccb1ed.PNG)

**Comment by ZiyunShang** [comment]
I think this may be due to too many packages you load. This may be an optimization direction for Dynamo. @QilongTang @mjkkirschner , could you take a look at this?

**Comment by ParametricMonkey** [comment]
I've seen that people have mentioned this before. But the freezing happens intermittently. If it was due to too many packages, it will be slow right from the start.

**Comment by AndyDu1985** [comment]
Could you try with Revit 2020? It has newer Dynamo Version.
There is a performance improvement.
see https://github.com/DynamoDS/Dynamo/wiki/Release-Note
2.1.0
Enhancements:
Library search performance improvements in general leading to faster search and more accurate key words matching. (Issue, PR1, PR2, PR3)

**Comment by ParametricMonkey** [comment]
@Amoursol I thought this would be the case. Dynamo 2.1 is tied to Revit 2020 and I can't upgrade due to client requirements. Do you have any plans to implement the same improvements to Dynamo 2.0 for the rest of us that are still using Revit 2019 and lower? Needless to say not everyone is on, or can be on, Revit 2020.

Is the slow search a result of too many packages or too many nodes in the library? The reason I ask is that the Dynamo team for some time now appears to have stopped developing nodes. So while this persists, users are left with no other way than to use multiple 3rd party packages. If the limitation is nodes in the library than developing more OOTB nodes isn't going to help. But if it is packaged dependent, than this could significantly help. In my opinion, pretty much everything that is in Archi-lab, Clockwork, Rhythm, Springs and Steam nodes should be available OOTB. That way we can keep 3rd party packages to more niche/specific topics - like datashapes and Ladybug. We need improved core functionality otherwise deployment becomes way too difficult.

**Comment by Amoursol** [comment]
@ParametricMonkey - To clarify, it's nodes in the library. 1000 nodes (Out-of-the-box libraries plus one or two packages) will perform much faster than 10,000 nodes. We have no plans to retroactively apply these fixes to prior versions of Dynamo as we have limited bandwidth. We have patched a few security related fixes back to Revit 2017/2018/2019 but typically features do not make it back.

Fully understand the client requirements side of Revit as I've been in that situation many times. As a workaround you can use the 'right click' search feature it's faster in the old context.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
