### ISSUE TITLE
Dynamo v2.1.0 not available for download?

### ISSUE THREAD

**Issue by andymanX** [DynamoDS/DynamoRevit#2416]
Where did the button go to download Dynamo v2.1.0 for revit??

On the website: https://dynamobim.org/download/

![image](https://user-images.githubusercontent.com/32685989/62397426-7c9ef180-b53b-11e9-85c3-58df56637345.png)

**Comment by ZiyunShang** [comment]
Hi @andymanX , DynamoRevit v2.1 and later will be released as Revit's internal Addin.
