### ISSUE TITLE
Frequent VM failures

### ISSUE THREAD

**Issue by TimFells9** [DynamoDS/DynamoRevit#2423]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 1.3.4.6666 (also says 2.3.0 in orange text)

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version 2019

(Which version of Revit are you using?)

## Operating system

Windows 7

## What did you do? 

Got 2 circular arc ModelLines from Revit; created a family of straight lines from points on them extrapolated either end; lofted them along the arcs to get a surface; generated points along isolines of the surface; iterated to generate vectors to new points on a special case of a geodesic; put some of these nodes into a custom node.

## What did you expect to see?

a more or less geodesic NurbsCurve along my points

## What did you see instead?

frequent freezes and crashes of the VM environment; inability to get any results from a Watch node; CodeBlocks that compiled OK kept losing function definitions in other CodeBlocks at runtime although they were right there on the screen; multiple hassle with Surface.GetIsoline(...); tendency to drop out of Automatic run and into Manual for no apparent reason. How can I best document this issue to you? I can send you some .dyn and .dyf files if you are interested?

**Comment by ZiyunShang** [comment]
Hi @TimFells9 , could you provide your workflow and work files(some dyn, dyf and Revit file)? So that we can reproduce this problem.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
