### ISSUE TITLE
Package search returns no results for all inputs.

### ISSUE THREAD

**Issue by DictatorCherry** [DynamoDS/DynamoRevit#2424]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Revit 1.3.x and 2.0.3.8810

## Revit version

Revit 2018

## Operating system

Windows 10

## What did you do? 

One day after using Dynamo Revit 1.3.x for a while, I tried to access a script I had been writing after accessing the script on my co-workers machine who was using Dynamo 2.0.3.x and there was some issues with opening it, so I updated to the new version, 2.0.3.8810, of Dynamo Core + Revit. When I did so I could access both 1.3.x and 2.0.x, but in Dynamo Revit 1.3.x node definitions from some fabrication packages that I used for the script seemed to have been removed. I uninstalled Dyanmo Core + Revit 1.3.x and 2.0.x and reinstalled Dynamo 2.0.3.x, however that did not fix my issue of not being able to search for packages. 

## What did you expect to see?

Package results when I search for them.

## What did you see instead?

A dialogue that says "Search returned no results!".

**Comment by DictatorCherry** [comment]
This issue has persisted through reinstallations of both Dynamo Revit 2.0.3.x and Revit 2018

**Comment by mjkkirschner** [comment]
@DictatorCherry please see this issue.
https://github.com/DynamoDS/Dynamo/issues/9896

It's a TLS issue - update your Revit to the latest patch specified in the AKN page.

**Comment by DictatorCherry** [comment]
@mjkkirschner I am using Revit 2018, is there a link for this security patch for Revit 2018?

**Comment by mjkkirschner** [comment]
https://knowledge.autodesk.com/support/revit-products/downloads/caas/downloads/content/autodesk-transport-layer-security-updates-require-security-fix-for-revit-2018.html

**Comment by DictatorCherry** [comment]
I will coordinate with our IT dpt and update the thread with results. Thanks for the help!
