### ISSUE TITLE
Dereferencing a non-pointer

### ISSUE THREAD

**Issue by CimaChen** [DynamoDS/DynamoRevit#2433]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.2.1.5175
Dynamo Revit2.1.0.7733

## Revit version

Revit 2020.1         20.1.0.81

## Operating system

Windows 10 Enterprise

## What did you do? 

please find the attachment.

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by ZiyunShang** [comment]
Hi @CimaChen , could you give some more info on this issue? I'm afraid your attachment missed.

**Comment by dimvoly** [comment]
Can this be closed as not enough information? This shows up on searches as an open issue.

**Comment by ZiyunShang** [comment]
OK, I closed this issue. I will reopen this if there is more information.
