### ISSUE TITLE
Dynamo 2.03 not launching in Revit 2016, 2017,2018 or 2019

### ISSUE THREAD

**Issue by mariusvanwyk2216** [DynamoDS/DynamoRevit#2435]
Installed Dynamo Revit 2.0.3, After that Dynamo does not work in Revit 2016,2017,2018 or 2019. Revit 2020 Dynamo starts up and shows Dynamo Revit 2.1.0.7733 and Dynamo Core 2.2.1.5175
![Revit 2020 Dynamo working](https://user-images.githubusercontent.com/14234026/65605342-37ca9080-dfa9-11e9-8bbc-ea4a5dc18376.JPG)
![Current Installed Dynamo versions](https://user-images.githubusercontent.com/14234026/65606063-80cf1480-dfaa-11e9-8ed7-97a1b33df625.JPG)
![Revit 2017 Dynamo not working](https://user-images.githubusercontent.com/14234026/65606064-80cf1480-dfaa-11e9-85c0-03389db4ca9d.JPG)
![Revit 2018 Dynamo not working](https://user-images.githubusercontent.com/14234026/65606065-8167ab00-dfaa-11e9-97b0-48663f1ec3c8.JPG)
![Revit 2019 Dynamo not working](https://user-images.githubusercontent.com/14234026/65606067-8167ab00-dfaa-11e9-874d-9dabb4cf04ad.JPG)
![Revit 2020 Dynamo working](https://user-images.githubusercontent.com/14234026/65606069-8167ab00-dfaa-11e9-868b-a3ecb67ed75c.JPG)

## What did you expect to see?

Expected Dynamo to open in 

## What did you see instead?

System.ArgumentException: preloadedPath
at DynamoShapeManager.Utilities.PreloadAsmFromPath(String
preloaderLocation, String asmLocation) 
at Dynamo.Applications.DynamoRevit.PreloadAsmFromRevit() 
at 
Dynamo.Applications.DynamoRevit.InitializeCoreModel(DynamoRevitCommandData commandData) at 
Dynamo.Application.DynamoRevit.ExecuteCommand(DynamoRevitCommandData commandData)

**Comment by mjkkirschner** [comment]
@mariusvanwyk2216 - seems you have a bad install of 2.0.3 - the dynamoCore version should also be 2.0.3 - you might need to force it to uninstall and then reinstall 2.0.3.

**Comment by mariusvanwyk2216** [comment]
Thanks yes did the uninstall and used Microsoft fixit. Then installed
starting with 2.02 it worked and I then installed 2.03. All good now

Regards
