### ISSUE TITLE
Error with nodes

### ISSUE THREAD

**Issue by JuanVizcarra95** [DynamoDS/DynamoRevit#2436]
## Dynamo version

Dynamo Core 2.1.0.7500
Dynamo Core 2.1.0.7733

## Revit version

Revit 2020

## Operating system

Windows 10

## What did you do? 

I want to use these nodes:
- "Detail Level"
- "Select Rule Type"

## What did you see instead?

![image](https://user-images.githubusercontent.com/56093880/66081599-eaf93380-e52d-11e9-8275-49db5df16cb2.png)

**Comment by ZiyunShang** [comment]
This error has been fixed, you can use the latest version instead. Or you could change the Automatic mode to Manuel, then create this node and select a value, it could work well.
