### ISSUE TITLE
Issue with running Springs.Feet2Fraction node

### ISSUE THREAD

**Issue by DimaPonomarovVEC** [DynamoDS/DynamoRevit#2438]
## Dynamo version
Dynamo Core 1.3.4.6666
Dynamo Revit 1.3.4.6666
2.0.3.0

## Revit version

Revit 2018.3

## Operating system

Windows 10 pro

## What did you do? 
I tried from gotten parameter conduit size 1", 0.75", 1.25" to get 3/4", 1 1/4" but Dynamo showed problem that you can find in DYN.zip
[DYN.zip](https://github.com/DynamoDS/DynamoRevit/files/3706191/DYN.zip)

![2019-10-09 10_59_08-Dynamo](https://user-images.githubusercontent.com/56339511/66462530-f4c9ec00-ea83-11e9-9059-b9ddaf50a625.png)

**Comment by ZiyunShang** [comment]
Hi @DimaPonomarovVEC , the package Spring Node is a third party package, I think you could ask its developers for help.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
