### ISSUE TITLE
Error with "Sections" Node

### ISSUE THREAD

**Issue by eric24683579** [DynamoDS/DynamoRevit#2440]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.1.0.7500
Dynamo Revit 2.1.0.7733

## Revit version

Revit 2020

## Operating system

Windows 10

## What did you do? 

Create a "Sections" Node

## What did you expect to see?

(Fill in here)

## What did you see instead?

![image](https://user-images.githubusercontent.com/55453617/66966171-279a5400-f031-11e9-8ea2-57b79c14b469.png)

**Comment by ZiyunShang** [comment]
Hi @eric24683579 , the node - 'Sections' may be a third party package, I think you can ask its owner for help.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
