### ISSUE TITLE
Custom python script node not showing 

### ISSUE THREAD

**Issue by Cisco22** [DynamoDS/DynamoRevit#2442]
![image](https://user-images.githubusercontent.com/25090141/67063767-9dc6c400-f1b3-11e9-8e8b-ded744b8949a.png)

Dynamo version 2.0.2

2019-2018-2017 Revit version

Windows 10 Operating system

## What did you do? 

Opened a graph with a custom script node, that is not showing (all that comes up is a blank code block), then when I close Dynamo I get this error.

## What did you expect to see?

the complete script 

## What did you see instead?

Just an error window

**Comment by ZiyunShang** [comment]
Hi @Cisco22 , could you provide your Revit & Dynamo files, so I can reproduce on my side?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
