### ISSUE TITLE
Need to reopen .dyn after model change

### ISSUE THREAD

**Issue by djdarkstream** [DynamoDS/DynamoRevit#2445]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Core 2.0.3.8810
Revit 2.0.63

## Revit version
19.2.20.24
20190808_0900(x64)
2019.2.2

## Operating system

Windows 10 Pro

## What did you do? 

I have a .dyn that takes a string, splits it, then fills out information in the ProjectInfo and into a TitleBlock on a Sheet, after which it'll print a PDF of the sheet.
When I close the model in Revit and open a new one to create more PDF's it hangs on nodes where it wants to SetParameterByName of both the ProjectInfo and the TitleBlock with error: 

_Warning: Element.SetParameterByName operation failed. 
The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone._

Funny thing is that the ProjectInfo element I'm passing along 3 times, only gives 2 errors. 
And the TitleBlock which I pass along 3 times, only gives 1 error.

## What did you expect to see?

No errors

## What did you see instead?

3 out of 6 nodes referencing the same two objects fail (I'm guessing its not the objects that actually fail, seeing as 3 o/o 6 work, maybe its just not retrieving all info in the object)
6 out of 6 nodes did not change the information in the model

Screenshot of the workspace:
Had too remove image, didn't save after censoring some info, will upload another if needed. But I think the answer can be given without it.

UPDATE:
I enabled the Show Run Preview setting and this immediately explained why only 3 nodes gave errors, these are hooked up to the value I change before running it again.
This stilll doesn't really give me an answer on what exactly is going wrong though...

**Comment by dimven** [comment]
When you change documents, you have to close down the graph and re-open it because Dynamo stores a reference to the active document. If you close the document, all data that belongs to it gets invalidated.

**Comment by djdarkstream** [comment]
Wouldn't it be nice though if the data was loaded for the new document when opening another.. Or that the graph gets reset entirely when closing the document you were working on, so that when you load a new document, it runs the entire graph again (this might be unwanted in some situations so maybe an option to choose a reset (or maybe even a node that does this))

If that's not a feat which can/should be in there, this issue can be closed.

(btw, I found a way around this with Dynamo Player in case anyone else also has this problem)

**Comment by AndyDu1985** [comment]
Crash may happens if we don't close Dynamo when their is no document, so we decided to exit Dynamo when no document.  PR(#2401)
