### ISSUE TITLE
Text Nodes do not work in German / French Version of Revit

### ISSUE THREAD

**Issue by jannisle** [DynamoDS/DynamoRevit#2470]
Text Nodes do not work in german/french version of Dynamo. I cannot even change a simple string. Objects do not have any location or anything else :(

https://forum.dynamobim.com/t/text-node-bug-german-english-simple-text-replace/33512

![image](https://user-images.githubusercontent.com/49270199/71973657-c2a96100-320f-11ea-828a-10f72d9d8dac.png)

Dynamo 2.02.6833
Windows 10

**Comment by andydandy74** [comment]
See #1626, #1664 & #1709.
First reported 2 years and roughly 10 months ago (Dynamo 1.2.x). 
I am sure this will get fixed any day now... ;-)

**Comment by QilongTang** [comment]
@andydandy74 @ZiyunShang Seems fairly easy to reproduce, would you take a look?

**Comment by ZiyunShang** [comment]
![TextNote-in-German](https://user-images.githubusercontent.com/33445445/74807970-bcd19000-5324-11ea-9511-ebfde2ba1c0a.png)
Hi @jannisle @QilongTang , I just try TextNote Node in German, it looks work well.
My DynamoRevit version is 2.5.0. Could you try the latest DynamoRevit version and do this again?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
