### ISSUE TITLE
Dynamo 1.3.4 Startup Error

### ISSUE THREAD

**Issue by AhmmTools** [DynamoDS/DynamoRevit#2500]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

v1.3.4

## Revit version

Revit 2019

## Operating system

Windows 10

## What did you do? 

Clicked the launch Dynamo button in Revit

## What did you expect to see?

Dynamo launching

## What did you see instead?

A large error message, like so:
![image](https://user-images.githubusercontent.com/44774230/74732943-3002d580-5243-11ea-83c1-63b271f00c7e.png)

This has begun to appear for several users on our network in the last few days. Redeploying Dynamo does not help. This is happening across multiple users and projects, so doesn't seem to be file-specific.

Can anyone please advise?

**Comment by ZiyunShang** [comment]
Have you installed some new Revit Addin recently? It may be due to a conflict between other Addin and Dynamo.

**Comment by AhmmTools** [comment]
Hi Ziyun,

we haven't installed any new addins or upgraded any versions recently. Everything's remained stable.

**Comment by AhmmTools** [comment]
@Amoursol

**Comment by ZiyunShang** [comment]
Hi @QilongTang @mjkkirschner , do you have any suggestions about this?

**Comment by AhmmTools** [comment]
Hi all - @ZiyunShang @QilongTang @mjkkirschner 

I've been facing this issue on Dynamo 2.0.3. We might have a reproducible test case on our end.

**Comment by AhmmTools** [comment]
Hi @mjkkirschner , I've been sent your way by Sol. 
I intially disregarded the error message as a red herring, but this does indeed appear to be a XAML issue. I've narrowed it down to the following: our plugin-wide ResourceDictionary probably has a naming conflict with Dynamo's. I will continue digging, but I've been told you're the right person to speak to about Dynamo's UI.

**Comment by AhmmTools** [comment]
I've solved it - it was down to one of the styles in our Resource Dictionary. I can only assume it has a naming conflict with a Dynamo Resource Dictionary. In particular, Dynamo didn't like the IsReadOnly property we'd set.

<Style x:Key="StandardComboBox" TargetType="{x:Type ComboBox}">
        <Setter Property="FontFamily" Value="Segoe UI"/>
        <Setter Property="FontWeight" Value="Regular"/>
        <Setter Property="FontSize" Value="12px"/>
        <Setter Property="Foreground" Value="{StaticResource FontColorDefault}"/>
        <Setter Property="Height" Value="22px"/>
        <Setter Property="Margin" Value="0px"/>
        <Setter Property="BorderThickness" Value="0px"/>
        <Setter Property="VerticalAlignment" Value="Top"/>
        <Setter Property="IsEditable" Value="True"/>
        <Setter Property="IsReadOnly" Value="True"/>  !!!!!!!!!!!!!!!! This is the offending property !!!!!!!!!!!
        <Setter Property="VerticalContentAlignment" Value="Center"/>
    </Style>

**Comment by Amoursol** [comment]
Love seeing self-solves! Good stuff @AhmmTools 😊

**Comment by mjkkirschner** [comment]
I don't think this has anything to do with the dynamo resource dictionary.

see this thread:
https://github.com/eirannejad/pyRevit/issues/525
for a very similar stacktrace and see the fix that was made by the PyRevit author.

Are you using an old version of PyRevit?

**Comment by AhmmTools** [comment]
Hi Mike, I don't have PyRevit installed. We are using our own addin, which has no external dependencies. It just uses WPF for UI.
Based on the stackoverflow link Ehsan [https://stackoverflow.com/questions/6850713/weird-xaml-parsing-error-when-trying-to-set-textbox-isreadonly--](posted) at the bottom of his issue, it appears to be a WPF bug / conflict.

I can confirm I found the same solution:
Opening Revit, then Opening Dynamo 2.0.4 works fine.
Opening Revit, displaying a dialog with the offending style, then opening Dynamo causes the error message.
Specifically (and only) commenting out the IsReadOnly property on the offending style causes Dynamo to launch, even when the offending dialog has displayed before Dynamo has launched.

I'm happy to discuss / demonstrate this reproducible behaviour if this would be helpful.

**Comment by mjkkirschner** [comment]
@AhmmTools thanks - if possible can you provide the following info:

1. do you subscribe to AssemblyResolve in your addin?
2. what version of .net framework do you target for your addin?
3. what version of Revit are you loading your addinin?
4. Do you see the same behavior with Dynamo 2.0.3?
5. Do you see the same behavior in Revit 2020 or 2021?

**Comment by AhmmTools** [comment]
1. Yes we do
2. We load different versions for different versions of Revit in the .csproj file. For 2018 we use 4.6.1. For 2019 onwards we use 4.7.2.
3. Revit 2018 and 2019
4. Yes
5. Yes

**Comment by mjkkirschner** [comment]
- please look at this commit from eirannejad
in it - he disables his addins' assembly resolve when the original assembly requesting the current assembly is not from his addin.
https://github.com/eirannejad/pyRevit/commit/8f463d109ba6a31b164775527f8491a3d2ff9b37

If you implement similar logic likely the issue will be solved and you can use the property you need, it's likely defined in some other assembly that is being loaded at runtime when this property is parsed - 
the issue is that when Dynamo asks for that same assembly - there is no guarantee that your handler is not called first.

In fact, it probably is called first, as you load your addin, and register it first, in your example above.

**Comment by AhmmTools** [comment]
Hi Michael, 

I've had some time to test, commenting out the AssemblyResolve code and tested again (with the XAML property re-activated). The error is still happening as before.
