### ISSUE TITLE
All Elements of Element Type supporting less element types than before

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#2515]
## Dynamo version
Dynamo Core 2.3.0.5885
Dynamo Revit 2.3.0.7661

## Revit version
2020.2.1

## Operating system
Win 10

## What did you do? 
Used the ```All Elements of Type``` node to collect instances of some element types.

## What did you expect to see?
The elements to be collected.

## What did you see instead?
Some element types that used to work with the node node in 1.3.4 now return null. This regression was apparently already introduced in Dynamo 2.0.x since I can reproduce it with Dynamo 2.0.3 as well.
The following element types that used to work now return null:
- CurveElement
- Material
- ConnectorElement

They throw the following warning:
```
Warning:ElementQueries.OfElementType failed.
The input type is not a subclass of Element.
Parameter name: type
```

**Comment by QilongTang** [comment]
@ZiyunShang  @AndyDu1985

**Comment by AndyDu1985** [comment]
We will look into it.

**Comment by ZiyunShang** [comment]
I have a fixing by PR https://github.com/DynamoDS/DynamoRevit/pull/2525 .
