### ISSUE TITLE
Dynamo OOB nodes removed from graph

### ISSUE THREAD

**Issue by jasonboehning** [DynamoDS/DynamoRevit#2528]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo -- Build 2.0.3.8810

## Revit version

Revit 2019.2

## Operating system

Windows 10

## What did you do? 

1. Created a basic graph using all OOB nodes
2. Ran the graph
3. Saved the graph
4. Re-opened to find that some of the OOB nodes are missing

## What did you expect to see?

I have never had OOB nodes be removed from a graph before. I expect to see all the nodes in the graphs I create.

## What did you see instead?

Certain OOB nodes missing, such as Categories, All Elements of Category, etc. I have attached two images (before and after) along with the Dynamo log. Also, this has been happening after I installed the latest version of SysQue, which is a Revit add-in. When I perform the same steps on another machine that doesn't have SysQue, I don't have the same issue, even though some of the same notifications appear. (Like these: Dynamo has detected a conflict with a dependency and may be unstable.)

![OOB_Nodes_1](https://user-images.githubusercontent.com/62903458/77946696-5c6d3100-7288-11ea-9a50-83832c7e3fce.png)
![OOB_Nodes_2](https://user-images.githubusercontent.com/62903458/77946699-5d05c780-7288-11ea-845b-31b68e0c55be.png)
[Dynamo_log_OOB_Nodes.txt](https://github.com/DynamoDS/DynamoRevit/files/4404632/Dynamo_log_OOB_Nodes.txt)

**Comment by jasonboehning** [comment]
@Amoursol here is the issue we were discussing. Thanks!

**Comment by mjkkirschner** [comment]
This can happen for a bunch of reasons - but if you've already narrowed down to SysQue I would start with an additional report to them - I cannot find a download anywhere to check it out - but addins will sometimes register assemblyResolve handlers - if these handlers are throw an exception they can stop other addins from loading components they need. Unfortunately, it's not in our control which order these are registered in, or what order they are called in.

Of course this is a guess from past examples of the same behavior - if you have a contact you may want to point them tot this issue.

Additionally, it may be useful to see a screenshot of the addin's binaries folder to look for common conflicts.

**Comment by mjkkirschner** [comment]
one more comment here, in newer versions of Dynamo the nodes should no longer just disappear - but atleast turn to unresovled nodes if they could not be loaded.

**Comment by jasonboehning** [comment]
Thanks @mjkkirschner, I'm happy to provide a screenshot. Can you point me in the direction where I could find this folder?

**Comment by mjkkirschner** [comment]
@jasonboehning - sorry - I don't know - it would be wherever SysQue installs itself... it could be anywhere really, but common locations are under programFiles

**Comment by jasonboehning** [comment]
I submitted a support ticket to Building Data and discovered that there was an update that needed to be installed. So when you install SysQue, it also installs some other add-ins from MEP Content. (I'm sure there's a way to not have them install, but I had installed them.) A couple of these add-ins required an update. Once updated, everything went back to normal. Thank you for your help!

**Comment by Amoursol** [comment]
Awesome - glad to hear it @jasonboehning ! Closing now 🏆
