### ISSUE TITLE
Roof.ByOutlineExtrusionTypeAndLevel operation failed.

### ISSUE THREAD

**Issue by m-danm** [DynamoDS/DynamoRevit#2544]
Warning: Roof.ByOutlineExtrusionTypeAndLevel operation failed. 
The input PolyCurve is not closed
if I close it the Error becomes "Invalid Profile"

there is no decent example of this node working anywhere...

Creating roof by profile works with Wombat node.. but not with ootb ...

**Comment by Amoursol** [comment]
Hello @m-danm ,

I've transferred this over to the **Dynamo4Revit** repo!

Pinging @AndyDu1985 re: the issue.

**Comment by ZiyunShang** [comment]
This may be a bug, the input PolyCurve should not be closed in RevitAPI.

**Comment by ZiyunShang** [comment]
https://github.com/DynamoDS/DynamoRevit/pull/2550 I have fixed this bug in master branch. It will be released next Revit version.
