### ISSUE TITLE
Yet another System.IO.FileLoadException issue

### ISSUE THREAD

**Issue by kikunot** [DynamoDS/DynamoRevit#2545]
I am trying to install DynamoRevit and Dynamo from source code in order to create testing for my Dynamo programs using C#.  I am using the following documentation. [Dynamobim](https://developer.dynamobim.org/02-Build-Dynamo-From-Source/2-1-build-dynamo-revit-from-source.html) However, I have not being able to successfully run Dynamo for Revit.

**Left Panel disappears**
One issue I keep seeing is there is add-in conflicts so that my left panels disappears. 
This occurred when I installed the following versions, 
`Dynamo: v2.1.0`
`DynamoRevit: Revit2019`
I've cleaned up my add-ins, yet I keep seeing the same error.

![image](https://user-images.githubusercontent.com/44632198/79178874-55761f00-7e41-11ea-8bd5-74869b4109b0.png)

![image](https://user-images.githubusercontent.com/44632198/79178952-85bdbd80-7e41-11ea-9e1f-801bcbbf0555.png)

Other add-in folders are empty.

(Same issue occurred when I installed Dynamo master branch, however this master branch was using DynamoCore v2.7.0 which was different from my DynamoRevit version so I installed v2.1.0 instead)

There was one version that I was able to run Dynamo without System.IO.FileLoadException issue.
Dynamo: `RC2.0.4_master`
DynamoRevit: `RC2.0.4_Revit2019`
However the problem with these versions were when I run testings, most of the tests (such as `CanSaveImage() ` test from `DynamoCoreWpfTests)` failed to run even though other versions were able to run these tests just fine.

I have been struggling with this installation issue close to a month already. I have read through blogs and Github issues. There are people with similar issues; however, none of them seem to give me a clean cut solution. I've also read that these source codes are under development. Are these source codes not meant to be used for testings?

If you could give me any direction or advice that will be extremely helpful. 
I haven't been able to figure out why constructing testing environment for Revit add-ins and Dynamo is so hard. I thought creating a testing environment is the first thing one needs to do as a developer before doing any development.

Thank you in advance, looking forward to hear your reply.

## Dynamo version

![image](https://user-images.githubusercontent.com/44632198/79179566-db469a00-7e42-11ea-8eb0-5cf8a5fa84d1.png)

## Revit version

2019

## Operating system

Windows 10

## What did you do? 

-Tried installing different versions of source codes. I.e Dynamo v2.0.4 and DynamoRevit v2.0.4 and so on
-Clean third party add-ins
-Reinstalling Revit and Dynamo 

## What did you expect to see?

-left panel and load dynamo properly
-successfully run dynamo testings

## What did you see instead?

-System.IO.FileLoadException, left panel disappears
-unable to load testings properly

P.S: No, I don't have NBS plug-in

**Comment by mjkkirschner** [comment]
The latest version of DynamoCore that is supported on Revit 2019 is 2.0.4. But 2.0.4 is not released so I would stick with 2.0.3.

The tests can be quite tricky to run on a local system. Running them all will take several hours. Make sure to remove all packages from your local install.

The core tests also are not intended to be run inside Revit (ie through DynamoRevit) so not sure why you believe the DynamoRevit installation status has an effect on them.

What type of testing are you looking to perform for your Dynamo c# code?
Are you writing code that interacts with the Revit API?

**Comment by kikunot** [comment]
@mjkkirschner  Thank you for your quick response. I will install 2.0.3 version and if Dynamo can be opened properly. Its good to know the latest version of DynamoCore.

I wasn't sure if the core tests could be run inside Dynamo Revit, but I just wanted to see what's possible and what's not. I guess I shouldn't do things that are not intended.

In terms of the things that I want to tests with Dynamo C# code is some of my coworkers can use Dynamo to create some automation tools. However, these tools usually get large and cumbersome. I would rather rewrite some of the useful ones in zero touch nodes and use testing to documents the development process properly. Another thing I wanted to test is Revit C# plugins. I developed some plug-ins such as lighting plot automation tool. However, I wasn't able to TDD properly. I was hoping this testing for Dynamo can be used for Revit plug-in testing.

**Comment by mjkkirschner** [comment]
hmm, well testing Dynamo graphs in Revit is complex as well -but if you are looking to test Revit addins in general you may want to look at https://thebuildingcoder.typepad.com/blog/2019/10/testrunner-run-unit-tests-in-revit.html

Dynamo For Revit uses a framework to do a similar testing on top of revit:
https://github.com/DynamoDS/RevitTestFramework

If you are looking to write tests for zero touch nodes that you are writing you should be able to test these with something like RTF - or even better-  if you write them in such a way that Dynamo/Revit are not involved at all you can unit test them by just executing regular unit tests against your c# functions.

You then layer more complex tests on top which require Revit or Dynamo interaction.

There are some instructions you can look at here for testing which might be useful:
https://developer.dynamobim.org/04-Testing/4-0-testing.html
https://github.com/DynamoDS/Dynamo/wiki/Writing-Unit-Test-Libraries-for-Dynamo

It's important to consider if the code you are testing needs access to a running Dynamo and/or Revit session - this considerably complicates matters but is possible.

**Comment by kikunot** [comment]
@mjkkirschner Dynamo Revit v2.0.3 worked perfectly fine. Also thank you for the tips and resources, I will sort out which one I need to perform the particular task. I will start with "Testrunner" and "Testing tips on dynamo."

**Comment by kikunot** [comment]
@mjkkirschner Thank you for your tips. I was able to run all the testing environment that you have recommended(testrunner, Revit Testing Framework, and unit test for Dynamo). It took me couple days since my experience with C# and Revit is still shallow. Moreover, some .dll files caused error; some required me to create a local copy and some doesn't require me to create local copy. I will look into test libraries and see if there is any useful sample of tests that I could implement. Again thank you for your help.

**Comment by kikunot** [comment]
@mjkkirschner Is it okay to ask you one more advice since you asked for what I am intending to use these tests. I have tones of dynamo files from my co-workers. What would you recommend to keep these files less buggy. Should I make test cases for each dynamo files? or should I rewrite them in zero-node program? or something else. Looking forward for your reply.
