### ISSUE TITLE
Problem obtaining simple Dynamo geometry from Revit family

### ISSUE THREAD

**Issue by R-vdg** [DynamoDS/DynamoRevit#2551]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Core 2.03.8811
Revit 2.0.3.8811

## Revit version

2019.0.2

## Operating system

Windows 10

## What did you do? 

Try to get Dynamo geometry from a Revit sweep (window frame).

## What did you expect to see?

A correct representation of the the geometry.

## What did you see instead?

an incorrect representation. 
See also: 

https://forum.dynamobim.com/t/problem-obtaining-simple-dynamo-geometry-from-revit-family/49448/5

![afbeelding](https://user-images.githubusercontent.com/63853567/79565955-ff5be280-80b1-11ea-87b0-0fc5634ab911.png)

family and script are in the zip below

[forum.zip](https://github.com/DynamoDS/DynamoRevit/files/4492712/forum.zip)
)

**Comment by ZiyunShang** [comment]
Hi @R-vdg , this issue has been fixed by https://github.com/DynamoDS/DynamoRevit/pull/2466 , but it has not been released with Revit. You can use the master branch build instead.
