### ISSUE TITLE
Dynamo doesn't purge the data from memory at the end of the script!

### ISSUE THREAD

**Issue by m-danm** [DynamoDS/DynamoRevit#2552]
1. script reads data from a table (rvt schedule);
2. performs some operations based on that data
3. scripts ends.

I've applied a filter on that schedule, and run the script again. I was super surprised to see that the same data, from the beginning, was used once again...!?!?

I've closed dynamo (reset), and after restart in the same file, the scrip was using the right data.

THAT'S A VERY BIG ISSUE~!!!

Revit 2021. Dynamo 2.5 ootb!!!!!

**Comment by ZiyunShang** [comment]
https://github.com/DynamoDS/DynamoRevit/pull/2560 Hi @m-danm I have a fix here. If you want to have a try, you need compile the latest master branch code.
