### ISSUE TITLE
Inconsistency when getting geometry surface

### ISSUE THREAD

**Issue by ViniKawazoe** [DynamoDS/DynamoRevit#2562]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Revit 2.1.0.7733

## Revit version

Revit 20.0.0.377

## Operating system

Windows 10

## What did you do? 

Created a opening by face on a structural beam using Revit. Tried to retrieve the geometry surfaces on Dynamo.

## What did you expect to see?

Expected Dynamo to show me the same geometry that appears in Revit.
![BeamOpenings1](https://user-images.githubusercontent.com/59017826/82217282-981f9100-98f0-11ea-9b7c-cbb89c634768.png)

## What did you see instead?

Instead, the Dynamo is showing inconsistencies after retrieving the geometry. In one side, it shows the correct geometry.
![BeamOpenings2](https://user-images.githubusercontent.com/59017826/82217426-c56c3f00-98f0-11ea-9bac-b3cb92b1c833.png)
But on the other side, it doesn't cut all of the openings.
![BeamOpenings4](https://user-images.githubusercontent.com/59017826/82217476-d917a580-98f0-11ea-99e6-ead893243542.png)

Instead, it gets the surface without the opening and also the surface of the opening, which leads to an incorrect surface area.

**Comment by ViniKawazoe** [comment]
[TestBeamOpening.zip](https://github.com/DynamoDS/DynamoRevit/files/4644340/TestBeamOpening.zip)

Here are the files to reproduce the situation.

**Comment by ZiyunShang** [comment]
Hi @ViniKawazoe , I think you can try the latest version of DynamoRevit. I have fix this problem by https://github.com/DynamoDS/DynamoRevit/pull/2466
