### ISSUE TITLE
Warning: Internal error, please report: Dereferencing a non-pointer. Internal error, please report: Dereferencing a non-pointer.Engine.Execute expects argument type(s) (Engine, Point[], SilentModeSettings, bool, bool, bool, bool, bool, bool, Settings), but was called with (DynaSpace.Engine, Autodesk.DesignScript.Geometry.PolyCurve, null, bool, bool, bool, bool, bool, bool, DynaSpace.Settings).

### ISSUE THREAD

**Issue by Budiandez** [DynamoDS/DynamoRevit#2563]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.1.0.7500, Dynamo Revit 2.1.0.7733

## Revit version

Revit 2020

## Operating system

Windows 10

## What did you do? 

I am relatively new to Dynamo Software. I was trying out DynaSpace Package and wanted to modify the boundaryvertice parameters to fit my site. I was able to construct the boundary with points to create a polycurve but when I connect the polycurve to the boundaryvertices under the Engine. Execute tab, I was not able to generate anything. All it says is-

"Engine.Execute expects argument type(s) (Engine, Point[], SilentModeSettings, bool, bool, bool, bool, bool, bool, Settings), but was called with (DynaSpace.Engine, Autodesk.DesignScript.Geometry.PolyCurve, null, bool, bool, bool, bool, bool, bool, DynaSpace.Settings)."

and the list appears as 'null'

I have attached the jpeg of the error and the dynamo file. 
[https://drive.google.com/open?id=1fmryGwB4Gp0BqRIL1KDoU8cSz_v-sO8s](url)

If anyone knows how to resolve this please help me.
Thank you.

**Comment by mjkkirschner** [comment]
sounds like you should file this in https://github.com/LongNguyenP/DynaShape

**Comment by ZiyunShang** [comment]
I think you can ask DynaShape team for help.
