### ISSUE TITLE
WPF Crash

### ISSUE THREAD

**Issue by MarkAckerley** [DynamoDS/DynamoRevit#2567]
## Dynamo version

2.5.0

## Revit version

2021

## Operating system

Windows 10

## What did you do? 

Ran a py to create a WPF

## What did you expect to see?

The WPF correctly executed, but upon exiting... Both Dynamo and Revit crashed with the message 'Encountered an improper argument'

I also tried to test in sandbox v2.6, but the py wouldn't run with the message 
'File "<string>", line 18, in <module>
SystemError: The calling thread must be STA, because many UI components require this.'

Obvs the line 18 is actually 17...! I presume that's already been noted :)

I attach the most simple WPF I could make...

Thanks,

Mark

[WPF-crash.zip](https://github.com/DynamoDS/DynamoRevit/files/4676272/WPF-crash.zip)

**Comment by mjkkirschner** [comment]
in sandbox you should execute your wpf code on the dispatcher - in Revit the idle thread (where all addin code ie executed is already the same thread as the dispatcher)

https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/threading-model

**Comment by MarkAckerley** [comment]
Thanks, really interesting! So Dynamo Revit cannot run WPF? Good to know :)

**Comment by mjkkirschner** [comment]
no, that is not what I stated.
I don't know what the error you saw is on shutdown was caused by - I mentioned how you can create wpf controls in sandbox.

It's a good practice to write your code assuming you're not always going to be on the dispatcher thread and write your wpf code to make sure you are. Ie so the code will run in DynamoSandbox or Revit.

**Comment by MarkAckerley** [comment]
Ok thanks for clarifying :)

**Comment by MarkAckerley** [comment]
Ok, so some progress... Now I can crash both Revit & Sandbox!

`# Reference the WPF assemblies
import clr
import sys
import System.Windows
from wpf import *
from System.Threading import Thread, ThreadStart, ApartmentState
clr.AddReference('PresentationFramework')

# Initialization Constants
Window = System.Windows.Window
Application = System.Windows.Application

def appThread():
    # Create window
    my_window = Window()
    # Run application
    my_app = Application()
    my_app.Run (my_window)
    
thread = Thread(ThreadStart(appThread))
thread.SetApartmentState(ApartmentState.STA)
thread.Start()
thread.Join()`

**Comment by ZiyunShang** [comment]
Well, I think you can ask for help on Dynamo Forum https://forum.dynamobim.com/

**Comment by mjkkirschner** [comment]
I think you probably just want to use:

```
Application.Current.Dispatcher.Invoke(
    () =>
    {
         // Code to run on the GUI thread.
    });
```

**Comment by MarkAckerley** [comment]
Woop Woop! 

Thanks Michael...

```
import clr
import sys
import System.Windows
from wpf import *
from System.Threading import Thread, ThreadStart, ApartmentState
clr.AddReference('PresentationFramework')

# Initialization Constants
Window = System.Windows.Window
Application = System.Windows.Application

def appThread():
    my_window = Window()
    my_window.Show()
    
thread = Application.Current.Dispatcher.Invoke(appThread)
```

**Comment by MarkAckerley** [comment]
and here's the code for an example in Dynamo Revit modified from here https://pythoncvc.net/?p=247

```
import clr

# Reference the WPF assemblies
import sys
import System.Windows
from wpf import *
clr.AddReference('PresentationFramework')
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
clr.AddReference('RevitServices')
# noinspection PyUnresolvedReferences
from Autodesk.Revit.UI import IExternalEventHandler, ExternalEvent
# noinspection PyUnresolvedReferences
from Autodesk.Revit.DB import Transaction
# noinspection PyUnresolvedReferences
from Autodesk.Revit.Exceptions import InvalidOperationException

from RevitServices import *
from RevitServices.Persistence import DocumentManager
from Autodesk.Revit.UI import *
from Autodesk.Revit.UI.Selection import *
doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
# Initialization Constants
Window = System.Windows.Window

# Simple function we want to run
def delete_elements():
    t = Transaction(doc, "Failing script")
    t.Start()
    for elid in uidoc.Selection.GetElementIds():
        print elid
        doc.Delete(elid)
    t.Commit()
    
# Create a subclass of IExternalEventHandler
class SimpleEventHandler(IExternalEventHandler):
    """
    Simple IExternalEventHandler sample
    """
    # __init__ is used to make function from outside of the class to be executed by the handler. \
    # Instructions could be simply written under Execute method only
    def __init__(self, do_this):
        self.do_this = do_this
    # Execute method run in Revit API environment.
    def Execute(self, uiapp):
        try:
            self.do_this()
        except InvalidOperationException:
            # If you don't catch this exeption Revit may crash.
            print "InvalidOperationException catched"
    def GetName(self):
        return "simple function executed by an IExternalEventHandler in a Form"
# Now we need to make an instance of this handler. Moreover, it shows that the same class could be used to for
# different functions using different handler class instances
simple_event_handler = SimpleEventHandler(delete_elements)
# We now need to create the ExternalEvent
ext_event = ExternalEvent.Create(simple_event_handler)

# A simple WPF form used to call the ExternalEvent
class ModelessForm(Window):#WPFWindow):
    """
    Simple modeless form sample#
    """
    def __init__(self):
        Window.__init__(self)
        self.Title = "Hello World"
        self.Show()
    def delete_click(self, sender, e):
        # This Raise() method launch a signal to Revit to tell him you want to do something in the API context
        ext_event.Raise()
# Let's launch our beautiful and useful form !
modeless_form = ModelessForm()
```
