### ISSUE TITLE
Element.Geometry :Warning  1.Unable to compute edge from curve : NO_CUR_BB -- no current bulletin board exists     2.trim_with_edge_loops requires all curves to touch surface

### ISSUE THREAD

**Issue by Zacharia2** [DynamoDS/DynamoRevit#2593]
## Dynamo version

Dynamo 2.0.4

## Revit version

Revit 2017

## Operating system

Windows10

## What did you do? 

该方法节点位于 ：Revit - Element - Element.Geometry（）
The method node is located in：Revit - Element - Element.Geometry（）

简单的调用了Element.Geometry（）
It's a simple call Element.Geometry（）

## What did you expect to see?

希望该程序能够正常执行并得到几何模型
It is hoped that the program can execute normally and get the geometric model

## What did you see instead?

1. Unable to compute edge from curve : NO_CUR_BB -- no current bulletin board exists
2. trim_with_edge_loops requires all curves to touch surface

**Comment by Zacharia2** [comment]
是不是我的Dynamo版本太新了或者Revit版本过旧？
Is my Dynamo version too new or Revit version too old?

**Comment by ZiyunShang** [comment]
Hi @Zacharia2 , could you provide your Revit and Dynamo files? So that I can reproduce on my side.
