### ISSUE TITLE
Decouple Geometry Preview from Category: Generic Model

### ISSUE THREAD

**Issue by jshial** [DynamoDS/DynamoRevit#2599]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.0.2.6826, Dynamo Revit 2.0.2.6833

## Revit version

19.2.20.24, 20190808_0900(x64), 2019.2.2

## Operating system

Win10

## What did you do? 

Hide Generic Model category through "Visibility/Graphics" in Revit.

## What did you expect to see?

After hiding Generic Model category, keep geometry preview alive.

## What did you see instead?

All geometry previews are gone as well.

**Comment by ZiyunShang** [comment]
Hi @jshial , the "Revit Background Preview" in Dynamo also belongs to Generic Model Category. When you hide all of Generic Model Category, the geometry previews are gone.

**Comment by jshial** [comment]
@ZiyunShang  Is there a chance that dev team could decouple them in future release? Consider having tons of generic models, to be able to see geometry preview of elements from other category, hiding all generic models is essential to avoid a crowded view.

**Comment by ZiyunShang** [comment]
I am sorry for the late reply, I think this may be an improvement of RevitAPI.
What do you think of this, @AndyDu1985 ?

**Comment by AndyDu1985** [comment]
Yes, this behavior is currently by design. So the "Revit Background Preview" in Dynamo also belongs to Generic Model Category. A solution or workround is that to user filter on Generic Model Category to hide others expect those backgournd preview.
