### ISSUE TITLE
How to execute Dynamo scripts from a button in the Revit ribbon

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#2603]
Hi Dynamo team,

Just a quick one; whats the simplest way to execute a Dynamo script from a button in the Revit ribbon. 

One technique which seems interesting would be to hijack Dynamo Player but see what its doing in Revits journal file such that when the user clicks the button its like clicking the play button and then they see the input window on player and can execute their script. 

Using the player as-is is not desirable as the ribbon already contains a tab with a suite of add-ins and the client wants all their tools as buttons under this tab to emphasise their workflows to the design teams. 

Any pointers you can give would be greatly appreciated.

**Comment by MarkAckerley** [comment]
Hi Thomas,

This is how I do it, I looked for the original forum post but couldn't find it...

https://github.com/MarkAckerley/Csharp/blob/master/Dynamo_Launch_From_Ribbon

Hope that's of interest, all comments welcome :)

Mark

**Comment by ThomasMahon** [comment]
Awesome thanks for sharing - I found a post using your method on the [Revit API forum](https://forums.autodesk.com/t5/revit-api-forum/dynamo-script-in-revit-api/m-p/9087859/highlight/true#M41896) so maybe it was there and not the Dynamo forum? Either way, time to get testing...

**Comment by skibadubskiybadubs** [comment]
This approach works well until you have a node in Dynamo script that will create another transaction. When that happens, the node will throw an error: "operation failed. Starting a transaction from an external application running outside of API context is not allowed.".

Did you guys ever found a solution for this? 
I guess its an issue with modeless tasks, but I am not sure how to address it.
