### ISSUE TITLE
Simple Dynamo Script never returns

### ISSUE THREAD

**Issue by wassimj** [DynamoDS/DynamoRevit#2609]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.3.0.5885
Dynamo Revit 2.3.0.8352
## Revit version

Revit 2020

## Operating system

WIndows 10

## What did you do? 

Created a wall in Revit
Launched Dynamo Revit through Manage -> Dynamo
Created a new Dynamo definition
Set the Execute mode to "Manual"
Inserted the Categories node and set it to Walls
Inserted the "All Elements of Category" Node
Connected the output of the "Categories" node to the input of the "All Elements by Category" node
Pressed the "Run" button

## What did you expect to see?
That the run will finish in a very short amount of time
The output of the "All Elements of Category" Node being a valid Revit Element

## What did you see instead?

The Dynamo definition never completes the execution and the message "Run started..." stays on-screen
I have recorded an MP4 video, ZIPPED it and attached it to this submission.

[DynamoRevitBug.zip](https://github.com/DynamoDS/DynamoRevit/files/5045150/DynamoRevitBug.zip)

**Comment by wassimj** [comment]
By the way, I just downloaded a brand new/fresh version of Revit 2021. Launched for the first time and repeated the process above and it gave me the same result. The definition never returns.
![DynamoRevit2021Bug](https://user-images.githubusercontent.com/6302909/89709250-2480a380-d976-11ea-990f-0b691668e487.png)

**Comment by wassimj** [comment]
Ignore. Was solved. Turns out you have to hit ESCAPE twice to exit wall creation. Revit should really not allow you to cilck on Manage and launch Dynamo if it is still not exited from the wall creation operation. Anyway. Solved.

**Comment by OliverEGreen** [comment]
Hi Wassim, Revit needs to be in its idle state in order for Dynamo to run. It won't run when: 

* Revit's active view is a 3D perspective view.
* Any Revit dialog whatsoever is open.
* Revit is in Edit Sketch mode, or similar.

However, it would be a big UI improvement if Dynamo were to report this to the user!
