### ISSUE TITLE
Element.GetParentElement don't work as expected.

### ISSUE THREAD

**Issue by AndyDu1985** [DynamoDS/DynamoRevit#2611]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.6.1

## Revit version
2021

## Operating system
Win 10

## What did you do? 
![image](https://user-images.githubusercontent.com/10704909/90105745-04d3eb80-dd79-11ea-854c-953ccc97d47b.png)

## What did you expect to see?
 StairRun should have Stairs as its parent.

## What did you see instead?
Null.

**Comment by ZiyunShang** [comment]
This bug has been fixed by https://github.com/DynamoDS/DynamoRevit/pull/2624 .
