### ISSUE TITLE
Dynamocore.dll issue

### ISSUE THREAD

**Issue by DonniaT-H** [DynamoDS/DynamoRevit#2646]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version 2.0.4
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version 2018.3

(Which version of Revit are you using?)

## Operating system Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

My packages were recently moved to a network drive, They show in my Installed Packages under Manage Packages but not in my library, I get an error about my Node of type "Unresolved ......DynamoCore.dll cannot be resolved. Others using same builds can see these packages in their library. 

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)

**Comment by DonniaT-H** [comment]
![bad dll](https://user-images.githubusercontent.com/58597506/98113555-d7777500-1e71-11eb-87d4-d5ed01f77f31.jpg)

**Comment by mjkkirschner** [comment]
please read:
https://github.com/DynamoDS/Dynamo/wiki/Loading-Packages-with-Binaries-from-a-Network-Location

**Comment by mjkkirschner** [comment]
Hi @DonniaT-H - I see you also filed: https://github.com/DynamoDS/Dynamo/issues/11229
so you've already seen this link.

You might try manually unblocking these binaries or marking your mapped drive as a trusted site.

**Comment by DonniaT-H** [comment]
If the mapped network drive is a cloud drive would that make a difference?

**Comment by ZiyunShang** [comment]
I found that this issue is duplicated, I will close this.
