### ISSUE TITLE
3D in revit 2021 not working

### ISSUE THREAD

**Issue by amraboali** [DynamoDS/DynamoRevit#2664]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Operating system

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

(Fill in here)

## What did you expect to see?

(Fill in here)

## What did you see instead?

(Fill in here)
![2](https://user-images.githubusercontent.com/77152297/104699993-34b65f00-571c-11eb-92bb-47780aa433a6.PNG)
![1](https://user-images.githubusercontent.com/77152297/104699995-354ef580-571c-11eb-8cd1-2b6d538749b1.PNG)

What is The Problem With Revit 2021..?

**Comment by QilongTang** [comment]
Hi @amraboali can you check the view setting to see if `Background Preview` is set? Sandbox does not share same setting with DynamoRevit and since Sandbox is working correctly for you, I expect no issue there.
![image](https://user-images.githubusercontent.com/3942418/104752593-dcd02600-5724-11eb-9ca7-d9aeda018ee6.png)

**Comment by amraboali** [comment]
Thanks for your reply
And This happened ..what to do next.?

Sent from Mail for Windows 10

**Comment by QilongTang** [comment]
> Thanks for your reply And This happened ..what to do next.? 

If you do not see the check checked, please click on it to enable Background geometry preview.

**Comment by amraboali** [comment]
Somehow it Just Worked Thank You A lot for your Time ..

Sent from Mail for Windows 10

**Comment by QilongTang** [comment]
@amraboali Thank you. Don't hesitate to get to us if you see anything in the future. Closing.
