### ISSUE TITLE
Dynamo 2.5 Background preview options are greyed out

### ISSUE THREAD

**Issue by kpai93** [DynamoDS/DynamoRevit#2677]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## 2.5

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Windows 10 Home

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Tried to get home to display 3d but the options are greyed out and there are no toggles on the 2d graph

## What did you expect to see?

A 3d preview

## What did you see instead?

Just the 2d grids showing up See attached screenshot
![Screenshot (11)_LI](https://user-images.githubusercontent.com/48401610/107506090-9951c600-6bc3-11eb-9b95-216d4b2cc9b6.jpg)

**Comment by QilongTang** [comment]
hi @kpai93 , if you expand the console, do you see error creating a background preview? If that is the case, you may need to install directX following this https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds#installing-directx

**Comment by kpai93** [comment]
> hi @kpai93 , if you expand the console, do you see error creating a background preview? If that is the case, you may need to install directX following this https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds#installing-directx

@QilongTang  I get an error creating a background preview in dynamo(attached). Revit 2021 ships with Dynamo 2.5 and that requires  DirectX 10 according to the link you provided. Windows 10 comes with DirectX 12 and thats the version I currently have. Perhaps dynamo is showing the error because of the direct X version? I will follow the steps and see what happens!
Thank you
![Screenshot (11)_LI](https://user-images.githubusercontent.com/48401610/107535947-396d1680-6be7-11eb-9ff8-83342b2b2932.jpg)

![dynamo 2 5_LI](https://user-images.githubusercontent.com/48401610/107535871-28bca080-6be7-11eb-9183-04438e41cc80.jpg)

**Comment by QilongTang** [comment]
@kpai93 Thanks, let us know! It should help us updating the documentations

**Comment by kpai93** [comment]
Sorry this is the error message
![Screenshot (13)](https://user-images.githubusercontent.com/48401610/107536598-f5c6dc80-6be7-11eb-8723-240fd74e2e01.png)

**Comment by kpai93** [comment]
@QilongTang I tried to follow the steps. Where can I find directX 10? And can I run two versions of DirectX in windows 10?(Currently running directx 12)

**Comment by mjkkirschner** [comment]
@kpai93 dx10 will not effect dx12 - unfortunately, it seems microsoft removed the dx10 installers for some reason, so download our repo and used the one linked there in the wiki @QilongTang shared - OR you can use the web archive of the installer... 😬 
http://web.archive.org/web/20210116051732/https://www.microsoft.com/en-us/download/details.aspx?id=35

hopefully MS puts the installer back.

**Comment by mjkkirschner** [comment]
I guess they will not be replacing it:
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/sha-1-windows-content-to-be-retired-august-3-2020/ba-p/1544373

**Comment by kpai93** [comment]
DXSETUP.exe  from https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds#installing-directx does nothing either.  Is it possible to replace the dynamo version 2.5 with 2.7? Since I already have directx 12 that it supports
![dynamo 2 5](https://user-images.githubusercontent.com/48401610/107540129-b7cbb780-6beb-11eb-84d9-ce8f83e63f3d.PNG)

**Comment by kpai93** [comment]
DXSETUP.exe  from https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds#installing-directx does nothing either.  Is it possible to replace the dynamo version 2.5 with 2.7? Since I already have directx 12 that it supports
![dynamo 2 5](https://user-images.githubusercontent.com/48401610/107540129-b7cbb780-6beb-11eb-84d9-ce8f83e63f3d.PNG)

**Comment by kpai93** [comment]
@QilongTang @mjkkirschner  Problem solved by installing directx 10 from https://directx-10.en.lo4d.com/windows
The issue was with directx just like the page mentioned. What a relief!
![Screenshot (15)](https://user-images.githubusercontent.com/48401610/107545812-b43b2f00-6bf1-11eb-9beb-b80c1d3bfd08.png)

**Comment by QilongTang** [comment]
@kpai93 Thank you so much for sharing with us. This is indeed a pain for legacy versions of Dynamo. Let us know if anything went wrong in the future.
