### ISSUE TITLE
Saving from Dynamo API nodes on top of each other

### ISSUE THREAD

**Issue by jamo162** [DynamoDS/DynamoRevit#2688]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## What did you do? I tried to save my Current WorkspaceModel from the API with the following declarations;
public static Dynamo.Graph.Workspaces.WorkspaceModel Current()
        {
            var model = Dynamo.Applications.DynamoRevit.RevitDynamoModel;
            Dynamo.Graph.Workspaces.WorkspaceModel ws = model.CurrentWorkspace;
            
            return ws;
        }
internal EngineController EngineController { get; set; }
public List<Especificacion> getNodeTypes()
        {
            Dynamo.Graph.Workspaces.WorkspaceModel ws = Current();
            string filepath = CurrentWorkspaceFileName;
            ws.Save(filepath, false, EngineController);
            etc etc etc
         }

## What did you expect to see?

I expected my definition to be saved and keep the same appearance when opening.

## What did you see instead?

After the saving process from the API, closing and opening the definition again. All nodes appeared on top of each other.

**Comment by mjkkirschner** [comment]
The method you are using does not serialize any view properties, the node positions are view properties.
You can try using a `SaveCommand` from the viewModel - or the `SaveAs` method there.

You can also look at how save from the ui stiches the model and view together here:
https://github.com/DynamoDS/Dynamo/blob/fffcb0def735f4d1a391c900e2b703b66ded99d0/src/DynamoCoreWpf/ViewModels/Core/WorkspaceViewModel.cs#L549

**Comment by jamo162** [comment]
That was it! Thank you.
