### ISSUE TITLE
Dynamo Library Bar missing

### ISSUE THREAD

**Issue by martinstacey** [DynamoDS/DynamoRevit#2713]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
- I checked this issue on various Core versions. (2.11.1, 2.11.0, 2.9.0, 2.6.1) With the same results.
- Dynamo Revit 2.6.1.885 running on Revit 2021.1.2 works fine. 

## Operating system
Windows 10 Pro

## What did you do? 
-Installed and opened Dynamo Core, no additional Addins installed.
-Unzipped using 7Zip.

## What did you expect to see?
Library menu with nodes/ categories.

## What did you see instead?
Empty Library sidebar, when adjusting the menu's width, categories and nodes appear, but the action executed when clicking on them does not match what you see on the menu.
It seems that the menu is only updated when changing its width.

![dynamoLibrary](https://user-images.githubusercontent.com/25138291/120461139-a91f3100-c391-11eb-9b38-90077eb8af40.gif)

## Additional information
-As suggested on other forums I already tried removing the `PnIDModeler folder` from the `Revit 2021\AddIns\` menu  (https://forum.dynamobim.com/t/the-missing-library-bar-in-dynamo/29494)
(https://github.com/DynamoDS/DynamoRevit/issues/1968)

**Comment by ZiyunShang** [comment]
@mjkkirschner @QilongTang , could you take a look at this? Is this a conflict with some addins?

**Comment by mjkkirschner** [comment]
no, @martinstacey is loading dynamoCore directly so there are no addins, I think this should probably be migrated over to dynamoCore repo.

chromium embedded framework display looks like it's crashing for some reason. I think we've seen similar issues in the past with some anti virus software.

**Comment by martinstacey** [comment]
I am currently using the provided antivirus that comes with windows. I haven't done any major downloads/personalizations to my laptop other than standard programs (Microsoft office, slack, adobe suite, etc)  as this laptop is relatively new. 

Somebody with the same laptop from the office was experiencing the same problem.
I don't know if the laptop device  specifications are relevant: 
 
![image](https://user-images.githubusercontent.com/25138291/124582439-e91e7b80-de49-11eb-89b0-d6b56d2d06ea.png)

**Comment by mjkkirschner** [comment]
this seems relevant, especially if you have a new CPU in a laptop with latest intel iris gpu - try the suggested update or force graphics acceleration to your discrete card (if you have one)
https://github.com/cefsharp/CefSharp/issues/3280

**Comment by martinstacey** [comment]
thanks @mjkkirschner! that solved it, I reinstalled the graphics update provided in the link you sent and it works fine now.
