### ISSUE TITLE
CategoryByName localized not working with the "Views" category

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/DynamoRevit#2723]
## Dynamo version

2.6 / 2.10

## Revit version

Revit 2011.1.3 / Revit 2022

## Operating system

Windows 10 x64

## What did you do? 

Tried to use the Category.ByName node with the FRA string (Vues) of Views

## What did you expect to see?

To get the proper category

## What did you see instead?

Incorrect category in this document

![image](https://user-images.githubusercontent.com/4299930/124662682-72b16600-dea9-11eb-9470-40af79c7caf4.png)

**Comment by ZiyunShang** [comment]
The reason for this issue is that there are no Views from Categories in the Current Document Settings. After asking the Revit Owner, it is found that this is by design.
We need to use another way to get category here.
