### ISSUE TITLE
"All Elements of Category in View" does not work for Wires category

### ISSUE THREAD

**Issue by NurlanGH** [DynamoDS/DynamoRevit#2751]
## Dynamo version

Dynamo: `2.12.0.5650`

## Revit version

Revit 2022.1

## Operating system

OS: `Microsoft Windows NT 10.0.19043.0`

## What did you do? 

Get all wires in a view with the node "All Elements of Category in View"

## What did you expect to see?

List of Wire elements in a view

## What did you see instead?

Empty list

**Comment by ZiyunShang** [comment]
Hi @NurlanGH , I just use the same version of Dynamo, it works well. 
![WireforSelectionIssue](https://user-images.githubusercontent.com/33445445/147030373-7c7fbb95-df11-4f79-94c2-dde68ed9d95e.PNG)

Is that you input a wrong view for "All Elements of Category in View" node?

**Comment by NurlanGH** [comment]
Hi @ZiyunShang 

"All Elements of Category **in View**" does not work.
![image](https://user-images.githubusercontent.com/81344243/147032307-aa9fe859-f805-4873-aa9b-f2c3605ea50c.png)

**Comment by ZiyunShang** [comment]
Hi @NurlanGH , on my side, it can get correctly - 
![WireforSelectionIssue](https://user-images.githubusercontent.com/33445445/147033238-e036eb7f-7891-4023-af46-c3d012e81965.PNG)
Is that your views incorrectly?

**Comment by NurlanGH** [comment]
@ZiyunShang 
You are right, I selected another view with a similar name
Level 1 Power Plan instead of
Level 1 - Power Plan
Sorry, thanks for looking at the issue
