### ISSUE TITLE
Settings tab disappeared from menu bar 

### ISSUE THREAD

**Issue by Yurrey** [DynamoDS/DynamoRevit#2785]
I just opened Dynamo in Revit 2022 and I cannot seem to find the settings tab in my menu bar. does anybody know how to get it back?
Thanks in advance:)

**Comment by QilongTang** [comment]
@Yurrey That is expected in newer version of Dynamo. Try launch settings from menu bar -> Dynamo -> Preferences

**Comment by Yurrey** [comment]
Ah ok that makes sense, thanks:)

**Comment by QilongTang** [comment]
Hi @Yurrey I will close this for now. If you still have difficulty locating any Dynamo functionality. Feel free to re-open and comment
