### ISSUE TITLE
Script saved in Revit 2022 / Dynamo 2.12 doesn't open in previous Dynamo versions

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#2802]
## Dynamo version

2.12 vs 2.6 and lower

## Revit version

2022 vs 2021 and lower

## Operating system

W10

## What did you do? 

- Created a script in Revit 2022/ Dynamo 2.12
- Included a ```Select Model Element``` node
- IMPORTANT: Set that node to ```IsInput``` = ```True```
- Saved the script
- Opened the script in Revit 2021 / Dynamo 2.6

## What did you expect to see?

Backwards compatibility

## What did you see instead?

Script didn't open. Instead Dynamo greets me with an empty workspace titled "Home"

## Cause

This is likely caused by the fact that Dynamo 2.12 stores information related to the ```Select Model Element``` node in the ```Inputs``` section of the DYN file:

![grafik](https://user-images.githubusercontent.com/3014437/154678033-5349c681-0fc4-4570-b3f8-7f31a4334ac0.png)

I am assuming this is going to happen with similar nodes that weren't supported by Dynamo Player in previous versions, too.
I don't expect this to get resolved - this kind of thing was bound to happen after Dynamo 2.0.4 - just leaving it here for anyone else that may experience this nuisance.

**Comment by mjkkirschner** [comment]
Hi Andreas - I am actually looking into this now and believe we can partially resolve it- no guarantees of course, but there is a temporary workaround on the forum.

**Comment by andydandy74** [comment]
Hi Mike, I did look on the forum before posting this but must have used the wrong search terms. Having a fix for this would be quite helpful. I managed to make about a third of my package sample scripts unreadable this way last fall. ;-)

**Comment by mjkkirschner** [comment]
https://forum.dynamobim.com/t/faq-my-dyn-dyf-file-from-2-12-2-13-wont-open-in-older-versions-of-dynamo/74049
