### ISSUE TITLE
Graphs with some revit nodes saved in 2.12 won't load in earlier versions

### ISSUE THREAD

**Issue by MostafaElAyoubi** [DynamoDS/DynamoRevit#2813]
## Dynamo version
Dynamo Revit 2.12.0.5740

## Revit version
Revit 2022.1

## Operating system
Windows 11

## What did you do? 
Saved a .dyn in Dynamo for revit 2022.1, then tried to open that graph from an earlier version (the one that ships with Revit 2022)

## What did you expect to see?
I expected the graph to be retro compatible

## What did you see instead?
the graph doesn't load at all. No specific warning or anything.. I took me some time but I think I figured it out because I was able to identify the breaking point : a "Select Model Element" node that was used in the graph. When I remove it, the graph becomes "retro compatible" again.

**Comment by andydandy74** [comment]
See #2802

**Comment by MostafaElAyoubi** [comment]
Thanks @andydandy74 ! Completely missed that.
