### ISSUE TITLE
Spec Type Id Error

### ISSUE THREAD

**Issue by yonkers92** [DynamoDS/DynamoRevit#2835]
Hi there 

I was under going script upgrades from Revit 2022 to 2023 when I came across the errors shown in the images attached. 
Please assist. 
## Dynamo version
Dynamo Core 2.13.1.3887

## Revit version
Revit 2023

## Operating system
Windows 10

## What did you do? 

Setting of view scale parameter values. 

## What did you expect to see?

Change in view scale.

## What did you see instead?

See images below.
![image](https://user-images.githubusercontent.com/91775351/174602512-ce4c4938-a46e-4e77-adb1-674127e78ffb.png)
![image](https://user-images.githubusercontent.com/91775351/174602593-4455e6b2-dbbb-4a2a-b29b-c995b3f0a676.png)

**Comment by Amoursol** [comment]
@yonkers92 this has now been resolved in: Revit 2023.1 and hotfix build Revit 2023.0.2 (Dynamo 2.16). 

![image](https://user-images.githubusercontent.com/12857357/222238079-e1ee26e2-63b7-4677-b4ac-9eabfc10c930.png)
