### ISSUE TITLE
Dynamo Script runs multiple times, but should not

### ISSUE THREAD

**Issue by HWLMorgenstern** [DynamoDS/DynamoRevit#2839]
## Dynamo version

Dynamo Core 2.10.1.3976
Dynamo Revit 2.10.1.4002

## Revit version

22.0.2.392

## Operating system

Windows 10 Pro

## What did you do? 

I wrote a quite comprehensive dynamo script, including several python-script-nodes. I generate output (csv and others) in many nodes. 

## What did you expect to see?

One run should generate several output files, some of them in a specific order as the nodes/data relates to each other. Each file should only be generated ONCE.

## What did you see instead?

The files were generated and correct - but the script runs excessively long (or until execution) and the files are overwritten multiple times (highest count over log files was 7). So the same script runs over and over again, doing more or less exactly the same (small differences due to random number generators).

This is the case, if I run the script in Dynamo. When using Dynamo Player, the exact same script runs only once, as it should.

**Comment by Amoursol** [comment]
@saintentropy @mjkkirschner  do you think this is a D4R thing, or a Dynamo thing? Worth looking into with performance work.

**Comment by aparajit-pratap** [comment]
@HWLMorgenstern can you share a simple graph that can reproduce this unexpected behavior? It would be hard to diagnose the issue otherwise.

**Comment by HWLMorgenstern** [comment]
Thanks for engaging this issue. I somehow fixed the script, but never could identify the mistake. As this was almost a year ago, I honestly do not remember my doing. But you can consider this issue closed. Thanks and best regards
