### ISSUE TITLE
set parameter value by name error in revit 2023

### ISSUE THREAD

**Issue by chiften1371** [DynamoDS/DynamoRevit#2845]
HI. In Revit 2023 When I want to set parameter value by name for z Justification of Structural beams this error will be displayed.

please make some advices.

## Dynamo version

2.13
## Revit version

2023
## Operating system

windows 10
## What did you do? 

SetParameterValueByName for Structural Framing for zJustification

## What did you expect to see?

set parameter

## What did you see instead?

Get Warning
image: [https://aws1.discourse-cdn.com/business6/uploads/dynamobim/original/3X/f/b/fbe980ea9c76200b8b5c6080307798c34db45180.png](url)

**Comment by Amoursol** [comment]
@chiften1371 This has now been resolved in the following releases: 

- Revit 2023.1
- Revit 2023.0.2
- Revit 2024 (Upcoming release)

![image](https://user-images.githubusercontent.com/12857357/222238858-c116b0b0-f1f1-4d20-9b04-c67088960e0b.png)
