### ISSUE TITLE
SpecTypeId

### ISSUE THREAD

**Issue by pavpd** [DynamoDS/DynamoRevit#2859]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
![image](https://user-images.githubusercontent.com/62962330/188333529-62209543-0890-4fc3-a584-a6360dd29487.png)

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version
Revit 2023.0.2.
(Which version of Revit are you using?)

## Operating system 
Windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
![image](https://user-images.githubusercontent.com/62962330/188333507-e86e646a-7494-42e0-8da0-43449a8861b0.png)

(Fill in here)

## What did you expect to see?
Changed parameter
(Fill in here)

## What did you see instead?
Error
(Fill in here)

**Comment by Amoursol** [comment]
@pavpd This has now been resolved in the following releases:

- Revit 2023.1
- Revit 2023.0.2
- Revit 2024 (Upcoming release)

![image](https://user-images.githubusercontent.com/12857357/222238994-0e02a510-b9d1-45c7-a35f-468216a3ec0c.png)
