### ISSUE TITLE
Incorrect Category returned by Category.ByName node

### ISSUE THREAD

**Issue by ricardyn** [DynamoDS/DynamoRevit#2870]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.13

## Revit version

2023

## Operating system

Windows 10

## What did you do? 

Trying to get Category by name, using Category.ByName node

## What did you expect to see?

correct Category returned

## What did you see instead?

another category

![image](https://user-images.githubusercontent.com/14896455/197207105-d658809c-e891-48fc-818e-1e44de78dedc.png)

**Comment by Amoursol** [comment]
@ricardyn this is being worked on and should come out in a future release beyond Revit 2024 global launch.

**Comment by ParametricMonkey** [comment]
@Amoursol as noted in by forum post, this is still an issue and outstanding as of Dynmamo 2.18.1 (Revit 2024).

**Comment by ParametricMonkey** [comment]
@Amoursol, this is still an issue in Revit 2024.2 and Dynamo 2.19. When will this be fixed as it is pretty problematic?

**Comment by andydandy74** [comment]
Workaround: use built-in category names (https://www.revitapidocs.com/2018/ba1c5b30-242f-5fdc-8ea9-ec3b61e6e722.htm)

**Comment by Amoursol** [comment]
@ParametricMonkey this should have been resolved, so can you please let me know what specific case you have that is failing? 

Also, I would second @andydandy74 's point as it's a much safer and stable path moving forward.

**Comment by Amoursol** [comment]
This has now been fixed for Revit 2025. 

CC @Mikhinja
