### ISSUE TITLE
Cant upload my .dyn as a image to the Dynamo Forum 

### ISSUE THREAD

**Issue by drib1** [DynamoDS/DynamoRevit#2876]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

Dynamo 2.13.1.3887

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

Revit 2023

(Which version of Revit are you using?)

Windows 10

(e.g. Windows 7, Windows 8.1, etc)

I tried exporting a picture of my .dyn to post in on the Dynamo Forum

(Fill in here)

Expected to be posted

(Fill in here)

I was told the file qas to big to upload (max. 80 megapixels)
(Fill in here)
Here is a Screenshot of my script for size comparison

![gesamt](https://user-images.githubusercontent.com/117008385/198872241-94724afa-f926-4871-92d6-e43e18405282.PNG)

**Comment by Amoursol** [comment]
Hello @drib1 - This is an intended safeguard for the Forum around size of images. Users typically upload a link to a download location for file sizes that exceed our limits.
