### ISSUE TITLE
ElementWrapper Missing with Get Tap Of Pipe

### ISSUE THREAD

**Issue by chuongmep** [DynamoDS/DynamoRevit#2903]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.12

## Revit version

2022

## Operating system
Windows 10

## What did you do? 

Create a ZeroTouch Return Tap Of Pipe, 
```cs
 public static Elements.Element GetTap(Revit.Elements.Element pipe)
    {
        Autodesk.Revit.DB.Plumbing.Pipe? pipeInternalElement = pipe.InternalElement as Autodesk.Revit.DB.Plumbing.Pipe;
        FamilySymbol familySymbol = pipeInternalElement!.PipeType.Tap;
        Revit.Elements.Element tap = familySymbol.ToDynamoType();
        return tap;
    }
```
Then : 

Warning: Pipe.GetTap operation failed. 
The call is ambiguous between the following methods or properties: 'Revit.Elements.ElementWrapper.Wrap(Autodesk.Revit.DB.RoofType, bool)' and 'Revit.Elements.ElementWrapper.Wrap(Autodesk.Revit.DB.ScheduleSheetInstance, bool)'
![ảnh](https://user-images.githubusercontent.com/31106432/215712973-1919ea34-9e2d-41e9-941f-98cc83f09e20.png)

## What did you expect to see?

It will be work perfect

## What did you see instead?

(Fill in here)

**Comment by chuongmep** [comment]
Hi @Amoursol , any new update for this , same when we create new union fitting . 
```cs
TransactionManager.Instance.ForceCloseTransaction();
        using Autodesk.Revit.DB.Transaction tran = new Autodesk.Revit.DB.Transaction(firstPipe.InternalElement.Document, "Create Union Fitting");
        tran.Start();
        Connector? c1 = firstPipe.InternalElement.GetConnectorCloset(secondPipe.InternalElement);
        Connector? c2 = secondPipe.InternalElement.GetConnectorCloset(firstPipe.InternalElement);
        ElementId unionFitting = firstPipe.InternalElement.Document.Create.NewUnionFitting(c2, c1).Id;
        int idValue = unionFitting.IntegerValue;
        tran.Commit();
```
in this case unionFitting allway return null.

**Comment by QilongTang** [comment]
@wangyangshi Are you aware of this, should we forward this issue to Revit API team or?

**Comment by chuongmep** [comment]
I will add more topic I posted in forum to explain for this: https://forum.dynamobim.com/t/newunionfitting-allway-return-null-in-dynamo-revit/85939/1

**Comment by wangyangshi** [comment]
Hi @chuongmep  what is the function 'ToDynamoType'? I am trying to reproduce your issue, cannot find it in d4r codes?

**Comment by wangyangshi** [comment]
@chuongmep 
![image](https://user-images.githubusercontent.com/62596335/219021508-b1cedfed-864a-4486-8ec1-1f8c4d1df3c6.png)
I reproduced this issue, what I found is:
1 the property **Tap** is null, 
2 then in the function ToDSType, as it calles ElementWrapper.Wrap, for the null Element, it doesn't know which is the right wrap function should use, so throw the warn.
Do you think the null is abnormal in 1 ? 
Or we should make the warn message clear, for example adding a check in the function ToDSType before calling wrap.

**Comment by wangyangshi** [comment]
**pipeInternalElement.PipeType.Tap** is  **FamilySymbol** 
in fact this wrapper exists.
![image](https://user-images.githubusercontent.com/62596335/219023856-1bbd8afb-101f-4167-bbd9-b21fbf6aff9a.png)

**Comment by chuongmep** [comment]
@wangyangshi that is correct issue I want report, I have many methods is same problem now.

**Comment by wangyangshi** [comment]
1 Tap is null is abnormal, we need to investigate why it is null?
2 tap is null is expected, we just need to improve the warn message?
I am not very clear which one do you want, or both two?

**Comment by wangyangshi** [comment]
if you care about is 1, I will contact with related Revit API owner to seek for reasons, I am not very clear about MEP related.
if you care about is 2, we can do some improvement in d4r codes.

**Comment by chuongmep** [comment]
Hi @wangyangshi, I need confirm my issue for clear  : 
- Get Tap of Pipe I want return is result not null, because I had setting ensure it can work by Revit API Command and result return a tap, but when we develop script use zero touch node, it return is warning and also result is null
- If can, please also investigate reason why create a union by two connector also return result is null, in case it created a union fitting in project model, topic I had open in forum : https://forum.dynamobim.com/t/newunionfitting-allway-return-null-in-dynamo-revit/85939/3 . I think two case is same problem.
Hope it is cleary with you!

**Comment by wangyangshi** [comment]
OK, thank you, I will post these to related API teams.

**Comment by wangyangshi** [comment]
Hi @chuongmep what is the function 'GetConnectorCloset', I cannot find it in Revit API, we need to reproduce the NewUnionFitting issue, thank you again.

**Comment by chuongmep** [comment]
@wangyangshi 
I want provide for you some file to quick check : 
Rvt2022 : https://1drv.ms/u/s!AmKukXZ0HxiElqxoqongELn_BG4fEA?e=KckFGi
Scripts : https://1drv.ms/u/s!AmKukXZ0HxiElqxoqongELn_BG4fEA?e=mp3CEo

**Comment by wangyangshi** [comment]
I see 2 links are both RVT files?
![image](https://user-images.githubusercontent.com/62596335/219600960-7cdd4b61-b780-490f-aa9e-08d41e018c33.png)

**Comment by chuongmep** [comment]
> I see 2 links are both RVT files? ![image](https://user-images.githubusercontent.com/62596335/219600960-7cdd4b61-b780-490f-aa9e-08d41e018c33.png)

I updated, can help me try again ?

**Comment by wangyangshi** [comment]
Yes, it is the DYN file now.
![image](https://user-images.githubusercontent.com/62596335/219608078-77cdd0f7-0562-416a-875d-d7a57141a04b.png)

**Comment by wangyangshi** [comment]
Hi @chuongmep I contacted with other MEP related teams, got the reply, 
template file has no Pipe Tap fitting by default. And user need to load the tap to the project, and then set it to pipe type, thus user can get the tap element

1. In the project, load the tap family;
2. Select or Create Pipe -> Pipe Type -> Routing Preference -> change "Junction" to the tap family, and then change the junction type to "Tap"
I haven't tried this yet, just wander do you miss these steps then return the null tap?

**Comment by chuongmep** [comment]
@wangyangshi, many thanks for @wangyangshi about tap, I resolved from my side, how about issue with create union fitting ?

**Comment by wangyangshi** [comment]
@chuongmep 
the API NewUnionFitting calls RbsEditorUtils::insertUnion in Revit, in fact the union element is created, but in this function, there is a check, if union element type is no REPT_Union, it will return null.
I use your RVT&DYN file to test, the union element type is REPT_Transition, so although union element created successfully,
it still returns null.

**Comment by chuongmep** [comment]
@wangyangshi, it means is this is correct null with Revit API ?

**Comment by wangyangshi** [comment]
Yes, I see these code hasn't been changed for many years, I think this is by design.
in the forum someone recommends using  NewTransitionFitting, because your return element Type is REPT_Transition, from the function name I think this should be the suitable method for you, would you please have a try?

**Comment by wangyangshi** [comment]
![image](https://user-images.githubusercontent.com/62596335/220586885-92947bce-7298-4e08-85bd-e50fc6b00a8e.png)
all these `NewXXXFitting` methods check element type if match then return the element, if not match then return null, so you may need to use the corresponding function.

**Comment by chuongmep** [comment]
Thanks, @wangyangshi, this is clear with me now, thanks for your supported, maybe I need some trick to help user get it.
