### ISSUE TITLE
Export as Image Does Nothing

### ISSUE THREAD

**Issue by Teflon98** [DynamoDS/DynamoRevit#2907]
## Dynamo version

v2.16.1
Core 2.16.1.2727
Dynamo Revit 2.16.1.650

## Revit version

Revit 2023.1

## Operating system

Windows 10 Pro 21H2

## What did you do? 

Export as Image -> Workspace

## What did you expect to see?

Expected to have a dialog box open to save the image

## What did you see instead?

Nothing happens.  Tried selecting the Background 3D Preview and nothing happens.  Both options highlight with mouse hover but clicking does nothing.

**Comment by chuongmep** [comment]
Hi Dynamo Team @QilongTang  @Amoursol , Any update for that ?

**Comment by QilongTang** [comment]
Indeed, ⚒️
