### ISSUE TITLE
Dynamo takes too long to open

### ISSUE THREAD

**Issue by Avery-Sanders** [DynamoDS/DynamoRevit#3034]
### Dynamo Version

DYNAMO v.2.16.2

### Revit Version

Revit 2023

### Operating System

Windows 10

### What did you do?

I opened a project in Revit 2023. I then clicked on the "Dynamo" button within the "Manage" tab "Visual Programming" label.

### What did you expect to see?

Dynamo opening in 30 seconds or less.

### What did you see instead?

It took six minutes and 3 seconds to open.

### Stacktrace/logs

[dynamoLog_a9cf4cfb-4fb6-452d-8de0-9fa09f249735.txt](https://github.com/DynamoDS/DynamoRevit/files/14057844/dynamoLog_a9cf4cfb-4fb6-452d-8de0-9fa09f249735.txt)

### Details

![image](https://github.com/DynamoDS/DynamoRevit/assets/157755419/3031b07f-5c99-40c6-9f60-d97d463818f7)

**Comment by mjkkirschner** [comment]
1. Does this reproduce every time?
2. Is this a new behavior?
3. Can you try disabling analytics in Revit etc, rebooting Revit and opening Dynamo again, any change?
4. Does this machine have slow internet?
5. How many packages do you have installed? If you remove them does it reproduce?
6. Do you see the same behavior with 2.16.2 dynamo sandbox from the daily build site? https://dynamobuilds.com

**Comment by Avery-Sanders** [comment]
Hello. To answer mjkkirschner's questions:

1. Yes it did.
2. Yes it was.
3. I tried uninstalling and reinstalling RVT 2023 completely which didn't fix it.
4. No
5. I removed all packages and still had the same issue.
6. I don't have sandbox installed.

HOWEVER, it started working yesterday after I uninstalled the following programs:

Dynamo 0.9.1
Dynamo Revit 1.3.4

**Comment by Avery-Sanders** [comment]
Actually, scratch that. When I said it started working, what I meant was it was easier to search for packages and install them. That was also slower prior to uninstalling the former Dynamo versions. 

This morning it took about 18 minutes for Dynamo to open, though the log will say only 6. 

[dynamoLog_fb788e6e-4166-4249-8531-afe189f37a0e.txt](https://github.com/DynamoDS/DynamoRevit/files/14066267/dynamoLog_fb788e6e-4166-4249-8531-afe189f37a0e.txt)

**Comment by mjkkirschner** [comment]
3. uninstall won't change those settings
try going to:
https://profile.autodesk.com/settings
and disabling the privacy options here so minimal data is sent.

**Comment by Avery-Sanders** [comment]
I tried that but it didn't work.

However, after finding other articles on other forums and trying their solutions as well and still not getting anywhere, I tried disabling loading the built-in and custom packages. Now it loads like a charm.

![image](https://github.com/DynamoDS/DynamoRevit/assets/157755419/3c0b8eef-bb67-4aea-a625-ceb3970e18bc)

**Comment by Avery-Sanders** [comment]
I have only one .dyn file that I just created. It was using a custom package, biomorphNodes. I deleted all the other custom packages but kept that one and unchecked disable loading custom packages. Dynamo still loads quickly.

**Comment by mjkkirschner** [comment]
@twastvedt @saintentropy @BogdanZavu to me it sounds like an issue with player,gd etc, any thoughts?

**Comment by mjkkirschner** [comment]
@Avery-Sanders - so what packages did you delete?

**Comment by Avery-Sanders** [comment]
![image](https://github.com/DynamoDS/DynamoRevit/assets/157755419/1fdf083b-3dc8-4207-b99c-806f885315bb)

Not sure which versions. These were all downloaded yesterday around 4:30 PM EST so whatever the current versions of them were as of yesterday.

**Comment by BogdanZavu** [comment]
@mjkkirschner I don't think it's an issue with the packages. I think it is the slowdown induced by adp tracking. This was fixed in 2.18.1 . It would explain why sometimes loads fast and sometimes doesn't. 
This would be the [PR](https://github.com/DynamoDS/Dynamo/pull/13678/files) that fixed the issue back then.

**Comment by mjkkirschner** [comment]
Hey @BogdanZavu i guessed the same as well but the user reported disabling adp via adsk prefs did not help - would you expect that change to make no improvement as it needs to make a network request in either case?

**Comment by BogdanZavu** [comment]
@mjkkirschner Yes, the actual slowdown was during checking if reporting analytics is true which was performed on every call to track something.
