### ISSUE TITLE
Dynamo inside Revit not working and throwing Exceptions

### ISSUE THREAD

**Issue by RoushanArshid** [DynamoDS/DynamoRevit#3037]
### Dynamo Version

Latest

### Revit Version

2024.1

### Operating System

Windows 10

### What did you do?

Opened Revit to start working, launched dynamo inside revit and threw exception.

![image](https://github.com/DynamoDS/DynamoRevit/assets/27721764/8887a54f-7d66-4267-9f7d-0084440b1d22)

### What did you expect to see?

dynamo basic launch interface 

### What did you see instead?

This error
![image](https://github.com/DynamoDS/DynamoRevit/assets/27721764/238ca454-612a-4741-8135-666305d62071)

**Comment by mjkkirschner** [comment]
See this issue-
https://github.com/DynamoDS/Dynamo/issues/14891

Use a version which is lower than 1.2 of ironPython3 package.
