### ISSUE TITLE
JsonObject.GetValueByKey transforming

### ISSUE THREAD

**Issue by MarcSp74** [DynamoDS/DynamoRevit#3060]
### Dynamo Version

Dynamo Core 2.13.1.3887
Dynamo Revit 2.13.1.3891
(up-to-date)

### Revit Version

Autodesk Revit 2023

### Operating System

Windows 10

### What did you do?

Using the node _JsonObject.GetValueByKey_ from the package JsonData 2.0.2 and save it in a script and save it in a custom node

### What did you expect to see?

not to change when reopening the script or the custom node

### What did you see instead?

it's expanding

### Stacktrace/logs

It could be possible that more nodes are expanding. 
All nodes from the JsonData-package combined in png-file attachment:
on the left the original, on the right the transformed ones after reopening the script.
The second image  is another reopening of the script: the expanding continues...

[JsonData transformations](https://github.com/DynamoDS/DynamoRevit/assets/166063939/1067253c-7acc-4f9e-8647-ae75018ca089)

[JsonData transformations 2](https://github.com/DynamoDS/DynamoRevit/assets/166063939/bad0217c-d236-42fe-88da-6bc388e3aea8)

**Comment by mjkkirschner** [comment]
https://github.com/DynamoDS/DynamoRevit/issues/2359

**Comment by avidit** [comment]
@MarcSp74 Can you uninstall any Revit add-ins and try the node again?
