### ISSUE TITLE
Get Family Parameter node improvement

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/DynamoRevit#939]
Team, 

cc: @ikeough @mjkkirschner @kronz  (I am not sure who's working on this)
I think there is a clean way to return parameters that you could implement in Get Family Parameter node. I might be wrong on this, but it has worked for me so far. 

This is the node that I am talking about: https://github.com/DynamoDS/DynamoRevit/blob/91f35d6e3762aa8b7da19043fde41e73e2a86f4d/src/Libraries/RevitNodesUI/RevitDropDown.cs

Please consider this instead: 

Don't cast elements passed in as input into <code>FamilyInstance</code> or <code>WallType</code> etc. As a matter of fact just leave them be as <code> Element </code>. 

Then you can get all parameters from an element and if that element is an instance you can also get its type parameters using this utility method: 

```C#
private void AddElementParams(Element e)
        {
            foreach (Parameter p in e.Parameters)
            {
                if (!(p.StorageType == StorageType.None))
                {
                    AddDropDownItem(p);
                }
            }
            // if element can have type assigned it's safe to assume that it's an instance
            // and add type parameters to the list
            if (e.CanHaveTypeAssigned())
            {
                ElementType et = DocumentManager.Instance.CurrentDBDocument.GetElement(e.GetTypeId()) as ElementType;
                if (et != null)
                {
                    AddTypeParams(et);
                }
            }
        }

private void AddTypeParams(ElementType et)
        {
            foreach (Parameter p in et.Parameters)
            {
                if (p.StorageType == StorageType.None)
                    continue;

                AddDropDownItem(p);
            }
        }
```
As you can see I am making a simple check <code> e.CanHaveTypeAssigned()</code> to see if element has also element type parameters available and this seems to be just good enough. 

This way, I can handle both, instances, as well as types being passed in as inputs and do away with type specific casting. 

Please let me know if this helps. Here are some results: 

![paramlister](https://cloud.githubusercontent.com/assets/529781/14086725/90fd934e-f4f4-11e5-897e-33d0334f6695.PNG)

**Comment by kronz** [comment]
@ksobon @ikeough @Randy-Ma Hey Konrad.  This looks very cool.  It's been a long time since we looked at this one.  Get Family Paramters works really differently than anything else, needing to run once before the UI can be populated has created some problems in the past.  But I love the idea of having a more generalized Get Parameters functionality. Randy/Ian, any obvious problems with this approach?

**Comment by ke-yu** [comment]
Fix in https://github.com/DynamoDS/DynamoRevit/pull/1015
