### ISSUE TITLE
1.0 Version switcher showing wrong 0.9 version number

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#983]
## Dynamo version

1.0.0 stable (1.0.0.1180)
## Operating system

Win 7
## What did you do?

Use the version switcher in the Revit ribbon
## What did you expect to see?

The correct version numbers
## What did you see instead?

Dynamo 0.9.0 is displayed as Dynamo 0.9.1

![versionswitcher](https://cloud.githubusercontent.com/assets/3014437/15070792/02f8c3dc-1387-11e6-8e0d-a43f14659592.png)
![dynamo09](https://cloud.githubusercontent.com/assets/3014437/15070795/08a12cf2-1387-11e6-9fc2-ec8ff157daef.PNG)

**Comment by kronz** [comment]
fyi @sharadkjaiswal

**Comment by QilongTang** [comment]
@andydandy74 As Dynamo evolves, we are probably not going to fix this particular instance. However, if you saw this again in future Dynamo versions, please re-open and let us know
