### ISSUE TITLE
NewFloor Method causing crash

### ISSUE THREAD

**Issue by Jezzzza** [DynamoDS/DynamoRevit#990]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.

## Dynamo version

1.0

## Revit version

2016

## Operating system

Windows 10

## What did you do? 

Tried flattened list of curves on Floor.ByOutlineTypeAndLevel node.
Tried same list as closed polycurve on same related node with polycurve input
Tried python revit api method Document.NewFloor method.

## What did you expect to see?

A new floor in revit

## What did you see instead?

a never ending loop until Revit crashes. I've tried rebuilding the curves in every which way but always causes Dynamo to crash.

**Comment by kronz** [comment]
@Jezzzza Take a look at the File in Help>Samples>Revit that shows how to construct floors.  
![2016-05-11_1314](https://cloud.githubusercontent.com/assets/3456818/15189788/a739e9fc-177a-11e6-869e-30705e1a575c.png)

**Comment by Jezzzza** [comment]
Thanks Kronz, I found it was crashing when update was set to Auto, works on manual.
