### ISSUE TITLE
Dynamo 0.6.3 crashes on exit in Revit 2012

### ISSUE THREAD

**Issue by jonathanroy8676** [DynamoDS/DynamoRevit#994]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.
## Dynamo version

0.6.3.7993
## Revit version

Revit MEP 2012
## Operating system

Win 7
## What did you do?

As per suggested in [Forum](http://dynamobim.org/forums/topic/revit-2012-what-dynamo-build/) 
- I downloaded and installed the 0.6.3 build from the most stable section. 
- Installed it on my station for Revit 2013/2014
- Opened Revit 2014, opened blank family, opened Dynamo, closed = OK
- Found the addin file in 2014 folder and pasted it in 2012 folder (C:\ProgramData\Autodesk\Revit\Addins\2012)
- Opened Revit MEP 2012, opened blank family, opened Dynamo, searched for 0.6 packages
- Installed Lunchbox & Clockwork 0.6
- File > Exit Dynamo
## What did you expect to see?

Dynamo close normally
## What did you see instead?
- "Dynamo has crashed" message
  Could not load type 'Autodesk.Revit.UI.RevitCommandId' from assembly 'RevitAPIUI, Version=2012.0.0.0, Culture=neutral, PublicKeyToken=null'.
  
  at Dynamo.DynamoController_Revit.ShutDown(Boolean shutDownHost)
  at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
  at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate cal

Dynamo Packages:
![image](https://cloud.githubusercontent.com/assets/16231080/15253215/5b348d42-18ff-11e6-8005-38dcb6d44038.png)
File > Exit
![image](https://cloud.githubusercontent.com/assets/16231080/15253230/6b845eb6-18ff-11e6-889d-3c9970320456.png)

**Comment by mjkkirschner** [comment]
@jonathanroy8676 I'll have to check, but I don't think we ever supported Revit 2012, and I don't think 63 ever ran on 2012... the error is basically saying as much - we're trying to call a method that docent exist in the 2012 API since I don't think we ever supported it.

**Comment by jonathanroy8676** [comment]
Ok. I'd say most of them work except a couple of the Clockwork Package that have to do with Family Instances By Category. I'll see how far I can get and/or work around what doesn't work.
![image](https://cloud.githubusercontent.com/assets/16231080/15253739/9f3eb72c-1901-11e6-864f-77126f9e65c6.png)
If nothing more can be done after you've checked, you can close the issue. At least we tried.

**Comment by mjkkirschner** [comment]
@jonathanroy8676 if you must work on 2012 - there is no reason you could not edit the clockwork nodes (I believe many are python) and change the revit api calls to make sure they conform with the 2012 API, you could even reshare them for other 2012 users.

**Comment by jonathanroy8676** [comment]
@mjkkirschner I'm justing getting around Dynamo in Revit 2016 with build 0.9 +.  I can open up a python node but I unfortunetly have no idea how to make it conform to the 2012 API... 
The more I try to go deeper the more crashes happen, so I think I'll have to wait till the project gets updated eventually. I was just happy with the basic things I could do with Dynamo in 2016 that I wanted to explore it in our mega hospital project that is stuck in 2012 for the moment.

**Comment by jonathanroy8676** [comment]
tried with the 0.7.1 version and still get an error message. (installed for the 2014 and copied in 2012 addin folder) Seems 2012 is out of it ;) Well at least I have Dynamo on 2016/17 to make me feel better ;)
![image](https://cloud.githubusercontent.com/assets/16231080/15258695/fa864ac8-191a-11e6-841f-6c66082280a3.png)

**Comment by kronz** [comment]
Sorry, we are not supporting 0.6.3 anymore, please update to a more recent version.  Thanks
