### ISSUE TITLE
package manager is empty

### ISSUE THREAD

**Issue by AndrewHeumann** [DynamoDS/DynamoRevit#995]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.

## Dynamo version

1.0

## Revit version

2015

## Operating system

windows 7

## What did you do? 

go to the package manager

## What did you expect to see?

packages

## What did you see instead?

(Fill in here)
![image](https://cloud.githubusercontent.com/assets/2157902/15297166/bc25024e-1b66-11e6-8506-06900ee2820a.png)

**Comment by jnealb** [comment]
@AndrewHeumann This is tracked with MAGN-10106. Thanks.

**Comment by mjkkirschner** [comment]
@AndrewHeumann just something to try: open dynamoyackges.com in your browser at the same time. Are you behind a firewall? on your personal machine? etc...

**Comment by AndrewHeumann** [comment]
it worked earlier today. dynamopackages.com (I assume that's what you meant) does not load. http://www.downforeveryoneorjustme.com/dynamopackages.com - appears the site is down.

**Comment by jnealb** [comment]
@AndrewHeumann Can you please try now?

**Comment by AndrewHeumann** [comment]
yes it's working now.
